In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/DL

/content/drive/MyDrive/DL

### Downloading data

In [ ]:
import os
os.environ["KAGGLE_CONFIG_DIR"]="/content/drive/MyDrive/.kaggle"

In [ ]:
!kaggle

usage: kaggle [-h] [-v] [-W]
              {competitions,c,datasets,d,kernels,k,models,m,files,f,config,auth}
              ...
kaggle: error: the following arguments are required: command

In [ ]:
!kaggle datasets download kapilverma/hindi-bible --unzip --force

Dataset URL: https://www.kaggle.com/datasets/kapilverma/hindi-bible
License(s): ODbL-1.0
Downloading hindi-bible.zip to /content/drive/MyDrive/DL
100% 4.82M/4.82M [00:00<00:00, 36.3MB/s]

In [ ]:
!kaggle datasets download aiswaryaramachandran/hindienglish-corpora --unzip

Dataset URL: https://www.kaggle.com/datasets/aiswaryaramachandran/hindienglish-corpora
License(s): copyright-authors
Downloading hindienglish-corpora.zip to /content/drive/MyDrive/DL
100% 13.9M/13.9M [00:00<00:00, 67.8MB/s]

In [ ]:
!kaggle datasets download preetviradiya/english-hindi-dataset --unzip

Dataset URL: https://www.kaggle.com/datasets/preetviradiya/english-hindi-dataset
License(s): GNU Free Documentation License 1.3
Downloading english-hindi-dataset.zip to /content/drive/MyDrive/DL
100% 13.9M/13.9M [00:00<00:00, 64.4MB/s]

In [ ]:
!kaggle datasets download vaibhavkumar11/hindi-english-parallel-corpus --unzip --force

Dataset URL: https://www.kaggle.com/datasets/vaibhavkumar11/hindi-english-parallel-corpus
License(s): unknown
Downloading hindi-english-parallel-corpus.zip to /content/drive/MyDrive/DL
100% 112M/112M [00:04<00:00, 24.2MB/s]

In [ ]:
!kaggle datasets download disisbig/hindi-text-short-summarization-corpus --unzip

Dataset URL: https://www.kaggle.com/datasets/disisbig/hindi-text-short-summarization-corpus
License(s): CC-BY-SA-4.0
Downloading hindi-text-short-summarization-corpus.zip to /content/drive/MyDrive/DL
100% 366M/366M [00:03<00:00, 119MB/s]

In [ ]:
!kaggle datasets download disisbig/hindi-wikipedia-articles-172k --unzip

Dataset URL: https://www.kaggle.com/datasets/disisbig/hindi-wikipedia-articles-172k
License(s): CC-BY-SA-4.0
hindi-wikipedia-articles-172k.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
from zipfile import ZipFile
with ZipFile('hindi-bible.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()
   print("Done!")

Done!

In [ ]:
from zipfile import ZipFile
with ZipFile('hindienglish-corpora.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()
   print("Done!")

Done!

In [ ]:
from zipfile import ZipFile
with ZipFile('english-hindi-dataset.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()
   print("Done!")

Done!

In [ ]:
from zipfile import ZipFile
with ZipFile('hindi-english-parallel-corpus.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()
   print("Done!")

Done!

In [ ]:
from zipfile import ZipFile
with ZipFile('hindi-text-short-summarization-corpus.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()
   print("Done!")

Done!

### Importing data

In [ ]:
bible_text = open("Full_text_Bible.txt", "r", encoding='utf-8').read()
wiki_text = open("hindi_text.txt", "r", encoding='utf-8').read()

In [ ]:
import pandas as pd
hindi_eng = pd.read_csv("Hindi_English_Truncated_Corpus.csv")
eng_hindi = pd.read_csv("Dataset_English_Hindi.csv")
hindi_eng_parallel = pd.read_csv("hindi_english_parallel.csv")

In [ ]:
bible_text[:1000]

In [ ]:
wiki_text[:1000]

In [ ]:
wiki_text.replace(" · ", " ").replace(" · ", " ")[:1000]

In [ ]:
" · " == " · "

True

In [ ]:
wik_text = wiki_text.replace(" · ", " ").replace(" · ", " ")

In [ ]:
hindi_eng

,source,english_sentence,hindi_sentence
0,ted,politicians do not have permission to do what ...,"राजनीतिज्ञों के पास जो कार्य करना चाहिए, वह कर..."
1,ted,"I'd like to tell you about one such child,",मई आपको ऐसे ही एक बच्चे के बारे में बताना चाहू...
2,indic2012,This percentage is even greater than the perce...,यह प्रतिशत भारत में हिन्दुओं प्रतिशत से अधिक है।
3,ted,what we really mean is that they're bad at not...,हम ये नहीं कहना चाहते कि वो ध्यान नहीं दे पाते
4,indic2012,.The ending portion of these Vedas is called U...,इन्हीं वेदों का अंतिम भाग उपनिषद कहलाता है।
...,...,...,...
127602,indic2012,Examples of art deco construction can be found...,आर्ट डेको शैली के निर्माण मैरीन ड्राइव और ओवल ...
127603,ted,and put it in our cheeks.,और अपने गालों में डाल लेते हैं।
127604,tides,"As for the other derivatives of sulphur , the ...","जहां तक गंधक के अन्य उत्पादों का प्रश्न है , द..."
127605,tides,its complicated functioning is defined thus in...,Zरचना-प्रकिया को उसने एक पहेली में यों बांधा है .
127606,ted,They've just won four government contracts to ...,हाल ही में उन्हें सरकारी ठेका मिला है करीब सौ ...

In [ ]:
eng_hindi

,English,Hindi
0,Help!,बचाओ!
1,Jump.,उछलो.
2,Jump.,कूदो.
3,Jump.,छलांग.
4,Hello!,नमस्ते।
...,...,...
130471,Examples of art deco construction can be found...,आर्ट डेको शैली के निर्माण मैरीन ड्राइव और ओवल ...
130472,and put it in our cheeks.,और अपने गालों में डाल लेते हैं।
130473,"As for the other derivatives of sulphur , the ...","जहां तक गंधक के अन्य उत्पादों का प्रश्न है , द..."
130474,its complicated functioning is defined thus in...,Zरचना-प्रकिया को उसने एक पहेली में यों बांधा है .
130475,They've just won four government contracts to ...,हाल ही में उन्हें सरकारी ठेका मिला है करीब सौ ...

In [ ]:
hindi_eng_parallel

,hindi,english
0,अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें,Give your application an accessibility workout
1,एक्सेर्साइसर पहुंचनीयता अन्वेषक,Accerciser Accessibility Explorer
2,निचले पटल के लिए डिफोल्ट प्लग-इन खाका,The default plugin layout for the bottom panel
3,ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका,The default plugin layout for the top panel
4,उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से नि...,A list of plugins that are disabled by default
...,...,...
1561836,स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...,स्पष्टीकरण.–जहां इस उपधारा के अधीन हानि और लाभ...
1561837,मैंने गौर किया है कि यह न केवल अपने महत्त्वपूर...,है। I note that this is a landmark meeting – n...
1561838,उन्होंने मेरे समक्ष जो प्रदर्शन किया उसमें से ...,है। In the presentations that they made before...
1561839,खाद्य और जल सुरक्षा; पर्यावरण की दृष्टि से वहन...,्त है। Issues such as food and water security;...
1561840,NaN,NaN

In [ ]:
hindi_eng = hindi_eng["hindi_sentence"].str.cat(sep='। ').replace(".", "")

In [ ]:
eng_hindi = eng_hindi["Hindi"].str.cat(sep='। ')

In [ ]:
hindi_eng_parallel = hindi_eng_parallel["hindi"].dropna().str.cat(sep='। ').replace(".", "")

In [ ]:
hindi_eng[:1000]

'राजनीतिज्ञों के पास जो कार्य करना चाहिए, वह करने कि अनुमति नहीं है । मई आपको ऐसे ही एक बच्चे के बारे में बताना चाहूंगी,। यह प्रतिशत भारत में हिन्दुओं प्रतिशत से अधिक है।। हम ये नहीं कहना चाहते कि वो ध्यान नहीं दे पाते। इन्हीं वेदों का अंतिम भाग उपनिषद कहलाता है।। कश्मीर के तत्कालीन गवर्नर ने इस हस्तांतरण का विरोध किया था , लेकिन अंग्रेजों की सहायता से उनकी आवाज दबा दी गयी । इसमें तुमसे पूर्व गुज़रे हुए लोगों के हालात हैं।। और हम होते कौन हैं यह कहने भी वाले कि वे गलत हैं। ग्लोबल वॉर्मिंग से आशय हाल ही के दशकों में हुई वार्मिंग और इसके निरंतर बने रहने के अनुमान और इसके अप्रत्यक्ष रूप से मानव पर पड़ने वाले प्रभाव से है।। हो सकता है कि आप चाहते हों कि आप का नऋर्नमेनटेन्ड ह्यबिना किसी समर्थन के हृ विशेष स्कूल , या किसी स्वतंत्र स्कूल में जाए , इजसके पास विशेष शैक्षणिक जऋऋरतों वाले बच्चों के प्रति सहूलियत हों  । कृपया यह सुनिश्चित कर लें कि आप सही फॉर्म का प्रयोग कर रहें हैं । श्रेणी:धर्मग्रन्थ। यह काल समग्रतः भक्ति भावना से ओतप्रोत काल है।। तो वहाँ न्याय है। पहले दो को अविश्वसनीय मानकर बाक'

In [ ]:
eng_hindi[:1000]

'बचाओ!। उछलो.। कूदो.। छलांग.। नमस्ते।। नमस्कार।। वाह-वाह!। चियर्स!। समझे कि नहीं?। मैं ठीक हूँ।। बहुत बढ़िया!। अंदर आ जाओ।। बाहर निकल जाओ!। चले जाओ!। ख़ुदा हाफ़िज़।। उत्तम!। सही!। आपका स्वागत है।। स्वागतम्।। मज़े करना।। मौज करना।। मज़े करो।। मैं भूल गया।। मैं भूल गई।। मैं पैसे दूंगा।। मैं ठीक हूँ।। मेरा पेट भर गया है।। चलो चलें!। मुझे जवाब दो।। पंछी उड़ते हैं।। माफ़ कीजिए।। बहुत ख़ूब!। खेद की बात है, लेकिन वैसा ही है।। मैं हँसा।। मैं बोर हो रहा हूँ।। मेरा दीवालिया हो चुका है।। मैं थक गया हूँ।। ठंड हो रही है।। कौन जाने?। किसको पता है?। किसे पता है?। किसे मालूम है?। अद्भुत। पंछी गाते हैं।। अंदर आ जाओ।। निश्चित ही। हिलो मत।। आग जलाती है।। उसका पीछा करो।। मैं थक गया हूँ।। मुझे तैरना आता है।। मैं तैर सकता हूँ।। मैं तुमसे प्यार करती हूँ।। मैं तुमसे प्यार करता हूँ।। मैं आपसे प्यार करता हूँ।। मैं आपसे प्यार करती हूँ।। मुझे तुमसे प्यार है।। मैं कोशिश करूँगा।। मैं आ रहा हूँ।। मुझे भूख लगी है!। मुझे भूख लगी है।। उसे अंदर भेजो।। उसे अंगर आने दो।। मुझे बाहर जाने दो!। और एक बार।। बैठिए।। क्या नया है?'

In [ ]:
hindi_eng_parallel[:1000]

'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें। एक्सेर्साइसर पहुंचनीयता अन्वेषक। निचले पटल के लिए डिफोल्ट प्लग-इन खाका। ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका। उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से निष्क्रिय किया गया है। अवधि को हाइलाइट रकें। पहुंचनीय आसंधि (नोड) को चुनते समय हाइलाइट बक्से की अवधि। सीमांत (बोर्डर) के रंग को हाइलाइट करें। हाइलाइट किए गए सीमांत का रंग और अपारदर्शिता। । भराई के रंग को हाइलाइट करें। हाइलाइट किया गया भराई का रंग और पारदर्शिता। । एपीआई विचरक। इस समय जिसे प्राप्त किया गया हो, उसकी विभिन्न विधियों (मेथड) में विचरण करें। निजी गुणों को छिपाएं। विधि। गुणधर्म। मान। आईपाइथन कन्सोल। इस समय चुने गए एक्सेसेबेल से काम लेने के लिए अंतर्क्रियात्मक कन्सोल। घटना मानिटर। घटनाओं को मानिटर करें (_ M) । चुनाव को हटाएं (C _) । सभी। चुने गए अनुप्रयोग। चुने गए एक्सेसेबेल। स्रोत। घटना मानिटर। चुने गए प्रकारों और स्रोतों से घटनाएं जैसे-जैसे घटित होती हैं, उन्हें दर्शाता है। अंतिम प्रविष्ट घटना को हाइलाइट करो। घटना रेकोर्डिंग शुरू करो/रोको। घटना रोजनामचा मिटाओ। कोई विवरण नहीं। '

In [ ]:
data = bible_text + hindi_eng + eng_hindi + hindi_eng_parallel + wiki_text

In [ ]:
len(data.split(" "))

81225040

In [ ]:
data.split(" ")[-1]

'था।\n\n'

In [ ]:
with open("total_data.txt", 'w') as text_file:
  # 4. Write the string to the file
  text_file.write(data)

In [ ]:
data = open("total_data.txt", "r").read()

In [ ]:
data[-100000:]

'िना हमारे देश में शिक्षा का स्तर उठाना संभव नहीं होगा।। 2200 से अधिक विद्यार्थियों, जिनमें 700 पीएचडी विद्यार्थी हैं, तथा इसके प्रत्येक संकाय द्वारा संकाय बहुत से पेटेंटों और अनुसंधान पर्चों के साथ यह प्रख्यात संस्थान निश्चित रूप से तकनीकी शिक्षा में अधिक ऊंचाइयां प्राप्त करेगा।। अपने40से अधिक अकादमिक विभागों, 20 स्नातकोत्तर पाठ्यक्रमों तथा8 सुपर स्पेशियलिटी कार्यक्रमों के साथ यह चिकित्सा विद्यालय,चिकित्सा शिक्षा के विभिन्न क्षेत्रों में शिक्षा प्रदान कर रहा है।। देश के4300 प्रौद्यागिकी स्टार्टअप के साथ,भारत विश्व की तीसरी विशालतम स्टार्टअप प्रणाली के रूप में उभरा है।। 4500 स्टार्ट-अप के साथ भारत में विश्व का तीसरा सबसे विशाल स्टार्टअप वातावरण है। स्टार्ट-अप इंडिया कार्यक्रम के अंतर्गत नई पहल निस्संदेह इस प्रयास को सही दिशा में आगे बढ़ाएगी।। 44केंद्रीय विश्वविद्यालयों तथा लगभग36,000 कॉलेजों सहित 700से अधिक विश्वविद्यालयों के साथ आज भारत में विश्व की एक सबसे विशाल उच्च शिक्षा प्रणाली है।। वर्ष2016में88लाख से अधिक विदेशी पर्यटक भारत आए जिससे पर्यटन क्षेत्र में10प्रतिशत से अधिक की वृद्धि हुई है।। अर्जुन सिंह जी का आठ वर्ष का मानव संसाधन विकास मंत्री के रूप में कार्यकाल मौलाना अबुल कलाम आजाद के बाद सबसे लंबा था।। एक बिलियन मोबाइल फोन के साथ सूचना और संचार प्रौद्योगिकी क्षेत्र हमारे देश के विकास और परिवर्तन के अगले चरण के लिए एक प्रमुख मंच बनने जा रहा है।। सत्तर हजार से अधिक शहीदों तथा उतने ही अंगविहीन और घायलों के साथ इन भारतीय सैनिकों ने भारतीय सशस्त्र बलों के भावी योद्धाओं के लिए एक स्थाई मिसाल छोड़ी है।। पारम्परिक पद्धतियों के सुचारू विकास एवं अध्ययन तथा आधुनिक विज्ञान से अब हमें उपलब्ध उपस्करों का मौलिक रूप से उपयोग करके, आयुर्वेद सहित पारम्परिक चिकित्सा पद्धतियां सर्वांगीण स्वास्थ्य सेवा प्रणाली का महत्वपूर्ण और वहनीय हिस्सा बन सकती हैं।। विज्ञान शिक्षा और अनुसंधान में तेजी से आ रहे बदलावों से प्रौद्योगिक बढ़त वाले देश ही कड़े स्पर्द्धात्मक विश्व-बाजार में सफल होंगे।। विज्ञान,शिक्षा और अनुसंधान से तेजी से आ रहे बदलावों से प्रौद्योगिकी बढ़त वाले देश ही प्रतिस्पर्द्धात्मक विश्व बाजार में सफल होंगे।। सुलभता से उपलब्ध कुशल मानव संसाधन के माध्यम से भारत सॉफ्टवेयर सहित रक्षा विनिर्माण के क्षेत्र में एक विश्वव्यापी प्लेटफॉर्म के रूप में उभर सकता है, जिससे हमारी रक्षा सुदृढ़ होगी और देश में औद्योगिक विकास और निर्यात में तेज़ी आएगी।। रोजगार की तलाश में विदेश गए इन अस्थायी प्रवासियों के संबंध में यह बुद्धिमतापूर्ण होगा कि उनके कौशल उन्नयन के प्रति ध्यान दिया जाए।। जहां तक सक्षम स्वास्थ्य सेवा पेशेवरों की पर्याप्त संख्या का संबंध है बारहवीं योजना में एक लाख लोगों पर 354 चिकित्सा पेशेवरों का औसत लक्ष्य किया गया है।। मूर्त सांस्कृतिक विरासत के संबंध में , यह मंत्रालय भारतीय पुरातत्व सर्वेक्षण के माध्यम से केंद्रीय रुप से सरंक्षित राष्ट्रीय महत्त्व के स्मारकों का रखरखाव करता है ।। 1966 में शास्त्रीजी के देहावसान के बाद देश के समक्ष यह प्रश्न आया कि राष्ट्र का नेतृत्व कौन करेगा।। 1200 छात्रों की संख्या वाला यह विश्वविद्यालय इस क्षेत्र के युवाओं के भाग्य को बनाने के लिए सही दिशा में आगे बढ़ रहा है।। सफलता के साथ जिम्मेदारी आती है। बड़ी सफलता के साथ बड़ी जिम्मेदारियां आती हैं।। घाना सरकार तथा घाना निवेश संवर्द्धन परिषद जैसे संगठनों की सक्रिय भागीदारी से हम निवेश करने के लिए भारतीय निजी क्षेत्र हेतु व्यवहार्य परियोजनाओं की मिलकर पहचान कर सकते हैं।। घाना सरकार तथा घाना निवेश संवर्धन परिषद जैसे संगठनों की सक्रिय भागीदारी से हम निवेश के लिए भारतीय निजी क्षेत्र हेतु व्यवहार्य परियोजनाओं की पहचान कर सकते हैं।। जुलाई, 2004 में सात और समितियों के गठन के साथ, यद्यपि इन समितियों की सदस्यता को घटाकर राज्य सभा के 10 सदस्य और लोक सभा के 21 सदस्य कर दी गयी थी, विभाग-संबंधित संसदीय स्थायी समितियों की संख्या बढ़ाकर 24 कर दी गई जिनमें से 8 को राज्य सभा के सभापति के अधिकारक्षेत्र में और 16 को लोक सभा अध्यक्ष के अधिकारक्षेत्र में रखा गया।। संचार प्रौद्योगिकी में प्रगति से सूचनाओं के बढ़ते प्रवाह के कारण शिक्षकों को न केवल उपलब्ध सूचना से फायदा उठाने बल्कि सूचनाओं के बढ़ते प्रवाह के दबाव में न आने के लिए विद्यार्थियों का मार्गदर्शन करना चाहिए।। ज्ञान संसाधनों तक समान और सभी की पहुंच बनाने के लक्ष्य से, भारत का राष्ट्रीय वर्चुअल पुस्तकालय विभिन्न भाषाओं में प्रासंगिक अध्ययन सामग्री को डिजीटाइज करके डिजीटल संसाधन उपलब्ध करवाएगा, जिसका सभी स्तर पर आदान-प्रदान किया जाएगा।। पौराणिक ज्ञान पद्धति में आधुनिक वैज्ञानिक विधियों का प्रयोग कर हम दोनों प्रकार की पद्धतियों को सर्वोत्तम चीजों को अपना सकते हैं।। जानी मानी विदेशी होटलों के भारत में आगमन से रसोई संबंधी संस्थाएं भी प्रचलित हो रही हैं।। मेरी ओर से सर्वोत्तम सद्भावना के आश्वासन के साथ’’।। मेरे उच्चतम आदर के आश्वासन सहित।। मेरे सर्वोत्तम सहयोग केआश्वासन के साथ।। हमारी जनसंख्या का बड़ा हिस्सा कामकाजी आयु समूह का है।। 7वीं सदी के प्रारम्भ होने पर, हर्षवर्धन (606-647 इसवी में) ने अपने भाई राज्यवर्धन की मृत्यु होने पर थानेश्वर व कन्नौज की राजगद्दी संभाली।। कृषि तथा रसायन प्रौद्योगिकी संस्थानों के सम्वेत प्रयासों के द्वारा हम उर्वरकों के उपयोग में बेहतर दक्षता प्राप्त करने में सफल होंगे।। सांस्कृतिक सौहार्द के लिए, प्रथम टैगोर पुरस्कार प्रदान करके हम स्वर्गीय पंडित रविशंकर को, सांस्कृतिक सौहार्द के लिए उनके महान योगदान को श्रद्धांजलि दे रहे हैं।। जनसंख्या का जितना घनत्व बंगलुरु में है, अगर उतना घनत्व भारत की पूरी जनसंख्या का हो तो आधे कर्नाटक में सारे भारतीय रह सकते हैं।। भारतीय अर्थव्यवस्था के विकास से प्रत्यक्ष कर तथा करदाताओं की संख्या बहुत अधिक बढ़ी है,जिससे कर विवाद निवारण प्रणाली पर दबाव पड़ा है।। हृदय,हस्त और मस्तक के पूर्ण प्रशिक्षण,जो नई तालीम है, के द्वारा एक समर्थ भारत का निर्माण करने का दायित्व आपका है।। इराक में लोकतंत्र की स्थापना के बाद दोनों देशों के बीच संबंध नए चरण में प्रवेश कर रहे हैं।। पहले अलकायदा और अब आई एस के उभरने से ये सीमाएं टूट चुकी हैं।। भारतीय उड्डयन क्षेत्र की उभरती हुई मांग से उड्डयन समारोह 2016 विश्व भर के सभी भागीदारों और उड्डयन प्रतिभगियों को अनूठे अवसर प्रदान कर रहा है।। कालेधन के अधिनियमन (अघोषित विदेशी आय तथा परिसंपत्तियां) तथा करारोपण अधिनियम, 2015 के साथ इस समस्या के समाधान के लिए एक कड़ी कानूनी प्रक्रिया तैयार की गई है।। 9वीं इसवी के समाप्त होते-होते भारत का मध्यकालीन इतिहास पाला, सेना, प्रतिहार और राष्ट्र कूट आदि - आदि उत्थान से प्रारंभ होता है।। हम दोनों देशों के बीच राजनयिक संबंधों की स्थापना करके, हमारे द्विपक्षीय संबंध परस्पर हित के विभिन्न क्षेत्रों में विस्तृत हुए हैं।। गोवा को छोड़कर, आज प्रत्येक राज्य में एक केन्द्रीय विश्वविद्यालय है।। मौजूदा आर्थिक केंद्रों के इष्टतम सीमा तक पहुंचने से कारोबार गतिविधियां नए गंतव्यों की ओर जाने के लिए बाध्य हो गई हैं।। मुझे खुशी हो रही है कि समेकित जल संसाधन प्रबंधन, जलवायु परिवर्तन तथा घरेलू और औद्योगिक जल प्रबंधन के क्षेत्र में विशेषज्ञता रखने वाले ऊर्जा तथा संसाधन संस्थान ने इस समारोह के आयोजन की अगुवाई की।। मेरी सरकार ‘हुनरमंद भारत’ के लक्ष्य से ‘‘नेशनल मल्टी स्किल मिशन’’ भी शुरू करेगी।। भारतीय अर्थव्यवस्था की प्रगति तथा जनता के पास व्यय योग्य आमदनी बढ़ने से हम आने वाले वर्षों में पर्यटकों की आमद में सकारात्मक रुझान की अपेक्षा कर सकते हैं।। 2013-14 में विकास दर के 49 प्रतिशत के अनुमान के साथ, मुझे विश्वास है कि हमने बदलाव के बिंदु को पार कर लिया है और कुछ ही वर्षों में हम 7-8 प्रतिशत की उच्च विकास गति दोबारा हासिल कर लेंगे।। प्रशासन और विधान की बढ़ती जटिलता के कारण विधायकों को कानून पारित करने से पूर्व पर्याप्त विचार-विमर्श और जांच पड़ताल कर लेनी चाहिए।। प्रशासन तथा कानून निर्माण की भारी जटिलताओं के चलते, विधायकों को कानून पारित करने से पहले समुचित परिचर्चा तथा जांच सुनिश्चित करनी चाहिए।। प्रशासन की बढ़ती जटिलताओं के मद्देनजर कानून पारित करने से पूर्व पर्याप्त परिचर्चा तथा जांच होनी चाहिए।। एनिमेशन तथा सिमुलेशन की नवीनतम डिजिटल तकनीकों की सहायता से राष्ट्रपति भवन द्वारा कहानीवक्ता के तौर पर भारत की नवीन राजधानी की योजना तथा उसका निर्माण, इसके स्वतंत्रता पूर्व भारत में औपनिवेशिक ताकत के प्रतीक से समावेशी, जीवंत तथा महत्वाकांक्षी, स्वतंत्र लोकतांत्रिक भारत के प्रतीक के रूप में रूपांतरण की गाथा का बयान की जाएगी।। विश्वविद्यालय अनुदान आयोग की सहायता से यह इस क्षेत्र की समृद्ध विविधता के प्रदर्शन के लिए पूर्वोत्तर विविधता केन्द्र की स्थापना कर रहा है।। मैं इस उम्मीद के साथ अपनी बात समाप्त करता हूं कि राष्ट्रीय सुरक्षा पुरस्कार (खान) हमारे खान कामगारों के व्यावसायिक स्वास्थ्य और सुरक्षा मानकों में सुधार के लिए उत्प्रेरक बनेंगे।। पंचायती राज संस्थाओं में महिलाओं के लिए 33 प्रतिशत आरक्षण को दृढ़ कार्रवाई के द्वारा अमल में लाने से महिला प्रतिनिधित्व में तीव्र वृद्धि हुई है।। 20 जुलाई, 2004 से प्रभावी राज्य सभा के प्रक्रिया और कार्य संचालन विषयक नियमों में आचार समिति संबंधी नियमों को शामिल किए जाने से, समिति का अधिदेश का दायरा व्यापक हो गया है जिसमें सदस्यों के नैतिक आचरण पर नज़र रखना, सदस्यों के लिए एक आचार संहिता तैयार करना और राज्य सभा को प्रतिवेदन प्रस्तुत करने के माध्यम से इस संहिता में समय-समय पर संशोधनों अथवा कुछ बातें जोड़ने का सुझाव देना; सदस्यों द्वारा कथित रूप से आचार संहिता का कथित उल्लंघन संबंधी मामलों और साथ ही सदस्य पर किसी अन्य नैतिक दुराचार के संबंधी में लगाए गए आरोप से भी संबंधित मामलों की जांच करना; और सदस्यों को नैतिक स्तर से संबंधित प्रश्नों के संबंध में स्वतः ही अथवा विशेष अनुरोध प्राप्त करने पर सलाह देना शामिल है।। इसकी जनसंख्या बढ़ने तथा विषयों के विस्तार से ऐसे तत्त्वों का लगातार हस्तक्षेप बढ़ गया है जो स्वतंत्रता और सहजता की भावना के विरुद्ध हैं।। उन्हें प्रज्ञा, अनुभव और नैतिक प्राधिकार के द्वारा केंद्र और राज्यों के बीच समन्वयपूर्ण संबंध स्थापित करने में मदद करनी चाहिए।। उन्हें प्रज्ञा,अनुभव और नैतिक प्राधिकार के द्वारा केंद्र और राज्यों के बीच समन्वयपूर्ण संबंध स्थापित करने में मदद करनी चाहिए।। हमारी सरकार ने‘हर हाथ को हुनर’के उद्देश्य से,युवकों को कुशल बनाने और उन्हें बेहतर रोजगार के योग्य बनाने के लिए अनेक कदम उठाए हैं।। मेरी सरकार ‘‘हर हाथ को हुनर’’ के उद्देश्य से औपचारिक शिक्षा और कौशल विकास के बीच की बाधाओं को दूर करने का प्रयास करेगी और ऐसी व्यवस्था बनाएगी जिसमें व्यावसायिक योग्यताओं को अकादमिक समानता दी जाएगी।। किसान क्रेडिट कार्डों को डिजिटल बनाने के उद्देश्य से,मौजूदा कार्डों के अलावा तीन करोड़ कार्डों को,जल्द ही रूपे डेबिट कार्डों में बदला जाएगा।। युवकों को अंतरराष्ट्रीय स्तर का प्रशिक्षण प्रदान करने के उद्देश्य से50 भारतीय अंतरराष्ट्रीय कौशल केंद्रों का राष्ट्रव्यापी नेटवर्क स्थापित किया जा रहा है।। आर्थिक सुधार आरंभ करने के बाद की सरकारों ने घरेलू और विदेशी कंपनियों के साथ स्पर्द्धा के लिए सार्वजनिक क्षेत्र उद्यमों में बढ़े हुए विदेशी निवेश सहित एक अधिक मुक्त अर्थव्यवस्था की और प्रणालीगत बदलाव आरंभ किया है।। स्वामी नित्यानंद महाराज के निधन से न केवल मिशन ने अपने संस्थापक को खो दिया है,न केवल संगठन के सदस्यों ने एक महान शिक्षक और मार्गदर्शक खोया है बल्कि उन्होंने भी एक महत्वपूर्ण मित्र खो दिया है।। हमारी जनसंख्या के मुख्यतः युवा वर्ग के 550 मिलीयन भारतीय 25 वर्ष से कम आयु के हैं- सामाजिक आर्थिक विकास के लिए राज्य हस्तक्षेपों और सुविधाओं के संबंध में धैर्य क्षीण हो रहा है।। दूरदर्शिता और उत्साह जैसे गुणों के साथ हमारे शिक्षक उनके क्षेत्र में अद्यतन विकासों के प्रति सचेत रहते हैं।। हाल में प्राकृतिक गैस और खनिजों की खोज से भविष्य उज्ज्वल है।। जनता की बढ़ती हुई उम्मीदों के मद्देनज़र सिविल सेवकों को भारी दायित्व उठाने होंगे। महामहिमगण,इन्हीं शब्दों के साथ,मैं एक बार फिर से आप सभी का स्वागत करता हूं तथा द्वितीय भारत-प्रशांत द्वीप समूह सहयोग मंच शिखर सम्मेलन की सफलता के लिए शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं इस आशा के साथ अपनी बात समाप्त करता हूं कि चर्च और सेमिनारी समाज के लिए अपने कल्याणकारी कार्य जारी रखेंगे।। इन्हीं कुछ शब्दों के साथ,मैं अपनी बात समाप्त करता हूं। मैं एक बार पुनः उन सभी को अपनी बधाई देता हूं जिन्हें आज‘वयोश्रेष्ठ सम्मान’से पुरस्कृत किया गया है।। इन्हीं चंद शब्दों के साथ मैं आप सभी को धन्यवाद देता हूं तथा एशिया-अफ्रीका कृषि फॉरम, नई दिल्ली की सफलता की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ,मैं अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ मैं एक बार फिर से बंगाल इंजीनियरी एवं विज्ञान विश्वविद्यालय को प्रथम भारतीय इंजीनियरी विज्ञान एवं प्रौद्योगिकी संस्थान में बदले जाने के इस यादगार मौके पर सभी संकाय सदस्यों और विद्यार्थियों को हार्दिक शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं सम्मेलन और इसकी परिचर्चाओं को अपनी शुभकामनाएं देता हूं।। इन्हीं कुछ शब्दों के साथ, मैं विश्व पारसी सम्मेलन की सफलता के लिए शुभकामनाएं देता हूं।। इन नीतिगत पहलों के द्वारा विनिर्माण और सेवा उद्योग के उद्यमिता कौशल तथा व्यवसाय पहल को अर्थव्यवस्था के सतत और सुदृढ़ विकास के लिए संयोजित करना होगा।। विभाग-संबंधित संसदीय स्थायी समितियों के गठन के साथ ही निरपवाद रूप से अध्यादेशों को प्रतिस्थापित करने वाले विधेयकों, अनपकारी प्रकृति के विधेयकों एवं धन विधेयकों को छोड़कर सभी विधेयक जांच एवं तीन महीने के भीतर प्रतिवेदन प्रस्तुत किए जाने के लिए इन समितियों को सौंप दिए जाते हैं।। इन्हीं शब्दों के साथ, विशिष्ट अतिथिगण, देवियो और सज्जनो, आइए हम सब मिलकरः। विद्वान अध्यक्ष जी, इन्हीं शब्दों के साथ, आज मुझे प्रदान किए गए सम्मान के लिए इस प्रतिष्ठित विश्वविद्यालय के विद्यार्थियों तथा संकाय सदस्यों का मैं धन्यवाद करता हूं।। इन्हीं शब्दों के साथ, महामहिमगण,देवियो और सज्जनो, आइए हम सब मिलकर;। महामहिम, इन्हीं शब्दों के साथ, मैं एक बार पुनः आपका और मादाम सलमा कीक्वेटे का स्वागत करता हूं और भारत की अत्यंत सफल यात्रा के लिए शुभकामनाएं देता हूं।। महामहिम, इन्हीं शब्दों के साथ मैं एक बार फिर से भारत में और राष्ट्रपति भवन में आपका स्वागत करता हूं तथा आपको और आपके विशिष्ट शिष्टमंडल को आरामदायक प्रवास तथा अत्यंत सफल यात्रा के लिए शुभकामनाएं देता हूं।। महामहिम,इन्हीं शब्दों के साथ,मैं इस अवसर पर आपकी भारत यात्रा के अपने निमंत्रण को अत्यंत हार्दिकतापूर्वक दोहराता हूं।। महामहिम, इन्हीं शब्दों के साथ मैं एक बार फिर आपके सम्मानजनक आतिथ्य सत्कार के लिए धन्यवाद देता हूं तथा फिलस्तीन की शांति और प्रगति के आपके प्रयासों की सफलता की कामना करता हूं।। महामहिम, इन्हीं शब्दों के साथ,मैं आपकी और मादाम इजौरा न्यूसी की भारत की आनंदपूर्ण और सफल यात्रा की कामना करता हूं।। इन्हीं शब्दों के साथ,मैं अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ, मैं अपनी बात समाप्त करता हूं। मैं एक बार पुनः इस महत्वपूर्ण सेमिनार के आयोजन के लिए राजघाट समाधि समिति की सराहना करता हूं।। इन्हीं शब्दों के साथ, मैं अपनी बात समाप्त करता हूं। मैं एक बार पुनः स्नातक बनने जा रहे विद्यार्थियों को बधाई देता हूं और उनके सुनहरे भविष्य की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं अंत में एक बार पुनः इस मंच पर आमंत्रित करने के लिए संघ लोक सेवा आयोग को धन्यवाद अदेता हूं।। अंत में इन्हीं शब्दों के साथ, मैं पुनः आप सभी को शुभकामनाएं देता हूं।। इन शब्दों के साथ,समापन करते हुए मैं आप सभी को मुझे इस समारोह में आमंत्रित करने के लिए धन्यवाद देता हूं।। अंत में इन्हीं शब्दों के साथ मैं, आपके राज्य में आमंत्रित किए जाने पर धन्यवाद करता हूं।। इन्हीं शब्दों के साथ मैं अपनी बात समाप्त करता हूं। मैं हमारे देश के मेधावी नर्सिंग पेशेवरों जिन्हें आज सम्मानित किया गया है,को अपने जीवनवृत्त में सफलता की शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं अपनी बात समाप्त करता हूं। मैं इस समारोह के सफल संचालन के लिए आपको शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ मैं अपनी बात समाप्त करता हूं। मैं आपके सभी प्रयासों में सफलता की कामना करता हूं।। इन्हीं शब्दों के साथ मैं अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ, मैं अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ,मैं अपनी बात समाप्त करता हूं।। मैं, इन्हीं शब्दों के साथ अपनी बात समाप्त करता हूं।। इन शब्दों के साथ मैं कोटे डी आइवरी की जनता को भारत की जनता की ओर से उनकी सतत शांति समृद्धि और सशक्तता के लिए शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं 33वें भारत अंतरराष्ट्रीय व्यापार मेले के शुभारंभ की घोषणा करता हूं।। इन शब्दों के साथ, मैं 35वें भारतीय अंतरराष्ट्रीय व्यापार मेले को आरंभ करने की घोषणा करता हूं।। इन्हीं शब्दों के साथ,मैं71वें स्टाफ पाठ्यक्रम के सभी स्टाफ सदस्यों और विद्यार्थी अधिकारियों को अपनी शुभकामनाएं देता हूं तथा उनके सभी प्रयासों के निरंतर सफल होने की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं आपको तथा आपकी ओर से पापुआ न्यू गिनिया की जनता को इस स्मरणीय यात्रा के लिए अपना हार्दिक धन्यवाद देता हूं।। इन शब्दों के साथ मैं माननीय अध्यक्ष आपको और नामिबिया के माननीय सदस्यों को भारत आने का हार्दिक निमंत्रण देता हूं।। इन शब्दों के साथ,मैं भारतीय आर्थिक संघ के 98वें सत्र के शुभारंभ की औपचारिक घोषणा करता हूं तथा इसकी परिचर्चाओं के सफल होने की कामना करता हूं।। इन्हीं शब्दों के साथ,मैं अब अपनी बात समाप्त करता हूं।। इन्हीं शब्दों के साथ,मैं एक बार फिर माननीय स्वास्थ्य मंत्री, श्री जेपीनड्डा, डॉ एसपी अग्रवाल तथा भारतीय रेड क्रॉस सोसायटी और सेंट जॉन एम्बुलेंस (भारत) के सभी पदाधिकारियों को बधाई देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार फिर से माननीय डॉ वीरप्पा मोइली को बधाई देता हूं।। इन शब्दों के साथ, मैं एक बार दोबारा निमहैन्स को मुबारकबाद देता हूं और राष्ट्र को यह राष्ट्रीय महत्त्व का संस्थान समर्पित करता हूं।। इन्हीं शब्दों के साथ मैं एक बार पुनः एडल्ट लीडरों सहित भारत स्काउट और गाइड के पुरस्कार विजेताओं को बधाई देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार फिर से इस सम्मेलन के आयोजकों को बधाई देता हूं और इसकी सफलता के लिए अपनी शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः नारी शक्ति पुरस्कार प्राप्तकर्ताओं तथा इस समारोह के आयोजन के लिए महिला और बाल विकास मंत्रालय को बधाई देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार फिर से केंद्रीय स्वास्थ्य मंत्रालय, राज्य सरकारों तथा उन सभी को फिर से बधाई देता हूं जिन्होंने भारत को पोलियो मुक्त करने में योगदान दिया है।। इन्हीं शब्दों के साथ मैं एक बार फिर से स्त्री शक्ति और नारी शक्ति पुरस्कार विजेताओं को बधाई देता हूं।। इन शब्दों के साथ,मैं एक बार दोबारा मुझे यह मानद प्रदान करने के लिए अल-कुड्स विश्वविद्यालय को धन्यवाद देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः आपका स्वागत करता हूं और भारत में आपके सुखद प्रवास की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं एक बार फिर से महामहिम आपका और मादाम शेरोन जोंस्टन तथा आपके विशिष्ट शिष्टमंडल का स्वागत करता हूं तथा भारत में आपके आरामदेह तथा सुखद प्रवास की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः महामहिम का स्वागत करता हूं तथा आपको और आपके शिष्टमंडल को भारत की सफल यात्रा की शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः भारत-अफ्रीका संबंधों तथा तृतीय भारत-अफ्रीका मंच शिखर सम्मेलन की सफलता की इस उत्सवमयी संध्या में आपका स्वागत करता हूं।। इन शब्दों के साथ,मैं इस स्वागत के लिए भारत के राजदूत को और आप सभी को धन्यवाद देता हूं।। इन्हीं शब्दों के साथ,एक बार पुनः मैं आप सभी को आपके आदर सत्कार तथा राष्ट्रपति महामा की गरिमामयी उपस्थिति और एकजुटता के लिए धन्यवाद करता हूं।। इन्हीं शब्दों के साथ, मैं एक बार फिर से आपको धन्यवाद देता हूं तथा आपके भावी प्रयासों में सफलता की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः आपको धन्यवाद देता हूं और आपके सहयोग के सफल होने की कामना करता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः इस विशिष्ट सभा को संबोधित करने का अवसर प्रदान करने के लिए आपको धन्यवाद देता हूं।। इन्हीं शब्दों के साथ, मैं एक बार पुनः आपके शानदार आतिथ्य के लिए धन्यवाद देता हूं।। इन्हीं शब्दों के साथ मैं एक बार पुनः आपके शानदार आतिथ्य सरकार के लिए धन्यवाद देता हूं।। महामहिम,इन शब्दों के साथ महामहिम मैं मैडम विदेश मंत्री और महानिदेशक डॉ दोरोथी गोर्डन को इस इस सेंटर के बहुत ही संतोषजनक यात्रा का आयोजन करने के लिए धन्यवाद देता हूं।। इन्हीं शब्दों के साथ,मैं सम्मेलन की अत्यंत सफलता की कामना करता हूं।। इन्हीं शब्दों के साथ,मैं आप सभी को और आपके माध्यम से बेलारूस की मित्र जनता को भारत की जनता की हार्दिक बधाई तथा आपकी निरंतर खुशहाली और प्रगति और समृद्धि के लिए शुभकामनाएं देता हूं।। इन्हीं शब्दों के साथ, मैं आपको और आपके माध्यम से हेलसिंकी की मैत्रीपूर्ण जनता को उनकी निरंतर प्रगति और समृद्धि के लिए भारतवासियों की ओर से हार्दिक शुभकामनाएं देता हूं।। इन शब्दों के साथ मैं एक बार फिर भारत-चीन व्यवसाय मंच का भारत और चीन के बीच आर्थिक संबंध मजबूत करने में योगदान देने के लिए धन्यवाद करता हूं।। इन्हीं शब्दों के साथ, देवियो और सज्जनो,आइए हम सब मिलकरः। देवियो और सज्जनो, इन्हीं शब्दों के साथ,आइए मिलकर भारत और फ्रांस की जनता के बीच सदैव विद्यमान मैत्री तथा हमारे दोनों के बीच निरंतर घनिष्ठ सहयोग की कामना करें।। इन शब्दों के साथ, देवियो और सज्जनो,मैं दोहराना चाहूंगा कि मैं भारत और जॉर्डन के बीच संबंधों की सुदृढ़ता के प्रति आपके आशावादी दृष्टिकोण और प्रतिबद्धता से बेहद प्रसन्न हूं।। देवियो और सज्जनो, इन्हीं शब्दों के साथ, आइए हम सब मिलकरः। माननीय राष्ट्रपति जी इन्हीं शब्दों के साथ मैं एक बार फिर आपका तथा आपके शिष्टमंडल के विशिष्ट सदस्यों का स्वागत करता हूं तथा आपकी बहुत उपयोगी और आनंददायक यात्रा की कामना करता हूं।। राष्ट्रपति महोदय, मैं इन्हीं शब्दों के साथ एक बार पुनः आपका धन्यवाद करता हूं।। राष्ट्रपति महोदय,इन्हीं शब्दों के साथ, मैं आपका और आपके महत्त्वपूर्ण शिष्टमंडल को भारत की अत्यंत सफल यात्रा के लिए शुभकामनाएं देता हूं।। महामहिम, इन्हीं शब्दों के साथ, हम सब मिलकर :। महामहिम,इन शब्दों के साथ इस यात्रा के लिए व्यापक प्रबंध करने और शानदार राजभोज आयोजित करने के लिए आपका और आपकी सरकार का धन्यवाद करता हूं।। इन्हीं शब्दों के साथ, महामहिमगण,मैं एक बार पुनः आपके गरिमापूर्ण आतिथ्य के लिए आपका धन्यवाद करता हूं तथा आपको अपनी सुविधानुसार भारत की यात्रा करने के लिए आमंत्रित करता हूं।। अक्तूबर 2000में भारत-रूस सामरिक साझीदारी घोषणा पर हस्ताक्षर से, भारत ने संभवतः किसी भी बाहरी देश के साथ सबसे घनिष्ठ संस्थागत संबंध स्थापित किए।। जल संसाधनों में बदलाव न होने के कारण भविष्य में जल के आबंटन संबंधी इस

### Preprocessing data

In [2]:
data = open('total_data.txt', 'r', encoding='utf-8').read().lstrip('\ufeff')

In [3]:
data[:100]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि की।और पृथ्वी बेडौल और सुनसान पड़ी थी; और गहरे जल के ऊपर'

#### Removing punctuations and wierd text

In [4]:
import regex as re

# Step 1: Remove ALL Unicode punctuation (\p{P}) and symbols (\p{S})
cleaned_text = re.sub(r'[\p{P}\p{S}]', '', data)

# Step 2: Explicitly remove all Devanagari Digits using their Unicode range
# Devanagari digits range from U+0966 (०) to U+096F (९)
cleaned_text = re.sub(r'[\u0966-\u096F]', '', cleaned_text)

# Step 3: Keep only Devanagari characters (now only letters as digits were removed in Step 2),
# English Digits, and Whitespace.
# Note: \p{Script=Devanagari} here will effectively match Devanagari letters after Step 2.
pattern_final_filter = r'[^\p{Script=Devanagari}0-9\s]'
cleaned_text = re.sub(pattern_final_filter, '', cleaned_text)

# Normalize whitespace (collapse multiple spaces into one) and strip leading/trailing spaces
cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()

# Add space between Devanagari character (which should now be only letters) and an English digit, and vice-versa
# We use \p{Script=Devanagari} here, as by this stage it refers only to letters.
cleaned_text = re.sub(r'(\p{Script=Devanagari})(\d)', r'\1 \2', cleaned_text)
cleaned_text = re.sub(r'(\d)(\p{Script=Devanagari})', r'\1 \2', cleaned_text)

# Final whitespace normalization after adding spaces
cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()

In [5]:
cleaned_text[:1000]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि कीऔर पृथ्वी बेडौल और सुनसान पड़ी थी और गहरे जल के ऊपर अन्धियारा था तथा परमेश्वर का आत्मा जल के ऊपर मण्डलाता थातब परमेश्वर ने कहा उजियाला हो तो उजियाला हो गयाऔर परमेश्वर ने उजियाले को देखा कि अच्छा है और परमेश्वर ने उजियाले को अन्धियारे से अलग कियाऔर परमेश्वर ने उजियाले को दिन और अन्धियारे को रात कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार पहिला दिन हो गयाफिर परमेश्वर ने कहा जल के बीच एक ऐसा अन्तर हो कि जल दो भाग हो जाएतब परमेश्वर ने एक अन्तर करके उसके नीचे के जल और उसके ऊपर के जल को अलग अलग किया और वैसा ही हो गयाऔर परमेश्वर ने उस अन्तर को आकाश कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार दूसरा दिन हो गयाफिर परमेश्वर ने कहा आकाश के नीचे का जल एक स्थान में इकट्ठा हो जाए और सूखी भूमि दिखाई दे और वैसा ही हो गयाऔर परमेश्वर ने सूखी भूमि को पृथ्वी कहा तथा जो जल इकट्ठा हुआ उसको उसने समुद्र कहा और परमेश्वर ने देखा कि अच्छा हैफिर परमेश्वर ने कहा पृथ्वी से हरी घास तथा बीज वाले छोटे छोटे पेड़ और फलदाई वृक्ष भी जिनके बीज उन्ही में एक एक की जाति के अनुसार होते हैं प'

In [6]:
";" in cleaned_text

False

In [7]:
len(cleaned_text.split(" "))

79239041

In [8]:
with open("cleaned_data.txt", 'w') as text_file:
  text_file.write(cleaned_text)

#### Breaking up numbers

In [3]:
cleaned_text = open('cleaned_data.txt', 'r').read()

In [9]:
cleaned_text[:1000]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि कीऔर पृथ्वी बेडौल और सुनसान पड़ी थी और गहरे जल के ऊपर अन्धियारा था तथा परमेश्वर का आत्मा जल के ऊपर मण्डलाता थातब परमेश्वर ने कहा उजियाला हो तो उजियाला हो गयाऔर परमेश्वर ने उजियाले को देखा कि अच्छा है और परमेश्वर ने उजियाले को अन्धियारे से अलग कियाऔर परमेश्वर ने उजियाले को दिन और अन्धियारे को रात कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार पहिला दिन हो गयाफिर परमेश्वर ने कहा जल के बीच एक ऐसा अन्तर हो कि जल दो भाग हो जाएतब परमेश्वर ने एक अन्तर करके उसके नीचे के जल और उसके ऊपर के जल को अलग अलग किया और वैसा ही हो गयाऔर परमेश्वर ने उस अन्तर को आकाश कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार दूसरा दिन हो गयाफिर परमेश्वर ने कहा आकाश के नीचे का जल एक स्थान में इकट्ठा हो जाए और सूखी भूमि दिखाई दे और वैसा ही हो गयाऔर परमेश्वर ने सूखी भूमि को पृथ्वी कहा तथा जो जल इकट्ठा हुआ उसको उसने समुद्र कहा और परमेश्वर ने देखा कि अच्छा हैफिर परमेश्वर ने कहा पृथ्वी से हरी घास तथा बीज वाले छोटे छोटे पेड़ और फलदाई वृक्ष भी जिनके बीज उन्ही में एक एक की जाति के अनुसार होते हैं प'

In [10]:
"#" in cleaned_text

False

In [11]:
import regex as re

mixed_alphanumeric_pattern = r'\b(?:\p{Script=Devanagari}+[0-9]+|[0-9]+\p{Script=Devanagari}+)\b'

mixed_matches = re.findall(mixed_alphanumeric_pattern, cleaned_text)

if mixed_matches:
    print(f"Found {len(mixed_matches)} instances of mixed words and numbers.")
    print("First 10 examples:")
    for i, match_ in enumerate(mixed_matches[:10]):
        print(f"- {match_}")
else:
    print("No mixed words and numbers found in the text.")

No mixed words and numbers found in the text.

In [ ]:
pattern = r'(\d)(?=\d)'
sep = r'\1# '

In [ ]:
import regex as re
cleaned_text_1 = re.sub(pattern, sep, cleaned_text)

In [ ]:
cleaned_text_1[:1000]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि कीऔर पृथ्वी बेडौल और सुनसान पड़ी थी और गहरे जल के ऊपर अन्धियारा था तथा परमेश्वर का आत्मा जल के ऊपर मण्डलाता थातब परमेश्वर ने कहा उजियाला हो तो उजियाला हो गयाऔर परमेश्वर ने उजियाले को देखा कि अच्छा है और परमेश्वर ने उजियाले को अन्धियारे से अलग कियाऔर परमेश्वर ने उजियाले को दिन और अन्धियारे को रात कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार पहिला दिन हो गयाफिर परमेश्वर ने कहा जल के बीच एक ऐसा अन्तर हो कि जल दो भाग हो जाएतब परमेश्वर ने एक अन्तर करके उसके नीचे के जल और उसके ऊपर के जल को अलग अलग किया और वैसा ही हो गयाऔर परमेश्वर ने उस अन्तर को आकाश कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार दूसरा दिन हो गयाफिर परमेश्वर ने कहा आकाश के नीचे का जल एक स्थान में इकट्ठा हो जाए और सूखी भूमि दिखाई दे और वैसा ही हो गयाऔर परमेश्वर ने सूखी भूमि को पृथ्वी कहा तथा जो जल इकट्ठा हुआ उसको उसने समुद्र कहा और परमेश्वर ने देखा कि अच्छा हैफिर परमेश्वर ने कहा पृथ्वी से हरी घास तथा बीज वाले छोटे छोटे पेड़ और फलदाई वृक्ष भी जिनके बीज उन्ही में एक एक की जाति के अनुसार होते हैं प'

In [ ]:
print("Number of token:", len(cleaned_text_1.split(" ")))

Number of token: 82035716

In [ ]:
with open('cleaned_data.txt', 'w') as text_file:
  text_file.write(cleaned_text_1)

#### Unique words

In [ ]:
cleaned_text = open("cleaned_data.txt", "r").read()

In [ ]:
import pandas as pd

In [ ]:
interested_words = pd.DataFrame(pd.DataFrame(cleaned_text.split(" ")).value_counts())[pd.DataFrame(pd.DataFrame(cleaned_text.split(" ")).value_counts())['count'] >= 0]

In [ ]:
'के' in interested_words.index

True

In [ ]:
interested_words.reset_index(inplace=True)

In [ ]:
interested_words[0].value_counts().sort_values(ascending=False)

0
की             1
अर्थानुवाद     1
के             1
ऑटोनेटिक्स     1
ऑटोनॉामस       1
              ..
ॠचाओं          1
ॠणअग्रिम       1
ॠणपूर्व        1
ॠणस्थगन        1
ॐप्रजाभ्यां    1
Name: count, Length: 850803, dtype: int64

In [ ]:
interested_words.describe()

              count
count  8.508030e+05
mean   9.642152e+01
std    7.166551e+03
min    1.000000e+00
25%    1.000000e+00
50%    2.000000e+00
75%    5.000000e+00
max    3.460205e+06

In [ ]:
interested_words[interested_words['count'] < 2]['count'].sum()

np.int64(342599)

In [ ]:
unique_words = interested_words[interested_words['count'] >= 2].copy()

In [ ]:
unique_words.loc[len(unique_words)] = [r'<UNK>', 0]

In [ ]:
interested_words

                 0    count
0               के  3460205
1               है  2567639
2              में  2554180
3               की  1745880
4               और  1693280
...            ...      ...
850798      खसरेका        1
850799       ॲर्डर        1
850800  ॲलटर्नेटिव        1
850801         ॲाव        1
850802  अर्थानुवाद        1

[850803 rows x 2 columns]

In [ ]:
unique_words

                 0    count
0               के  3460205
1               है  2567639
2              में  2554180
3               की  1745880
4               और  1693280
...            ...      ...
508200  अर्थानुरणन        2
508201      ॠथियों        2
508202        ॠणों        2
508203  अर्थानुसार        2
508204       <UNK>        0

[508205 rows x 2 columns]

In [ ]:
unique_words.rename(columns={0: 'Word'}, inplace=True)

In [ ]:
unique_words

              Word    count
0               के  3460205
1               है  2567639
2              में  2554180
3               की  1745880
4               और  1693280
...            ...      ...
508200  अर्थानुरणन        2
508201      ॠथियों        2
508202        ॠणों        2
508203  अर्थानुसार        2
508204       <UNK>        0

[508205 rows x 2 columns]

In [ ]:
unique_words.to_csv("vocabulary.csv")

###### Older way of getting unique words for vocab

In [ ]:
import numpy as np
unique_words = {}
i = 0
for word in cleaned_text.split(" "):
  if word not in unique_words:
    unique_words[word] = i
    i+=1

In [ ]:
i

97256

In [ ]:
unique_words

{'आदि': 0,
 'में': 1,
 'परमेश्वर': 2,
 'ने': 3,
 'आकाश': 4,
 'और': 5,
 'पृथ्वी': 6,
 'की': 7,
 'सृष्टि': 8,
 'कीऔर': 9,
 'बेडौल': 10,
 'सुनसान': 11,
 'पड़ी': 12,
 'थी': 13,
 'गहरे': 14,
 'जल': 15,
 'के': 16,
 'ऊपर': 17,
 'अन्धियारा': 18,
 'था': 19,
 'तथा': 20,
 'का': 21,
 'आत्मा': 22,
 'मण्डलाता': 23,
 'थातब': 24,
 'कहा': 25,
 'उजियाला': 26,
 'हो': 27,
 'तो': 28,
 'गयाऔर': 29,
 'उजियाले': 30,
 'को': 31,
 'देखा': 32,
 'कि': 33,
 'अच्छा': 34,
 'है': 35,
 'अन्धियारे': 36,
 'से': 37,
 'अलग': 38,
 'कियाऔर': 39,
 'दिन': 40,
 'रात': 41,
 'सांझ': 42,
 'हुई': 43,
 'फिर': 44,
 'भोर': 45,
 'हुआ': 46,
 'इस': 47,
 'प्रकार': 48,
 'पहिला': 49,
 'गयाफिर': 50,
 'बीच': 51,
 'एक': 52,
 'ऐसा': 53,
 'अन्तर': 54,
 'दो': 55,
 'भाग': 56,
 'जाएतब': 57,
 'करके': 58,
 'उसके': 59,
 'नीचे': 60,
 'किया': 61,
 'वैसा': 62,
 'ही': 63,
 'उस': 64,
 'दूसरा': 65,
 'स्थान': 66,
 'इकट्ठा': 67,
 'जाए': 68,
 'सूखी': 69,
 'भूमि': 70,
 'दिखाई': 71,
 'दे': 72,
 'जो': 73,
 'उसको': 74,
 'उसने': 75,
 'समुद्र': 76,
 'हैफिर': 77,
 'हरी': 78,
 'घास': 79,
 'बीज': 80,
 'वाले': 81,
 'छोटे': 82,
 'पेड़': 83,
 'फलदाई': 84,
 'वृक्ष': 85,
 'भी': 86,
 'जिनके': 87,
 'उन्ही': 88,
 'जाति': 89,
 'अनुसार': 90,
 'होते': 91,
 'हैं': 92,
 'पर': 93,
 'उगें': 94,
 'गयातो': 95,
 'जिन': 96,
 'अपनी': 97,
 'होता': 98,
 'उगे': 99,
 'हैतथा': 100,
 'तीसरा': 101,
 'करने': 102,
 'लिये': 103,
 'ज्योतियां': 104,
 'हों': 105,
 'वे': 106,
 'चिन्हों': 107,
 'नियत': 108,
 'समयों': 109,
 'दिनों': 110,
 'वर्षों': 111,
 'कारण': 112,
 'होंऔर': 113,
 'प्रकाश': 114,
 'देने': 115,
 'वाली': 116,
 'ठहरें': 117,
 'गयातब': 118,
 'बड़ी': 119,
 'बनाईं': 120,
 'उन': 121,
 'ज्योति': 122,
 'प्रभुता': 123,
 'छोटी': 124,
 'बनाया': 125,
 'तारागण': 126,
 'बनायापरमेश्वर': 127,
 'इसलिये': 128,
 'रखा': 129,
 'देंतथा': 130,
 'करें': 131,
 'चौथा': 132,
 'जीवित': 133,
 'प्राणियों': 134,
 'बहुत': 135,
 'भर': 136,
 'पक्षी': 137,
 'उड़ेंइसलिये': 138,
 'बड़े': 139,
 'जलजन्तुओं': 140,
 'सब': 141,
 'चलते': 142,
 'फिरते': 143,
 'गया': 144,
 'उड़ने': 145,
 'पक्षियों': 146,
 'हैऔर': 147,
 'यह': 148,
 'कहके': 149,
 'उनको': 150,
 'आशीष': 151,
 'दी': 152,
 'फूलोफलो': 153,
 'जाओ': 154,
 'बढ़ेंतथा': 155,
 'पांचवां': 156,
 'प्राणी': 157,
 'अर्थात': 158,
 'घरेलू': 159,
 'पशु': 160,
 'रेंगने': 161,
 'जन्तु': 162,
 'वनपशु': 163,
 'उत्पन्न': 164,
 'गयासो': 165,
 'वन': 166,
 'पशुओं': 167,
 'जन्तुओं': 168,
 'हम': 169,
 'मनुष्य': 170,
 'अपने': 171,
 'स्वरूप': 172,
 'समानता': 173,
 'बनाएं': 174,
 'मछलियों': 175,
 'सारी': 176,
 'रेंगते': 177,
 'अधिकार': 178,
 'रखेंतब': 179,
 'नर': 180,
 'नारी': 181,
 'मनुष्यों': 182,
 'वश': 183,
 'कर': 184,
 'लो': 185,
 'जन्तुओ': 186,
 'रखोफिर': 187,
 'सुनो': 188,
 'जितने': 189,
 'वृक्षों': 190,
 'फल': 191,
 'मैं': 192,
 'तुम': 193,
 'दिए': 194,
 'तुम्हारे': 195,
 'भोजन': 196,
 'हैंऔर': 197,
 'जीवन': 198,
 'प्राण': 199,
 'खाने': 200,
 'हरे': 201,
 'कुछ': 202,
 'क्या': 203,
 'वह': 204,
 'छठवां': 205,
 'गयायों': 206,
 'उनकी': 207,
 'सेना': 208,
 'बनाना': 209,
 'समाप्त': 210,
 'अपना': 211,
 'काम': 212,
 'जिसे': 213,
 'करता': 214,
 'सातवें': 215,
 'किए': 216,
 'हुए': 217,
 'सारे': 218,
 'विश्राम': 219,
 'पवित्र': 220,
 'ठहराया': 221,
 'क्योंकि': 222,
 'रचना': 223,
 'लियाआकाश': 224,
 'उत्पत्ति': 225,
 'वृत्तान्त': 226,
 'जब': 227,
 'जिस': 228,
 'यहोवा': 229,
 'बनायातब': 230,
 'मैदान': 231,
 'कोई': 232,
 'पौधा': 233,
 'न': 234,
 'छोटा': 235,
 'उगा': 236,
 'नहीं': 237,
 'बरसाया': 238,
 'खेती': 239,
 'थातौभी': 240,
 'कोहरा': 241,
 'उठता': 242,
 'सिंच': 243,
 'जाती': 244,
 'थीऔर': 245,
 'आदम': 246,
 'मिट्टी': 247,
 'रचा': 248,
 'नथनों': 249,
 'श्वास': 250,
 'फूंक': 251,
 'दिया': 252,
 'जीवता': 253,
 'बन': 254,
 'पूर्व': 255,
 'ओर': 256,
 'अदन': 257,
 'देश': 258,
 'वाटिका': 259,
 'लगाई': 260,
 'वहां': 261,
 'रख': 262,
 'दियाऔर': 263,
 'भांति': 264,
 'देखने': 265,
 'मनोहर': 266,
 'अच्छे': 267,
 'उगाए': 268,
 'भले': 269,
 'या': 270,
 'बुरे': 271,
 'ज्ञान': 272,
 'लगायाऔर': 273,
 'सींचने': 274,
 'महानदी': 275,
 'निकली': 276,
 'आगे': 277,
 'बहकर': 278,
 'चार': 279,
 'धारा': 280,
 'गईपहिली': 281,
 'नाम': 282,
 'पीशोन': 283,
 'वही': 284,
 'हवीला': 285,
 'जहां': 286,
 'सोना': 287,
 'मिलता': 288,
 'घेरे': 289,
 'हैउस': 290,
 'चोखा': 291,
 'मोती': 292,
 'सुलैमानी': 293,
 'पत्थर': 294,
 'मिलते': 295,
 'दूसरी': 296,
 'नदी': 297,
 'गीहोन': 298,
 'कूश': 299,
 'तीसरी': 300,
 'हिद्देकेल': 301,
 'अश्शूर': 302,
 'बहती': 303,
 'चौथी': 304,
 'फरात': 305,
 'हैतब': 306,
 'ले': 307,
 'करे': 308,
 'उसकी': 309,
 'रक्षा': 310,
 'करेतब': 311,
 'आज्ञा': 312,
 'तू': 313,
 'बिना': 314,
 'खटके': 315,
 'खा': 316,
 'सकता': 317,
 'हैपर': 318,
 'उसका': 319,
 'कभी': 320,
 'खाना': 321,
 'खाए': 322,
 'उसी': 323,
 'अवश्य': 324,
 'मर': 325,
 'जाएगाफिर': 326,
 'अकेला': 327,
 'रहना': 328,
 'सहायक': 329,
 'बनाऊंगा': 330,
 'उससे': 331,
 'मेल': 332,
 'खाएऔर': 333,
 'बनैले': 334,
 'भाँति': 335,
 'रचकर': 336,
 'पास': 337,
 'आया': 338,
 'देखें': 339,
 'उनका': 340,
 'रखता': 341,
 'रखे': 342,
 'परन्तु': 343,
 'मिला': 344,
 'सकेतब': 345,
 'भारी': 346,
 'नीन्द': 347,
 'डाल': 348,
 'सो': 349,
 'तब': 350,
 'पसली': 351,
 'निकाल': 352,
 'सन्ती': 353,
 'मांस': 354,
 'निकाली': 355,
 'स्त्री': 356,
 'बना': 357,
 'आयाऔर': 358,
 'अब': 359,
 'मेरी': 360,
 'हड्डियों': 361,
 'हड्डी': 362,
 'मेरे': 363,
 'इसका': 364,
 'होगा': 365,
 'गई': 366,
 'हैइस': 367,
 'पुरूष': 368,
 'माता': 369,
 'पिता': 370,
 'छोड़कर': 371,
 'पत्नी': 372,
 'रहेगा': 373,
 'तन': 374,
 'बने': 375,
 'रहेंगेऔर': 376,
 'दोनो': 377,
 'नंगे': 378,
 'थे': 379,
 'लजाते': 380,
 'बनाए': 381,
 'सर्प': 382,
 'धूर्त': 383,
 'सच': 384,
 'बाटिका': 385,
 'किसी': 386,
 'खानास्त्री': 387,
 'सकते': 388,
 'हैंपर': 389,
 'विषय': 390,
 'छूना': 391,
 'जाओगेतब': 392,
 'निश्चय': 393,
 'मरोगेवरन': 394,
 'आप': 395,
 'जानता': 396,
 'खाओगे': 397,
 'तुम्हारी': 398,
 'आंखें': 399,
 'खुल': 400,
 'जाएंगी': 401,
 'पाकर': 402,
 'तुल्य': 403,
 'जाओगेसो': 404,
 'मनभाऊ': 405,
 'बुद्धि': 406,
 'चाहने': 407,
 'योग्य': 408,
 'तोड़कर': 409,
 'खाया': 410,
 'पति': 411,
 'खायातब': 412,
 'दोनों': 413,
 'आंखे': 414,
 'मालूम': 415,
 'उन्होंने': 416,
 'अंजीर': 417,
 'पत्ते': 418,
 'जोड़': 419,
 'लंगोट': 420,
 'लियेतब': 421,
 'ठंडे': 422,
 'समय': 423,
 'फिरता': 424,
 'शब्द': 425,
 'सुनाई': 426,
 'छिप': 427,
 'गएतब': 428,
 'पुकार': 429,
 'पूछा': 430,
 'कहां': 431,
 'हैउसने': 432,
 'तेरा': 433,
 'बारी': 434,
 'सुन': 435,
 'डर': 436,
 'नंगा': 437,
 'गयाउसने': 438,
 'किस': 439,
 'तुझे': 440,
 'चिताया': 441,
 'बर्जा': 442,
 'हैआदम': 443,
 'संग': 444,
 'रहने': 445,
 'मुझे': 446,
 'बहका': 447,
 'अधिक': 448,
 'शापित': 449,
 'पेट': 450,
 'बल': 451,
 'चला': 452,
 'करेगा': 453,
 'चाटता': 454,
 'रहेगाऔर': 455,
 'तेरे': 456,
 'वंश': 457,
 'इसके': 458,
 'बैर': 459,
 'करुंगा': 460,
 'सिर': 461,
 'कुचल': 462,
 'डालेगा': 463,
 'एड़ी': 464,
 'डसेगाफिर': 465,
 'तेरी': 466,
 'पीड़ा': 467,
 'गर्भवती': 468,
 'होने': 469,
 'दुख': 470,
 'बढ़ाऊंगा': 471,
 'पीड़ित': 472,
 'बालक': 473,
 'करेगी': 474,
 'लालसा': 475,
 'होगी': 476,
 'तुझ': 477,
 'करेगाऔर': 478,
 'बात': 479,
 'सुनी': 480,
 'उसे': 481,
 'उपज': 482,
 'साथ': 483,
 'कांटे': 484,
 'ऊंटकटारे': 485,
 'उगाएगी': 486,
 'खेत': 487,
 'खाएगा': 488,
 'माथे': 489,
 'पसीने': 490,
 'रोटी': 491,
 'अन्त': 492,
 'मिल': 493,
 'जाएगा': 494,
 'निकाला': 495,
 'जाएगाऔर': 496,
 'हव्वा': 497,
 'आदिमाता': 498,
 'हुईऔर': 499,
 'चमड़े': 500,
 'अंगरखे': 501,
 'पहिना': 502,
 'दिएफिर': 503,
 'समान': 504,
 'हाथ': 505,
 'बढ़ा': 506,
 'तोड़': 507,
 'सदा': 508,
 'रहेतब': 509,
 'थाइसलिये': 510,
 'मार्ग': 511,
 'पहरा': 512,
 'करुबों': 513,
 'चारों': 514,
 'घूमने': 515,
 'ज्वालामय': 516,
 'तलवार': 517,
 'नियुक्त': 518,
 'दियाजब': 519,
 'कैन': 520,
 'जन्म': 521,
 'सहायता': 522,
 'पाया': 523,
 'भाई': 524,
 'हाबिल': 525,
 'जन्मी': 526,
 'भेड़बकरियों': 527,
 'चरवाहा': 528,
 'वाला': 529,
 'किसान': 530,
 'बनाकुछ': 531,
 'पश्चात': 532,
 'भेंट': 533,
 'कई': 534,
 'पहिलौठे': 535,
 'बच्चे': 536,
 'चढ़ाने': 537,
 'चर्बी': 538,
 'चढ़ाई': 539,
 'ग्रहण': 540,
 'कियापरन्तु': 541,
 'अति': 542,
 'क्रोधित': 543,
 'मुंह': 544,
 'उदासी': 545,
 'छा': 546,
 'गईतब': 547,
 'क्यों': 548,
 'हैयदि': 549,
 'भला': 550,
 'जाएगी': 551,
 'यदि': 552,
 'पाप': 553,
 'द्वार': 554,
 'छिपा': 555,
 'रहता': 556,
 'करेगातब': 557,
 'चढ़': 558,
 'घात': 559,
 'कियातब': 560,
 'रखवाला': 561,
 'हूंउसने': 562,
 'लोहू': 563,
 'चिल्ला': 564,
 'दोहाई': 565,
 'रहा': 566,
 'हैइसलिये': 567,
 'जिसने': 568,
 'पीने': 569,
 'खोला': 570,
 'हैचाहे': 571,
 'तौभी': 572,
 'पूरी': 573,
 'मिलेगी': 574,
 'बहेतू': 575,
 'भगोड़ा': 576,
 'होगातब': 577,
 'मेरा': 578,
 'दण्ड': 579,
 'सहने': 580,
 'बाहर': 581,
 'हैदेख': 582,
 'आज': 583,
 'दृष्टि': 584,
 'आड़': 585,
 'मे': 586,
 'रहूंगा': 587,
 'पाएगा': 588,
 'करेगाइस': 589,
 'सात': 590,
 'गुणा': 591,
 'पलटा': 592,
 'लिया': 593,
 'चिन्ह': 594,
 'मार': 595,
 'डालेतब': 596,
 'सम्मुख': 597,
 'निकल': 598,
 'नोद': 599,
 'लगाजब': 600,
 'हनोक': 601,
 'नगर': 602,
 'बसाया': 603,
 'पुत्र': 604,
 'रखाऔर': 605,
 'ईराद': 606,
 'महूयाएल': 607,
 'मतूशाएल': 608,
 'लेमेक': 609,
 'स्त्रियां': 610,
 'ब्याह': 611,
 'ली': 612,
 'आदा': 613,
 'सिल्ला': 614,
 'याबाल': 615,
 'तम्बुओं': 616,
 'जानवरों': 617,
 'पालन': 618,
 'इन': 619,
 'रीतियों': 620,
 'उत्पादक': 621,
 'हुआऔर': 622,
 'यूबाल': 623,
 'वीणा': 624,
 'बांसुरी': 625,
 'बाजों': 626,
 'बजाने': 627,
 'रीति': 628,
 'तूबल्कैन': 629,
 'पीतल': 630,
 'लोहे': 631,
 'धार': 632,
 'हथियारों': 633,
 'गढ़ने': 634,
 'बहिन': 635,
 'नामा': 636,
 'पत्नियों': 637,
 'हे': 638,
 'कान': 639,
 'लगाओ': 640,
 'मैंने': 641,
 'चोट': 642,
 'लगाता': 643,
 'जवान': 644,
 'घायल': 645,
 'हैजब': 646,
 'सत्तर': 647,
 'कह': 648,
 'शेत': 649,
 'ठहरा': 650,
 'एनोश': 651,
 'लोग': 652,
 'प्रार्थना': 653,
 'लगेआदम': 654,
 'वंशावली': 655,
 'बनायाउसने': 656,
 'उन्हें': 657,
 'रखाजब': 658,
 'सौ': 659,
 'तीस': 660,
 'वर्ष': 661,
 'द्वारा': 662,
 'आठ': 663,
 'बेटे': 664,
 'बेटियां': 665,
 'हुईंऔर': 666,
 'कुल': 667,
 'अवस्था': 668,
 'नौ': 669,
 'तत्पश्चात': 670,
 'गयाजब': 671,
 'पांच': 672,
 'बारह': 673,
 'नब्बे': 674,
 'केनान': 675,
 'पन्द्रह': 676,
 'महललेल': 677,
 'चालीस': 678,
 'दस': 679,
 'पैंसठ': 680,
 'येरेद': 681,
 'पंचानवे': 682,
 'बासठ': 683,
 'मतूशेलह': 684,
 'तीन': 685,
 'तक': 686,
 'चलता': 687,
 'लोप': 688,
 'उठा': 689,
 'लियाजब': 690,
 'सत्तासी': 691,
 'बयासी': 692,
 'उनहत्तर': 693,
 'कहकर': 694,
 'नूह': 695,
 'शाप': 696,
 'लड़का': 697,
 'हमारे': 698,
 'कठिन': 699,
 'परिश्रम': 700,
 'करते': 701,
 'शान्ति': 702,
 'देगाऔर': 703,
 'सतहत्तर': 704,
 'शेम': 705,
 'हाम': 706,
 'येपेत': 707,
 'दियाफिर': 708,
 'बढ़ने': 709,
 'लगे': 710,
 'उनके': 711,
 'हुईतब': 712,
 'पुत्रों': 713,
 'पुत्रियों': 714,
 'सुन्दर': 715,
 'चाहा': 716,
 'लियाऔर': 717,
 'लों': 718,
 'विवाद': 719,
 'शरीर': 720,
 'आयु': 721,
 'बीस': 722,
 'होगीउन': 723,
 'दानव': 724,
 'रहते': 725,
 'गए': 726,
 'सन्तान': 727,
 'शूरवीर': 728,
 'जिनकी': 729,
 'कीर्ति': 730,
 'प्राचीन': 731,
 'काल': 732,
 'प्रचलित': 733,
 'बुराई': 734,
 'बढ़': 735,
 'मन': 736,
 'विचार': 737,
 'निरन्तर': 738,
 'बुरा': 739,
 'बनाने': 740,
 'पछताया': 741,
 'खेदित': 742,
 'हुआतब': 743,
 'सोचा': 744,
 'जिसकी': 745,
 'मिटा': 746,
 'दूंगा': 747,
 'पछताता': 748,
 'हूंपरन्तु': 749,
 'अनुग्रह': 750,
 'बनी': 751,
 'रहीनूह': 752,
 'धर्मी': 753,
 'लोगों': 754,
 'खरा': 755,
 'रहाऔर': 756,
 'हुएउस': 757,
 'बिगड़': 758,
 'उपद्रव': 759,
 'बिगड़ी': 760,
 'चाल': 761,
 'चलन': 762,
 'बिगाड़': 763,
 'थीतब': 764,
 'प्रश्न': 765,
 'साम्हने': 766,
 'आ': 767,
 'समेत': 768,
 'नाश': 769,
 'डालूंगाइसलिये': 770,
 'गोपेर': 771,
 'लकड़ी': 772,
 'जहाज': 773,
 'कोठरियां': 774,
 'भीतर': 775,
 'राल': 776,
 'लगानाऔर': 777,
 'ढंग': 778,
 'लम्बाई': 779,
 'चौड़ाई': 780,
 'पचास': 781,
 'ऊंचाई': 782,
 'होजहाज': 783,
 'खिड़की': 784,
 'छत': 785,
 'अलंग': 786,
 'रखना': 787,
 'खण्ड': 788,
 'बनानाऔर': 789,
 'जलप्रलय': 790,
 'हूं': 791,
 'जाएंगेपरन्तु': 792,
 'वाचा': 793,
 'बान्धता': 794,
 'बहुओं': 795,
 'प्रवेश': 796,
 'करनाऔर': 797,
 'मादा': 798,
 'जा': 799,
 'रखनाएक': 800,
 'आएंगे': 801,
 'रखेऔर': 802,
 'भोज्य': 803,
 'पदार्थ': 804,
 'जाता': 805,
 'होगापरमेश्वर': 806,
 'घराने': 807,
 'केवल': 808,
 'तुझी': 809,
 'हैसब': 810,
 'शुद्ध': 811,
 'लेना': 812,
 'मादाऔर': 813,
 'बचकर': 814,
 'रहेक्योंकि': 815,
 'बीतने': 816,
 'बरसाता': 817,
 'जितनी': 818,
 'वस्तुएं': 819,
 'दूंगायहोवा': 820,
 'कियानूह': 821,
 'छ': 822,
 'आयानूह': 823,
 'बचने': 824,
 'अशुद्ध': 825,
 'पक्षियोंऔर': 826,
 'वालों': 827,
 'थीसात': 828,
 'उपरान्त': 829,
 'प्रलय': 830,
 'आने': 831,
 'सौवें': 832,
 'दूसरे': 833,
 'महीने': 834,
 'सत्तरहवां': 835,
 'गहिरे': 836,
 'सोते': 837,
 'फूट': 838,
 'निकले': 839,
 'झरोखे': 840,
 'गएऔर': 841,
 'वर्षा': 842,
 'होती': 843,
 'रहीठीक': 844,
 'तीनों': 845,
 'समेतऔर': 846,
 'गएजितने': 847,
 'जातियों': 848,
 'बन्द': 849,
 'पानी': 850,
 'बढ़ता': 851,
 'उठने': 852,
 'लगा': 853,
 'ऊंचा': 854,
 'उठ': 855,
 'बढ़ते': 856,
 'तैरता': 857,
 'अत्यन्त': 858,
 'यहां': 859,
 'धरती': 860,
 'पहाड़': 861,
 'डूब': 862,
 'गएजल': 863,
 'चलने': 864,
 'बहुतायत': 865,
 'गएजो': 866,
 'स्थल': 867,
 'जितनों': 868,
 'मिटेऔर': 869,
 'मिट': 870,
 'बच': 871,
 'प्रबल': 872,
 'सभों': 873,
 'सुधि': 874,
 'पवन': 875,
 'बहाई': 876,
 'घटने': 877,
 'लगाऔर': 878,
 'बंद': 879,
 'थम': 880,
 'गईऔर': 881,
 'पशचात': 882,
 'लगातार': 883,
 'लगासातवें': 884,
 'सत्तरहवें': 885,
 'अरारात': 886,
 'टिक': 887,
 'दसवें': 888,
 'घटता': 889,
 'पहिले': 890,
 'पहाड़ों': 891,
 'चोटियाँ': 892,
 'दिखलाई': 893,
 'दींफिर': 894,
 'खोल': 895,
 'कौआ': 896,
 'उड़ा': 897,
 'दियावह': 898,
 'सूख': 899,
 'इधर': 900,
 'उधर': 901,
 'रहाफिर': 902,
 'कबूतरी': 903,
 'घट': 904,
 'नहींउस': 905,
 'पैर': 906,
 'तले': 907,
 'टेकने': 908,
 'आधार': 909,
 'लौट': 910,
 'आई': 911,
 'छाया': 912,
 'लियातब': 913,
 'ठहर': 914,
 'चोंच': 915,
 'जलपाई': 916,
 'नया': 917,
 'पत्ता': 918,
 'जान': 919,
 'ठहरकर': 920,
 'आईफिर': 921,
 'सताईसवें': 922,
 'कहातू': 923,
 'आक्या': 924,
 'शरीरधारी': 925,
 'जीवजन्तु': 926,
 'फूलेंफलें': 927,
 'फैल': 928,
 'जाएंतब': 929,
 'बहुएं': 930,
 'आईंऔर': 931,
 'चौपाए': 932,
 'आएतब': 933,
 'वेदी': 934,
 'बनाई': 935,
 'होमबलि': 936,
 'चढ़ायाइस': 937,
 'सुखदायक': 938,
 'सुगन्ध': 939,
 'यद्यपि': 940,
 'बचपन': 941,
 'जैसा': 942,
 'जीवों': 943,
 'मारा': 944,
 'मारूंगाअब': 945,
 'रहेगी': 946,
 'बोने': 947,
 'काटने': 948,
 'ठण्ड': 949,
 'तपन': 950,
 'धूपकाल': 951,
 'शीतकाल': 952,
 'चले': 953,
 'जाएंगेफिर': 954,
 'बढ़ो': 955,
 'जाओऔर': 956,
 'तुम्हारा': 957,
 'भय': 958,
 'जाते': 959,
 'हैंसब': 960,
 'आहार': 961,
 'होंगे': 962,
 'देता': 963,
 'हूंपर': 964,
 'खानाऔर': 965,
 'लूंगा': 966,
 'बन्धु': 967,
 'लूंगाजो': 968,
 'बहाएगा': 969,
 'बहाया': 970,
 'जन्मा': 971,
 'जाओफिर': 972,
 'कहासुनों': 973,
 'हूंऔर': 974,
 'बन्धती': 975,
 'पूरा': 976,
 'करूंगा': 977,
 'होगाफिर': 978,
 'युग': 979,
 'पीढिय़ों': 980,
 'हैकि': 981,
 'बादल': 982,
 'धनुष': 983,
 'होगाऔर': 984,
 'फैलाऊं': 985,
 'देख': 986,
 'पड़ेगातब': 987,
 'बान्धी': 988,
 'स्मरण': 989,
 'विनाश': 990,
 'होबादल': 991,
 'बन्धी': 992,
 'यही': 993,
 'हैनूह': 994,
 'कनान': 995,
 'हुआनूह': 996,
 'ये': 997,
 'इनका': 998,
 'किसानी': 999,
 ...}

In [ ]:
print("Number of unique words:", len(unique_words))

Number of unique words: 97256

In [ ]:
list(unique_words.keys())

['आदि',
 'में',
 'परमेश्वर',
 'ने',
 'आकाश',
 'और',
 'पृथ्वी',
 'की',
 'सृष्टि',
 'कीऔर',
 'बेडौल',
 'सुनसान',
 'पड़ी',
 'थी',
 'गहरे',
 'जल',
 'के',
 'ऊपर',
 'अन्धियारा',
 'था',
 'तथा',
 'का',
 'आत्मा',
 'मण्डलाता',
 'थातब',
 'कहा',
 'उजियाला',
 'हो',
 'तो',
 'गयाऔर',
 'उजियाले',
 'को',
 'देखा',
 'कि',
 'अच्छा',
 'है',
 'अन्धियारे',
 'से',
 'अलग',
 'कियाऔर',
 'दिन',
 'रात',
 'सांझ',
 'हुई',
 'फिर',
 'भोर',
 'हुआ',
 'इस',
 'प्रकार',
 'पहिला',
 'गयाफिर',
 'बीच',
 'एक',
 'ऐसा',
 'अन्तर',
 'दो',
 'भाग',
 'जाएतब',
 'करके',
 'उसके',
 'नीचे',
 'किया',
 'वैसा',
 'ही',
 'उस',
 'दूसरा',
 'स्थान',
 'इकट्ठा',
 'जाए',
 'सूखी',
 'भूमि',
 'दिखाई',
 'दे',
 'जो',
 'उसको',
 'उसने',
 'समुद्र',
 'हैफिर',
 'हरी',
 'घास',
 'बीज',
 'वाले',
 'छोटे',
 'पेड़',
 'फलदाई',
 'वृक्ष',
 'भी',
 'जिनके',
 'उन्ही',
 'जाति',
 'अनुसार',
 'होते',
 'हैं',
 'पर',
 'उगें',
 'गयातो',
 'जिन',
 'अपनी',
 'होता',
 'उगे',
 'हैतथा',
 'तीसरा',
 'करने',
 'लिये',
 'ज्योतियां',
 'हों',
 'वे',
 'चिन्हों',
 'नियत',
 'समयों',
 'दिनों',
 'वर्षों',
 'कारण',
 'होंऔर',
 'प्रकाश',
 'देने',
 'वाली',
 'ठहरें',
 'गयातब',
 'बड़ी',
 'बनाईं',
 'उन',
 'ज्योति',
 'प्रभुता',
 'छोटी',
 'बनाया',
 'तारागण',
 'बनायापरमेश्वर',
 'इसलिये',
 'रखा',
 'देंतथा',
 'करें',
 'चौथा',
 'जीवित',
 'प्राणियों',
 'बहुत',
 'भर',
 'पक्षी',
 'उड़ेंइसलिये',
 'बड़े',
 'जलजन्तुओं',
 'सब',
 'चलते',
 'फिरते',
 'गया',
 'उड़ने',
 'पक्षियों',
 'हैऔर',
 'यह',
 'कहके',
 'उनको',
 'आशीष',
 'दी',
 'फूलोफलो',
 'जाओ',
 'बढ़ेंतथा',
 'पांचवां',
 'प्राणी',
 'अर्थात',
 'घरेलू',
 'पशु',
 'रेंगने',
 'जन्तु',
 'वनपशु',
 'उत्पन्न',
 'गयासो',
 'वन',
 'पशुओं',
 'जन्तुओं',
 'हम',
 'मनुष्य',
 'अपने',
 'स्वरूप',
 'समानता',
 'बनाएं',
 'मछलियों',
 'सारी',
 'रेंगते',
 'अधिकार',
 'रखेंतब',
 'नर',
 'नारी',
 'मनुष्यों',
 'वश',
 'कर',
 'लो',
 'जन्तुओ',
 'रखोफिर',
 'सुनो',
 'जितने',
 'वृक्षों',
 'फल',
 'मैं',
 'तुम',
 'दिए',
 'तुम्हारे',
 'भोजन',
 'हैंऔर',
 'जीवन',
 'प्राण',
 'खाने',
 'हरे',
 'कुछ',
 'क्या',
 'वह',
 'छठवां',
 'गयायों',
 'उनकी',
 'सेना',
 'बनाना',
 'समाप्त',
 'अपना',
 'काम',
 'जिसे',
 'करता',
 'सातवें',
 'किए',
 'हुए',
 'सारे',
 'विश्राम',
 'पवित्र',
 'ठहराया',
 'क्योंकि',
 'रचना',
 'लियाआकाश',
 'उत्पत्ति',
 'वृत्तान्त',
 'जब',
 'जिस',
 'यहोवा',
 'बनायातब',
 'मैदान',
 'कोई',
 'पौधा',
 'न',
 'छोटा',
 'उगा',
 'नहीं',
 'बरसाया',
 'खेती',
 'थातौभी',
 'कोहरा',
 'उठता',
 'सिंच',
 'जाती',
 'थीऔर',
 'आदम',
 'मिट्टी',
 'रचा',
 'नथनों',
 'श्वास',
 'फूंक',
 'दिया',
 'जीवता',
 'बन',
 'पूर्व',
 'ओर',
 'अदन',
 'देश',
 'वाटिका',
 'लगाई',
 'वहां',
 'रख',
 'दियाऔर',
 'भांति',
 'देखने',
 'मनोहर',
 'अच्छे',
 'उगाए',
 'भले',
 'या',
 'बुरे',
 'ज्ञान',
 'लगायाऔर',
 'सींचने',
 'महानदी',
 'निकली',
 'आगे',
 'बहकर',
 'चार',
 'धारा',
 'गईपहिली',
 'नाम',
 'पीशोन',
 'वही',
 'हवीला',
 'जहां',
 'सोना',
 'मिलता',
 'घेरे',
 'हैउस',
 'चोखा',
 'मोती',
 'सुलैमानी',
 'पत्थर',
 'मिलते',
 'दूसरी',
 'नदी',
 'गीहोन',
 'कूश',
 'तीसरी',
 'हिद्देकेल',
 'अश्शूर',
 'बहती',
 'चौथी',
 'फरात',
 'हैतब',
 'ले',
 'करे',
 'उसकी',
 'रक्षा',
 'करेतब',
 'आज्ञा',
 'तू',
 'बिना',
 'खटके',
 'खा',
 'सकता',
 'हैपर',
 'उसका',
 'कभी',
 'खाना',
 'खाए',
 'उसी',
 'अवश्य',
 'मर',
 'जाएगाफिर',
 'अकेला',
 'रहना',
 'सहायक',
 'बनाऊंगा',
 'उससे',
 'मेल',
 'खाएऔर',
 'बनैले',
 'भाँति',
 'रचकर',
 'पास',
 'आया',
 'देखें',
 'उनका',
 'रखता',
 'रखे',
 'परन्तु',
 'मिला',
 'सकेतब',
 'भारी',
 'नीन्द',
 'डाल',
 'सो',
 'तब',
 'पसली',
 'निकाल',
 'सन्ती',
 'मांस',
 'निकाली',
 'स्त्री',
 'बना',
 'आयाऔर',
 'अब',
 'मेरी',
 'हड्डियों',
 'हड्डी',
 'मेरे',
 'इसका',
 'होगा',
 'गई',
 'हैइस',
 'पुरूष',
 'माता',
 'पिता',
 'छोड़कर',
 'पत्नी',
 'रहेगा',
 'तन',
 'बने',
 'रहेंगेऔर',
 'दोनो',
 'नंगे',
 'थे',
 'लजाते',
 'बनाए',
 'सर्प',
 'धूर्त',
 'सच',
 'बाटिका',
 'किसी',
 'खानास्त्री',
 'सकते',
 'हैंपर',
 'विषय',
 'छूना',
 'जाओगेतब',
 'निश्चय',
 'मरोगेवरन',
 'आप',
 'जानता',
 'खाओगे',
 'तुम्हारी',
 'आंखें',
 'खुल',
 'जाएंगी',
 'पाकर',
 'तुल्य',
 'जाओगेसो',
 'मनभाऊ',
 'बुद्धि',
 'चाहने',
 'योग्य',
 'तोड़कर',
 'खाया',
 'पति',
 'खायातब',
 'दोनों',
 'आंखे',
 'मालूम',
 'उन्होंने',
 'अंजीर',
 'पत्ते',
 'जोड़',
 'लंगोट',
 'लियेतब',
 'ठंडे',
 'समय',
 'फिरता',
 'शब्द',
 'सुनाई',
 'छिप',
 'गएतब',
 'पुकार',
 'पूछा',
 'कहां',
 'हैउसने',
 'तेरा',
 'बारी',
 'सुन',
 'डर',
 'नंगा',
 'गयाउसने',
 'किस',
 'तुझे',
 'चिताया',
 'बर्जा',
 'हैआदम',
 'संग',
 'रहने',
 'मुझे',
 'बहका',
 'अधिक',
 'शापित',
 'पेट',
 'बल',
 'चला',
 'करेगा',
 'चाटता',
 'रहेगाऔर',
 'तेरे',
 'वंश',
 'इसके',
 'बैर',
 'करुंगा',
 'सिर',
 'कुचल',
 'डालेगा',
 'एड़ी',
 'डसेगाफिर',
 'तेरी',
 'पीड़ा',
 'गर्भवती',
 'होने',
 'दुख',
 'बढ़ाऊंगा',
 'पीड़ित',
 'बालक',
 'करेगी',
 'लालसा',
 'होगी',
 'तुझ',
 'करेगाऔर',
 'बात',
 'सुनी',
 'उसे',
 'उपज',
 'साथ',
 'कांटे',
 'ऊंटकटारे',
 'उगाएगी',
 'खेत',
 'खाएगा',
 'माथे',
 'पसीने',
 'रोटी',
 'अन्त',
 'मिल',
 'जाएगा',
 'निकाला',
 'जाएगाऔर',
 'हव्वा',
 'आदिमाता',
 'हुईऔर',
 'चमड़े',
 'अंगरखे',
 'पहिना',
 'दिएफिर',
 'समान',
 'हाथ',
 'बढ़ा',
 'तोड़',
 'सदा',
 'रहेतब',
 'थाइसलिये',
 'मार्ग',
 'पहरा',
 'करुबों',
 'चारों',
 'घूमने',
 'ज्वालामय',
 'तलवार',
 'नियुक्त',
 'दियाजब',
 'कैन',
 'जन्म',
 'सहायता',
 'पाया',
 'भाई',
 'हाबिल',
 'जन्मी',
 'भेड़बकरियों',
 'चरवाहा',
 'वाला',
 'किसान',
 'बनाकुछ',
 'पश्चात',
 'भेंट',
 'कई',
 'पहिलौठे',
 'बच्चे',
 'चढ़ाने',
 'चर्बी',
 'चढ़ाई',
 'ग्रहण',
 'कियापरन्तु',
 'अति',
 'क्रोधित',
 'मुंह',
 'उदासी',
 'छा',
 'गईतब',
 'क्यों',
 'हैयदि',
 'भला',
 'जाएगी',
 'यदि',
 'पाप',
 'द्वार',
 'छिपा',
 'रहता',
 'करेगातब',
 'चढ़',
 'घात',
 'कियातब',
 'रखवाला',
 'हूंउसने',
 'लोहू',
 'चिल्ला',
 'दोहाई',
 'रहा',
 'हैइसलिये',
 'जिसने',
 'पीने',
 'खोला',
 'हैचाहे',
 'तौभी',
 'पूरी',
 'मिलेगी',
 'बहेतू',
 'भगोड़ा',
 'होगातब',
 'मेरा',
 'दण्ड',
 'सहने',
 'बाहर',
 'हैदेख',
 'आज',
 'दृष्टि',
 'आड़',
 'मे',
 'रहूंगा',
 'पाएगा',
 'करेगाइस',
 'सात',
 'गुणा',
 'पलटा',
 'लिया',
 'चिन्ह',
 'मार',
 'डालेतब',
 'सम्मुख',
 'निकल',
 'नोद',
 'लगाजब',
 'हनोक',
 'नगर',
 'बसाया',
 'पुत्र',
 'रखाऔर',
 'ईराद',
 'महूयाएल',
 'मतूशाएल',
 'लेमेक',
 'स्त्रियां',
 'ब्याह',
 'ली',
 'आदा',
 'सिल्ला',
 'याबाल',
 'तम्बुओं',
 'जानवरों',
 'पालन',
 'इन',
 'रीतियों',
 'उत्पादक',
 'हुआऔर',
 'यूबाल',
 'वीणा',
 'बांसुरी',
 'बाजों',
 'बजाने',
 'रीति',
 'तूबल्कैन',
 'पीतल',
 'लोहे',
 'धार',
 'हथियारों',
 'गढ़ने',
 'बहिन',
 'नामा',
 'पत्नियों',
 'हे',
 'कान',
 'लगाओ',
 'मैंने',
 'चोट',
 'लगाता',
 'जवान',
 'घायल',
 'हैजब',
 'सत्तर',
 'कह',
 'शेत',
 'ठहरा',
 'एनोश',
 'लोग',
 'प्रार्थना',
 'लगेआदम',
 'वंशावली',
 'बनायाउसने',
 'उन्हें',
 'रखाजब',
 'सौ',
 'तीस',
 'वर्ष',
 'द्वारा',
 'आठ',
 'बेटे',
 'बेटियां',
 'हुईंऔर',
 'कुल',
 'अवस्था',
 'नौ',
 'तत्पश्चात',
 'गयाजब',
 'पांच',
 'बारह',
 'नब्बे',
 'केनान',
 'पन्द्रह',
 'महललेल',
 'चालीस',
 'दस',
 'पैंसठ',
 'येरेद',
 'पंचानवे',
 'बासठ',
 'मतूशेलह',
 'तीन',
 'तक',
 'चलता',
 'लोप',
 'उठा',
 'लियाजब',
 'सत्तासी',
 'बयासी',
 'उनहत्तर',
 'कहकर',
 'नूह',
 'शाप',
 'लड़का',
 'हमारे',
 'कठिन',
 'परिश्रम',
 'करते',
 'शान्ति',
 'देगाऔर',
 'सतहत्तर',
 'शेम',
 'हाम',
 'येपेत',
 'दियाफिर',
 'बढ़ने',
 'लगे',
 'उनके',
 'हुईतब',
 'पुत्रों',
 'पुत्रियों',
 'सुन्दर',
 'चाहा',
 'लियाऔर',
 'लों',
 'विवाद',
 'शरीर',
 'आयु',
 'बीस',
 'होगीउन',
 'दानव',
 'रहते',
 'गए',
 'सन्तान',
 'शूरवीर',
 'जिनकी',
 'कीर्ति',
 'प्राचीन',
 'काल',
 'प्रचलित',
 'बुराई',
 'बढ़',
 'मन',
 'विचार',
 'निरन्तर',
 'बुरा',
 'बनाने',
 'पछताया',
 'खेदित',
 'हुआतब',
 'सोचा',
 'जिसकी',
 'मिटा',
 'दूंगा',
 'पछताता',
 'हूंपरन्तु',
 'अनुग्रह',
 'बनी',
 'रहीनूह',
 'धर्मी',
 'लोगों',
 'खरा',
 'रहाऔर',
 'हुएउस',
 'बिगड़',
 'उपद्रव',
 'बिगड़ी',
 'चाल',
 'चलन',
 'बिगाड़',
 'थीतब',
 'प्रश्न',
 'साम्हने',
 'आ',
 'समेत',
 'नाश',
 'डालूंगाइसलिये',
 'गोपेर',
 'लकड़ी',
 'जहाज',
 'कोठरियां',
 'भीतर',
 'राल',
 'लगानाऔर',
 'ढंग',
 'लम्बाई',
 'चौड़ाई',
 'पचास',
 'ऊंचाई',
 'होजहाज',
 'खिड़की',
 'छत',
 'अलंग',
 'रखना',
 'खण्ड',
 'बनानाऔर',
 'जलप्रलय',
 'हूं',
 'जाएंगेपरन्तु',
 'वाचा',
 'बान्धता',
 'बहुओं',
 'प्रवेश',
 'करनाऔर',
 'मादा',
 'जा',
 'रखनाएक',
 'आएंगे',
 'रखेऔर',
 'भोज्य',
 'पदार्थ',
 'जाता',
 'होगापरमेश्वर',
 'घराने',
 'केवल',
 'तुझी',
 'हैसब',
 'शुद्ध',
 'लेना',
 'मादाऔर',
 'बचकर',
 'रहेक्योंकि',
 'बीतने',
 'बरसाता',
 'जितनी',
 'वस्तुएं',
 'दूंगायहोवा',
 'कियानूह',
 'छ',
 'आयानूह',
 'बचने',
 'अशुद्ध',
 'पक्षियोंऔर',
 'वालों',
 'थीसात',
 'उपरान्त',
 'प्रलय',
 'आने',
 'सौवें',
 'दूसरे',
 'महीने',
 'सत्तरहवां',
 'गहिरे',
 'सोते',
 'फूट',
 'निकले',
 'झरोखे',
 'गएऔर',
 'वर्षा',
 'होती',
 'रहीठीक',
 'तीनों',
 'समेतऔर',
 'गएजितने',
 'जातियों',
 'बन्द',
 'पानी',
 'बढ़ता',
 'उठने',
 'लगा',
 'ऊंचा',
 'उठ',
 'बढ़ते',
 'तैरता',
 'अत्यन्त',
 'यहां',
 'धरती',
 'पहाड़',
 'डूब',
 'गएजल',
 'चलने',
 'बहुतायत',
 'गएजो',
 'स्थल',
 'जितनों',
 'मिटेऔर',
 'मिट',
 'बच',
 'प्रबल',
 'सभों',
 'सुधि',
 'पवन',
 'बहाई',
 'घटने',
 'लगाऔर',
 'बंद',
 'थम',
 'गईऔर',
 'पशचात',
 'लगातार',
 'लगासातवें',
 'सत्तरहवें',
 'अरारात',
 'टिक',
 'दसवें',
 'घटता',
 'पहिले',
 'पहाड़ों',
 'चोटियाँ',
 'दिखलाई',
 'दींफिर',
 'खोल',
 'कौआ',
 'उड़ा',
 'दियावह',
 'सूख',
 'इधर',
 'उधर',
 'रहाफिर',
 'कबूतरी',
 'घट',
 'नहींउस',
 'पैर',
 'तले',
 'टेकने',
 'आधार',
 'लौट',
 'आई',
 'छाया',
 'लियातब',
 'ठहर',
 'चोंच',
 'जलपाई',
 'नया',
 'पत्ता',
 'जान',
 'ठहरकर',
 'आईफिर',
 'सताईसवें',
 'कहातू',
 'आक्या',
 'शरीरधारी',
 'जीवजन्तु',
 'फूलेंफलें',
 'फैल',
 'जाएंतब',
 'बहुएं',
 'आईंऔर',
 'चौपाए',
 'आएतब',
 'वेदी',
 'बनाई',
 'होमबलि',
 'चढ़ायाइस',
 'सुखदायक',
 'सुगन्ध',
 'यद्यपि',
 'बचपन',
 'जैसा',
 'जीवों',
 'मारा',
 'मारूंगाअब',
 'रहेगी',
 'बोने',
 'काटने',
 'ठण्ड',
 'तपन',
 'धूपकाल',
 'शीतकाल',
 'चले',
 'जाएंगेफिर',
 'बढ़ो',
 'जाओऔर',
 'तुम्हारा',
 'भय',
 'जाते',
 'हैंसब',
 'आहार',
 'होंगे',
 'देता',
 'हूंपर',
 'खानाऔर',
 'लूंगा',
 'बन्धु',
 'लूंगाजो',
 'बहाएगा',
 'बहाया',
 'जन्मा',
 'जाओफिर',
 'कहासुनों',
 'हूंऔर',
 'बन्धती',
 'पूरा',
 'करूंगा',
 'होगाफिर',
 'युग',
 'पीढिय़ों',
 'हैकि',
 'बादल',
 'धनुष',
 'होगाऔर',
 'फैलाऊं',
 'देख',
 'पड़ेगातब',
 'बान्धी',
 'स्मरण',
 'विनाश',
 'होबादल',
 'बन्धी',
 'यही',
 'हैनूह',
 'कनान',
 'हुआनूह',
 'ये',
 'इनका',
 'किसानी',
 ...]

In [ ]:
import pandas as pd
unique_words_df = pd.DataFrame({
    'Word': list(unique_words.keys()),
    'Int': list(unique_words.values())
})

In [ ]:
unique_words_df['Word']

0                आदि
1                में
2           परमेश्वर
3                 ने
4               आकाश
            ...
97251          विदोश
97252    सूपरमार्केट
97253         रोजाने
97254         अंदेखा
97255       ट्रेफ़िक
Name: Word, Length: 97256, dtype: object

In [ ]:
unique_words_df.to_csv("unique_words.csv")

In [ ]:
r"parents" in cleaned_text

False

### Trying Byte pair encoding

In [3]:
cleaned_text = open("cleaned_data.txt", "r", encoding='utf-8').read()

In [2]:
#cleaned_text = list(open("cleaned_data.txt", "r", encoding='utf-8').read())

In [12]:
cleaned_text[:1000]

'आदि में परमेश्वर ने आकाश और पृथ्वी की सृष्टि कीऔर पृथ्वी बेडौल और सुनसान पड़ी थी और गहरे जल के ऊपर अन्धियारा था तथा परमेश्वर का आत्मा जल के ऊपर मण्डलाता थातब परमेश्वर ने कहा उजियाला हो तो उजियाला हो गयाऔर परमेश्वर ने उजियाले को देखा कि अच्छा है और परमेश्वर ने उजियाले को अन्धियारे से अलग कियाऔर परमेश्वर ने उजियाले को दिन और अन्धियारे को रात कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार पहिला दिन हो गयाफिर परमेश्वर ने कहा जल के बीच एक ऐसा अन्तर हो कि जल दो भाग हो जाएतब परमेश्वर ने एक अन्तर करके उसके नीचे के जल और उसके ऊपर के जल को अलग अलग किया और वैसा ही हो गयाऔर परमेश्वर ने उस अन्तर को आकाश कहा तथा सांझ हुई फिर भोर हुआ इस प्रकार दूसरा दिन हो गयाफिर परमेश्वर ने कहा आकाश के नीचे का जल एक स्थान में इकट्ठा हो जाए और सूखी भूमि दिखाई दे और वैसा ही हो गयाऔर परमेश्वर ने सूखी भूमि को पृथ्वी कहा तथा जो जल इकट्ठा हुआ उसको उसने समुद्र कहा और परमेश्वर ने देखा कि अच्छा हैफिर परमेश्वर ने कहा पृथ्वी से हरी घास तथा बीज वाले छोटे छोटे पेड़ और फलदाई वृक्ष भी जिनके बीज उन्ही में एक एक की जाति के अनुसार होते हैं प'

In [13]:
import numpy as np
unique_chars = np.unique(list(cleaned_text))

In [14]:
unique_chars

array([' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'ँ', 'ं',
       'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऌ', 'ऍ', 'ऎ', 'ए', 'ऐ',
       'ऑ', 'ऒ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ',
       'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प',
       'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'ळ', 'ऴ', 'व', 'श', 'ष',
       'स', 'ह', 'ऺ', 'ऻ', '़', 'ऽ', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॄ',
       'ॅ', 'ॆ', 'े', 'ै', 'ॉ', 'ॊ', 'ो', 'ौ', '्', 'ॎ', 'ॐ', 'क़', 'ख़',
       'ज़', 'ड़', 'ढ़', 'फ़', 'य़', 'ॠ', 'ॡ', 'ॢ', 'ॣ', 'ॱ', 'ॲ', 'ॻ', 'ॼ',
       'ॾ', 'ॿ'], dtype='<U1')

In [15]:
with open("unique_chars.txt", "w") as f:
  for c in unique_chars:
    f.write(c+"\n")

In [4]:
unique_chars = open('unique_chars.txt', 'r', encoding='utf-8').read().split("\n")

In [16]:
unique_chars

array([' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'ँ', 'ं',
       'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऌ', 'ऍ', 'ऎ', 'ए', 'ऐ',
       'ऑ', 'ऒ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'ङ', 'च', 'छ', 'ज', 'झ',
       'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प',
       'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'ळ', 'ऴ', 'व', 'श', 'ष',
       'स', 'ह', 'ऺ', 'ऻ', '़', 'ऽ', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'ॄ',
       'ॅ', 'ॆ', 'े', 'ै', 'ॉ', 'ॊ', 'ो', 'ौ', '्', 'ॎ', 'ॐ', 'क़', 'ख़',
       'ज़', 'ड़', 'ढ़', 'फ़', 'य़', 'ॠ', 'ॡ', 'ॢ', 'ॣ', 'ॱ', 'ॲ', 'ॻ', 'ॼ',
       'ॾ', 'ॿ'], dtype='<U1')

In [4]:
words = cleaned_text.split()

In [5]:
words[:100]

['आदि',
 'में',
 'परमेश्वर',
 'ने',
 'आकाश',
 'और',
 'पृथ्वी',
 'की',
 'सृष्टि',
 'कीऔर',
 'पृथ्वी',
 'बेडौल',
 'और',
 'सुनसान',
 'पड़ी',
 'थी',
 'और',
 'गहरे',
 'जल',
 'के',
 'ऊपर',
 'अन्धियारा',
 'था',
 'तथा',
 'परमेश्वर',
 'का',
 'आत्मा',
 'जल',
 'के',
 'ऊपर',
 'मण्डलाता',
 'थातब',
 'परमेश्वर',
 'ने',
 'कहा',
 'उजियाला',
 'हो',
 'तो',
 'उजियाला',
 'हो',
 'गयाऔर',
 'परमेश्वर',
 'ने',
 'उजियाले',
 'को',
 'देखा',
 'कि',
 'अच्छा',
 'है',
 'और',
 'परमेश्वर',
 'ने',
 'उजियाले',
 'को',
 'अन्धियारे',
 'से',
 'अलग',
 'कियाऔर',
 'परमेश्वर',
 'ने',
 'उजियाले',
 'को',
 'दिन',
 'और',
 'अन्धियारे',
 'को',
 'रात',
 'कहा',
 'तथा',
 'सांझ',
 'हुई',
 'फिर',
 'भोर',
 'हुआ',
 'इस',
 'प्रकार',
 'पहिला',
 'दिन',
 'हो',
 'गयाफिर',
 'परमेश्वर',
 'ने',
 'कहा',
 'जल',
 'के',
 'बीच',
 'एक',
 'ऐसा',
 'अन्तर',
 'हो',
 'कि',
 'जल',
 'दो',
 'भाग',
 'हो',
 'जाएतब',
 'परमेश्वर',
 'ने',
 'एक',
 'अन्तर']

In [6]:
vocab = {}

for word in words:
  token = " ".join(list(word)) + r" <w>"
  if token not in vocab:
    vocab[token] = 1
  else:
    vocab[token] += 1

In [7]:
vocab

{'आ द ि <w>': 61443,
 'म े ं <w>': 2554180,
 'प र म े श ् व र <w>': 4963,
 'न े <w>': 487710,
 'आ क ा श <w>': 6063,
 'औ र <w>': 1693280,
 'प ृ थ ् व ी <w>': 17072,
 'क ी <w>': 1745880,
 'स ृ ष ् ट ि <w>': 3166,
 'क ी औ र <w>': 74,
 'ब े ड ौ ल <w>': 31,
 'स ु न स ा न <w>': 152,
 'प ड ़ ी <w>': 4600,
 'थ ी <w>': 158145,
 'ग ह र े <w>': 3040,
 'ज ल <w>': 22395,
 'क े <w>': 3460205,
 'ऊ प र <w>': 25846,
 'अ न ् ध ि य ा र ा <w>': 22,
 'थ ा <w>': 389654,
 'त थ ा <w>': 244962,
 'क ा <w>': 1291782,
 'आ त ् म ा <w>': 7881,
 'म ण ् ड ल ा त ा <w>': 2,
 'थ ा त ब <w>': 126,
 'क ह ा <w>': 104936,
 'उ ज ि य ा ल ा <w>': 52,
 'ह ो <w>': 336138,
 'त ो <w>': 270637,
 'ग य ा औ र <w>': 290,
 'उ ज ि य ा ल े <w>': 31,
 'क ो <w>': 1144583,
 'द े ख ा <w>': 24245,
 'क ि <w>': 483936,
 'अ च ् छ ा <w>': 17177,
 'ह ै <w>': 2567639,
 'अ न ् ध ि य ा र े <w>': 45,
 'स े <w>': 1407775,
 'अ ल ग <w>': 34163,
 'क ि य ा औ र <w>': 168,
 'द ि न <w>': 57802,
 'र ा त <w>': 11809,
 'स ा ं झ <w>': 166,
 'ह ु ई <w>': 83864,
 'फ ि र <w>': 82797,
 'भ ो र <w>': 414,
 'ह ु आ <w>': 143330,
 'इ स <w>': 395764,
 'प ् र क ा र <w>': 102577,
 'प ह ि ल ा <w>': 91,
 'ग य ा फ ि र <w>': 43,
 'ब ी च <w>': 66414,
 'ए क <w>': 792156,
 'ऐ स ा <w>': 47496,
 'अ न ् त र <w>': 4805,
 'द ो <w>': 98826,
 'भ ा ग <w>': 57403,
 'ज ा ए त ब <w>': 38,
 'क र क े <w>': 32865,
 'उ स क े <w>': 103089,
 'न ी च े <w>': 22953,
 'क ि य ा <w>': 472029,
 'व ै स ा <w>': 2299,
 'ह ी <w>': 339524,
 'उ स <w>': 99004,
 'द ू स र ा <w>': 15650,
 'स ् थ ा न <w>': 51880,
 'इ क ट ् ठ ा <w>': 2863,
 'ज ा ए <w>': 25243,
 'स ू ख ी <w>': 1124,
 'भ ू म ि <w>': 17175,
 'द ि ख ा ई <w>': 14837,
 'द े <w>': 37422,
 'ज ो <w>': 374975,
 'उ स क ो <w>': 10194,
 'उ स न े <w>': 43842,
 'स म ु द ् र <w>': 11146,
 'ह ै फ ि र <w>': 294,
 'ह र ी <w>': 1632,
 'घ ा स <w>': 2737,
 'ब ी ज <w>': 4412,
 'व ा ल े <w>': 100782,
 'छ ो ट े <w>': 20663,
 'प े ड ़ <w>': 4534,
 'फ ल द ा ई <w>': 16,
 'व ृ क ् ष <w>': 4897,
 'भ ी <w>': 518822,
 'ज ि न क े <w>': 12527,
 'उ न ् ह ी <w>': 736,
 'ज ा त ि <w>': 13593,
 'अ न ु स ा र <w>': 64769,
 'ह ो त े <w>': 86654,
 'ह ै ं <w>': 897087,
 'प र <w>': 681481,
 'उ ग े ं <w>': 11,
 'ग य ा त ो <w>': 7,
 'ज ि न <w>': 16830,
 'अ प न ी <w>': 113919,
 'ह ो त ा <w>': 181270,
 'उ ग े <w>': 89,
 'ह ै त थ ा <w>': 66,
 'त ी स र ा <w>': 4433,
 'क र न े <w>': 276064,
 'ल ि य े <w>': 66649,
 'ज ् य ो त ि य ा ं <w>': 11,
 'ह ो ं <w>': 17231,
 'व े <w>': 166212,
 'च ि न ् ह ो ं <w>': 509,
 'न ि य त <w>': 3403,
 'स म य ो ं <w>': 324,
 'द ि न ो ं <w>': 15089,
 'व र ् ष ो ं <w>': 26094,
 'क ा र ण <w>': 101399,
 'ह ो ं औ र <w>': 58,
 'प ् र क ा श <w>': 16932,
 'द े न े <w>': 37007,
 'व ा ल ी <w>': 51172,
 'ठ ह र े ं <w>': 211,
 'ग य ा त ब <w>': 131,
 'ब ड ़ ी <w>': 34359,
 'ब न ा ई ं <w>': 247,
 'उ न <w>': 66115,
 'ज ् य ो त ि <w>': 1550,
 'प ् र भ ु त ा <w>': 402,
 'छ ो ट ी <w>': 11605,
 'ब न ा य ा <w>': 29978,
 'त ा र ा ग ण <w>': 20,
 'ब न ा य ा प र म े श ् व र <w>': 1,
 'इ स ल ि य े <w>': 4879,
 'र ख ा <w>': 29951,
 'द े ं त थ ा <w>': 1,
 'क र े ं <w>': 49902,
 'च ौ थ ा <w>': 2092,
 'ज ी व ि त <w>': 7599,
 'प ् र ा ण ि य ो ं <w>': 3402,
 'ब ह ु त <w>': 103996,
 'भ र <w>': 18317,
 'प क ् ष ी <w>': 4076,
 'उ ड ़ े ं इ स ल ि य े <w>': 1,
 'ब ड ़ े <w>': 34791,
 'ज ल ज न ् त ु ओ ं <w>': 2,
 'स ब <w>': 37911,
 'च ल त े <w>': 8165,
 'फ ि र त े <w>': 642,
 'ग य ा <w>': 331911,
 'उ ड ़ न े <w>': 788,
 'प क ् ष ि य ो ं <w>': 2920,
 'ह ै औ र <w>': 1402,
 'य ह <w>': 448592,
 'क ह क े <w>': 36,
 'उ न क ो <w>': 15280,
 'आ श ी ष <w>': 347,
 'द ी <w>': 64733,
 'फ ू ल ो फ ल ो <w>': 6,
 'ज ा ओ <w>': 5200,
 'ब ढ ़ े ं त थ ा <w>': 1,
 'प ा ं च व ा ं <w>': 473,
 'प ् र ा ण ी <w>': 4010,
 'अ र ् थ ा त <w>': 7922,
 'घ र े ल ू <w>': 6606,
 'प श ु <w>': 4809,
 'र े ं ग न े <w>': 116,
 'ज न ् त ु <w>': 406,
 'व न प श ु <w>': 11,
 'उ त ् प न ् न <w>': 23289,
 'ग य ा स ो <w>': 7,
 'व न <w>': 7745,
 'प श ु ओ ं <w>': 3875,
 'ज न ् त ु ओ ं <w>': 423,
 'ह म <w>': 79844,
 'म न ु ष ् य <w>': 15579,
 'अ प न े <w>': 219981,
 'स ् व र ू प <w>': 10270,
 'स म ा न त ा <w>': 4333,
 'ब न ा ए ं <w>': 695,
 'म छ ल ि य ो ं <w>': 1493,
 'स ा र ी <w>': 7390,
 'र े ं ग त े <w>': 76,
 'अ ध ि क ा र <w>': 25396,
 'र ख े ं त ब <w>': 6,
 'न र <w>': 3984,
 'न ा र ी <w>': 1565,
 'म न ु ष ् य ो ं <w>': 4438,
 'व श <w>': 927,
 'क र <w>': 320473,
 'ल ो <w>': 6642,
 'ज न ् त ु ओ <w>': 17,
 'र ख ो फ ि र <w>': 2,
 'स ु न ो <w>': 883,
 'ज ि त न े <w>': 2652,
 'व ृ क ् ष ो ं <w>': 1830,
 'फ ल <w>': 7505,
 'म ै ं <w>': 62723,
 'त ु म <w>': 79373,
 'द ि ए <w>': 18412,
 'त ु म ् ह ा र े <w>': 29859,
 'भ ो ज न <w>': 11212,
 'ह ै ं औ र <w>': 383,
 'ज ी व न <w>': 48569,
 'प ् र ा ण <w>': 2925,
 'ख ा न े <w>': 5680,
 'ह र े <w>': 2642,
 'क ु छ <w>': 181633,
 'क ् य ा <w>': 61113,
 'व ह <w>': 212258,
 'छ ठ व ा ं <w>': 54,
 'ग य ा य ो ं <w>': 4,
 'उ न क ी <w>': 78581,
 'स े न ा <w>': 23904,
 'ब न ा न ा <w>': 6398,
 'स म ा प ् त <w>': 15498,
 'अ प न ा <w>': 43969,
 'क ा म <w>': 64827,
 'ज ि स े <w>': 45522,
 'क र त ा <w>': 107479,
 'स ा त व े ं <w>': 990,
 'क ि ए <w>': 47326,
 'ह ु ए <w>': 128606,
 'स ा र े <w>': 15444,
 'व ि श ् र ा म <w>': 1364,
 'प व ि त ् र <w>': 8245,
 'ठ ह र ा य ा <w>': 2096,
 'क ् य ो ं क ि <w>': 47415,
 'र च न ा <w>': 17345,
 'ल ि य ा आ क ा श <w>': 1,
 'उ त ् प त ् त ि <w>': 5639,
 'व ृ त ् त ा न ् त <w>': 324,
 'ज ब <w>': 119151,
 'ज ि स <w>': 35301,
 'य ह ो व ा <w>': 6414,
 'ब न ा य ा त ब <w>': 3,
 'म ै द ा न <w>': 7484,
 'क ो ई <w>': 113697,
 'प ौ ध ा <w>': 1571,
 'न <w>': 129474,
 'छ ो ट ा <w>': 9636,
 'उ ग ा <w>': 158,
 'न ह ी ं <w>': 357863,
 'ब र स ा य ा <w>': 555,
 'ख े त ी <w>': 6023,
 'थ ा त ौ भ ी <w>': 7,
 'क ो ह र ा <w>': 233,
 'उ ठ त ा <w>': 1438,
 'स ि ं च <w>': 10,
 'ज ा त ी <w>': 88831,
 'थ ी औ र <w>': 179,
 'आ द म <w>': 1320,
 'म ि ट ् ट ी <w>': 9556,
 'र च ा <w>': 837,
 'न थ न ो ं <w>': 24,
 'श ् व ा स <w>': 977,
 'फ ू ं क <w>': 198,
 'द ि य ा <w>': 179311,
 'ज ी व त ा <w>': 15,
 'ब न <w>': 34146,
 'प ू र ् व <w>': 66753,
 'ओ र <w>': 68431,
 'अ द न <w>': 217,
 'द े श <w>': 61202,
 'व ा ट ि क ा <w>': 162,
 'ल ग ा ई <w>': 1506,
 'व ह ा ं <w>': 16451,
 'र ख <w>': 8206,
 'द ि य ा औ र <w>': 223,
 'भ ा ं त ि <w>': 2411,
 'द े ख न े <w>': 12820,
 'म न ो ह र <w>': 849,
 'अ च ् छ े <w>': 11861,
 'उ ग ा ए <w>': 330,
 'भ ल े <w>': 3207,
 'य ा <w>': 258845,
 'ब ु र े <w>': 2302,
 'ज ् ञ ा न <w>': 21497,
 'ल ग ा य ा औ र <w>': 9,
 'स ी ं च न े <w>': 29,
 'म ह ा न द ी <w>': 527,
 'न ि क ल ी <w>': 1407,
 'आ ग े <w>': 29014,
 'ब ह क र <w>': 283,
 'च ा र <w>': 26179,
 'ध ा र ा <w>': 16567,
 'ग ई प ह ि ल ी <w>': 1,
 'न ा म <w>': 110500,
 'प ी श ो न <w>': 2,
 'व ह ी <w>': 20990,
 'ह व ी ल ा <w>': 7,
 'ज ह ा ं <w>': 28949,
 'स ो न ा <w>': 1929,
 'म ि ल त ा <w>': 16307,
 'घ े र े <w>': 2057,
 'ह ै उ स <w>': 135,
 'च ो ख ा <w>': 56,
 'म ो त ी <w>': 1124,
 'स ु ल ै म ा न ी <w>': 20,
 'प त ् थ र <w>': 8124,
 'म ि ल त े <w>': 8325,
 'द ू स र ी <w>': 21342,
 'न द ी <w>': 30043,
 'ग ी ह ो न <w>': 7,
 'क ू श <w>': 23,
 'त ी स र ी <w>': 4767,
 'ह ि द ् द े क े ल <w>': 2,
 'अ श ् श ू र <w>': 163,
 'ब ह त ी <w>': 3176,
 'च ौ थ ी <w>': 2438,
 'फ र ा त <w>': 26,
 'ह ै त ब <w>': 331,
 'ल े <w>': 41122,
 'क र े <w>': 14152,
 'उ स क ी <w>': 50972,
 'र क ् ष ा <w>': 11660,
 'क र े त ब <w>': 27,
 'आ ज ् ञ ा <w>': 3157,
 'त ू <w>': 10805,
 'ब ि न ा <w>': 22586,
 'ख ट क े <w>': 28,
 'ख ा <w>': 2377,
 'स क त ा <w>': 114370,
 'ह ै प र <w>': 81,
 'उ स क ा <w>': 39341,
 'क भ ी <w>': 31846,
 'ख ा न ा <w>': 4898,
 'ख ा ए <w>': 588,
 'उ स ी <w>': 29260,
 'अ व श ् य <w>': 6524,
 'म र <w>': 4467,
 'ज ा ए ग ा फ ि र <w>': 22,
 'अ क े ल ा <w>': 1910,
 'र ह न ा <w>': 6030,
 'स ह ा य क <w>': 12702,
 'ब न ा ऊ ं ग ा <w>': 45,
 'उ स स े <w>': 21489,
 'म े ल <w>': 8056,
 'ख ा ए औ र <w>': 4,
 'ब न ै ल े <w>': 26,
 'भ ा ँ त ि <w>': 2694,
 'र च क र <w>': 101,
 'प ा स <w>': 60423,
 'आ य ा <w>': 18974,
 'द े ख े ं <w>': 5991,
 'उ न क ा <w>': 47991,
 'र ख त ा <w>': 9654,
 'र ख े <w>': 6345,
 'प र न ् त ु <w>': 17350,
 'म ि ल ा <w>': 17360,
 'स क े त ब <w>': 9,
 'भ ा र ी <w>': 10772,
 'न ी न ् द <w>': 10,
 'ड ा ल <w>': 6851,
 'स ो <w>': 2629,
 'त ब <w>': 44567,
 'प स ल ी <w>': 77,
 'न ि क ा ल <w>': 5968,
 'स न ् त ी <w>': 84,
 'म ा ं स <w>': 3419,
 'न ि क ा ल ी <w>': 1396,
 'स ् त ् र ी <w>': 5413,
 'ब न ा <w>': 44321,
 'आ य ा औ र <w>': 39,
 'अ ब <w>': 53301,
 'म े र ी <w>': 16339,
 'ह ड ् ड ि य ो ं <w>': 1149,
 'ह ड ् ड ी <w>': 1471,
 'म े र े <w>': 23837,
 'इ स क ा <w>': 63251,
 'ह ो ग ा <w>': 45800,
 'ग ई <w>': 84863,
 'ह ै इ स <w>': 1179,
 'प ु र ू ष <w>': 1914,
 'म ा त ा <w>': 10275,
 'प ि त ा <w>': 20224,
 'छ ो ड ़ क र <w>': 7787,
 'प त ् न ी <w>': 9792,
 'र ह े ग ा <w>': 4489,
 'त न <w>': 573,
 'ब न े <w>': 20775,
 'र ह े ं ग े औ र <w>': 15,
 'द ो न ो <w>': 4559,
 'न ं ग े <w>': 328,
 'थ े <w>': 222499,
 'ल ज ा त े <w>': 4,
 'ब न ा ए <w>': 15240,
 'स र ् प <w>': 831,
 'ध ू र ् त <w>': 121,
 'स च <w>': 4170,
 'ब ा ट ि क ा <w>': 11,
 'क ि स ी <w>': 138092,
 'ख ा न ा स ् त ् र ी <w>': 2,
 'स क त े <w>': 68487,
 'ह ै ं प र <w>': 31,
 'व ि ष य <w>': 24465,
 'छ ू न ा <w>': 114,
 'ज ा ओ ग े त ब <w>': 4,
 'न ि श ् च य <w>': 10905,
 'म र ो ग े व र न <w>': 1,
 'आ प <w>': 56646,
 'ज ा न त ा <w>': 8303,
 'ख ा ओ ग े <w>': 69,
 'त ु म ् ह ा र ी <w>': 10011,
 'आ ं ख े ं <w>': 908,
 'ख ु ल <w>': 1275,
 'ज ा ए ं ग ी <w>': 666,
 'प ा क र <w>': 1450,
 'त ु ल ् य <w>': 700,
 'ज ा ओ ग े स ो <w>': 1,
 'म न भ ा ऊ <w>': 13,
 'ब ु द ् ध ि <w>': 4531,
 'च ा ह न े <w>': 507,
 'य ो ग ् य <w>': 10129,
 'त ो ड ़ क र <w>': 635,
 'ख ा य ा <w>': 1217,
 'प त ि <w>': 5378,
 'ख ा य ा त ब <w>': 7,
 'द ो न ो ं <w>': 59925,
 'आ ं ख े <w>': 238,
 'म ा ल ू म <w>': 5539,
 'उ न ् ह ो ं न े <w>': 102084,
 'अ ं ज ी र <w>': 281,
 'प त ् त े <w>': 1500,
 'ज ो ड ़ <w>': 4413,
 'ल ं ग ो ट <w>': 33,
 'ल ि य े त ब <w>': 2,
 'ठ ं ड े <w>': 936,
 'स म य <w>': 120827,
 'फ ि र त ा <w>': 232,
 'श ब ् द <w>': 34272,
 'स ु न ा ई <w>': 1939,
 'छ ि प <w>': 354,
 'ग ए त ब <w>': 91,
 'प ु क ा र <w>': 1369,
 'प ू छ ा <w>': 3761,
 'क ह ा ं <w>': 1750,
 'ह ै उ स न े <w>': 107,
 'त े र ा <w>': 2143,
 'ब ा र ी <w>': 1380,
 'स ु न <w>': 3444,
 'ड र <w>': 7288,
 'न ं ग ा <w>': 248,
 'ग य ा उ स न े <w>': 13,
 'क ि स <w>': 9631,
 'त ु झ े <w>': 3085,
 'च ि त ा य ा <w>': 17,
 'ब र ् ज ा <w>': 2,
 'ह ै आ द म <w>': 1,
 'स ं ग <w>': 2078,
 'र ह न े <w>': 20498,
 'म ु झ े <w>': 29196,
 'ब ह क ा <w>': 328,
 'अ ध ि क <w>': 110563,
 'श ा प ि त <w>': 129,
 'प े ट <w>': 3427,
 'ब ल <w>': 12680,
 'च ल ा <w>': 13879,
 'क र े ग ा <w>': 13745,
 'च ा ट त ा <w>': 7,
 'र ह े ग ा औ र <w>': 23,
 'त े र े <w>': 4829,
 'व ं श <w>': 10571,
 'इ स क े <w>': 122175,
 'ब ै र <w>': 266,
 'क र ु ं ग ा <w>': 90,
 'स ि र <w>': 7176,
 'क ु च ल <w>': 507,
 'ड ा ल े ग ा <w>': 391,
 'ए ड ़ ी <w>': 148,
 'ड स े ग ा फ ि र <w>': 1,
 'त े र ी <w>': 2708,
 'प ी ड ़ ा <w>': 1756,
 'ग र ् भ व त ी <w>': 1236,
 'ह ो न े <w>': 102317,
 'द ु ख <w>': 2547,
 'ब ढ ़ ा ऊ ं ग ा <w>': 18,
 'प ी ड ़ ि त <w>': 3171,
 'ब ा ल क <w>': 3626,
 'क र े ग ी <w>': 3116,
 'ल ा ल स ा <w>': 403,
 'ह ो ग ी <w>': 18048,
 'त ु झ <w>': 1144,
 'क र े ग ा औ र <w>': 39,
 'ब ा त <w>': 55996,
 'स ु न ी <w>': 1109,
 'उ स े <w>': 81357,
 'उ प ज <w>': 1931,
 'स ा थ <w>': 209562,
 'क ा ं ट े <w>': 189,
 'ऊ ं ट क ट ा र े <w>': 3,
 'उ ग ा ए ग ी <w>': 1,
 'ख े त <w>': 2204,
 'ख ा ए ग ा <w>': 100,
 'म ा थ े <w>': 503,
 'प स ी न े <w>': 257,
 'र ो ट ी <w>': 1466,
 'अ न ् त <w>': 4062,
 'म ि ल <w>': 16688,
 'ज ा ए ग ा <w>': 22243,
 'न ि क ा ल ा <w>': 4757,
 'ज ा ए ग ा औ र <w>': 94,
 'ह व ् व ा <w>': 60,
 'आ द ि म ा त ा <w>': 4,
 'ह ु ई औ र <w>': 36,
 'च म ड ़ े <w>': 1127,
 'अ ं ग र ख े <w>': 16,
 'प ह ि न ा <w>': 14,
 'द ि ए फ ि र <w>': 10,
 'स म ा न <w>': 23934,
 'ह ा थ <w>': 19412,
 'ब ढ ़ ा <w>': 5660,
 'त ो ड ़ <w>': 2681,
 'स द ा <w>': 4143,
 'र ह े त ब <w>': 28,
 'थ ा इ स ल ि य े <w>': 31,
 'म ा र ् ग <w>': 22482,
 'प ह र ा <w>': 186,
 'क र ु ब ो ं <w>': 3,
 'च ा र ो ं <w>': 8711,
 'घ ू म न े <w>': 1343,
 'ज ् व ा ल ा म य <w>': 5,
 'त ल व ा र <w>': 1916,
 'न ि य ु क ् त <w>': 9395,
 'द ि य ा ज ब <w>': 50,
 'क ै न <w>': 224,
 'ज न ् म <w>': 42903,
 'स ह ा य त ा <w>': 25459,
 'प ा य ा <w>': 18970,
 'भ ा ई <w>': 13696,
 'ह ा ब ि ल <w>': 19,
 'ज न ् म ी <w>': 447,
 'भ े ड ़ ब क र ि य ो ं <w>': 127,
 'च र व ा ह ा <w>': 115,
 'व ा ल ा <w>': 40660,
 'क ि स ा न <w>': 3694,
 'ब न ा क ु छ <w>': 1,
 'प श ् च ा त <w>': 9661,
 'भ े ं ट <w>': 3071,
 'क ई <w>': 94482,
 'प ह ि ल ौ ठ े <w>': 38,
 'ब च ् च े <w>': 12038,
 'च ढ ़ ा न े <w>': 539,
 'च र ् ब ी <w>': 370,
 'च ढ ़ ा ई <w>': 1833,
 'ग ् र ह ण <w>': 7907,
 'क ि य ा प र न ् त ु <w>': 26,
 'अ त ि <w>': 5463,
 'क ् र ो ध ि त <w>': 629,
 'म ु ं ह <w>': 3156,
 'उ द ा स ी <w>': 281,
 'छ ा <w>': 1054,
 'ग ई त ब <w>': 37,
 'क ् य ो ं <w>': 11409,
 'ह ै य द ि <w>': 240,
 'भ ल ा <w>': 2743,
 'ज ा ए ग ी <w>': 7968,
 'य द ि <w>': 53446,
 'प ा प <w>': 2215,
 'द ् व ा र <w>': 6074,
 'छ ि प ा <w>': 1281,
 'र ह त ा <w>': 24756,
 'क र े ग ा त ब <w>': 16,
 'च ढ ़ <w>': 1297,
 'घ ा त <w>': 1073,
 'क ि य ा त ब <w>': 84,
 'र ख व ा ल ा <w>': 89,
 'ह ू ं उ स न े <w>': 4,
 'ल ो ह ू <w>': 312,
 'च ि ल ् ल ा <w>': 243,
 'द ो ह ा ई <w>': 151,
 'र ह ा <w>': 90833,
 'ह ै इ स ल ि य े <w>': 138,
 'ज ि स न े <w>': 17563,
 'प ी न े <w>': 2665,
 'ख ो ल ा <w>': 2220,
 'ह ै च ा ह े <w>': 56,
 'त ौ भ ी <w>': 382,
 'प ू र ी <w>': 25582,
 'म ि ल े ग ी <w>': 1771,
 'ब ह े त ू <w>': 38,
 'भ ग ो ड ़ ा <w>': 63,
 'ह ो ग ा त ब <w>': 33,
 'म े र ा <w>': 10737,
 'द ण ् ड <w>': 1283,
 'स ह न े <w>': 439,
 'ब ा ह र <w>': 26754,
 'ह ै द े ख <w>': 29,
 'आ ज <w>': 34079,
 'द ृ ष ् ट ि <w>': 19300,
 'आ ड ़ <w>': 438,
 'म े <w>': 36126,
 'र ह ू ं ग ा <w>': 189,
 'प ा ए ग ा <w>': 761,
 'क र े ग ा इ स <w>': 8,
 'स ा त <w>': 10550,
 'ग ु ण ा <w>': 1473,
 'प ल ट ा <w>': 291,
 'ल ि य ा <w>': 67218,
 'च ि न ् ह <w>': 2257,
 'म ा र <w>': 7478,
 'ड ा ल े त ब <w>': 10,
 'स म ् म ु ख <w>': 1239,
 'न ि क ल <w>': 8137,
 'न ो द <w>': 3,
 'ल ग ा ज ब <w>': 26,
 'ह न ो क <w>': 24,
 'न ग र <w>': 37321,
 'ब स ा य ा <w>': 1047,
 'प ु त ् र <w>': 17017,
 'र ख ा औ र <w>': 34,
 'ई र ा द <w>': 2,
 'म ह ू य ा ए ल <w>': 2,
 'म त ू श ा ए ल <w>': 2,
 'ल े म े क <w>': 20,
 'स ् त ् र ि य ा ं <w>': 590,
 'ब ् य ा ह <w>': 434,
 'ल ी <w>': 18976,
 'आ द ा <w>': 14,
 'स ि ल ् ल ा <w>': 23,
 'य ा ब ा ल <w>': 1,
 'त म ् ब ु ओ ं <w>': 39,
 'ज ा न व र ो ं <w>': 4138,
 'प ा ल न <w>': 9548,
 'इ न <w>': 82776,
 'र ी त ि य ो ं <w>': 421,
 'उ त ् प ा द क <w>': 2039,
 'ह ु आ औ र <w>': 111,
 'य ू ब ा ल <w>': 1,
 'व ी ण ा <w>': 735,
 'ब ा ं स ु र ी <w>': 567,
 'ब ा ज ो ं <w>': 36,
 'ब ज ा न े <w>': 683,
 'र ी त ि <w>': 3422,
 'त ू ब ल ् क ै न <w>': 2,
 'प ी त ल <w>': 888,
 'ल ो ह े <w>': 2925,
 'ध ा र <w>': 945,
 'ह थ ि य ा र ो ं <w>': 1792,
 'ग ढ ़ न े <w>': 188,
 'ब ह ि न <w>': 427,
 'न ा म ा <w>': 144,
 'प त ् न ि य ो ं <w>': 795,
 'ह े <w>': 8509,
 'क ा न <w>': 3237,
 'ल ग ा ओ <w>': 196,
 'म ै ं न े <w>': 11815,
 'च ो ट <w>': 2987,
 'ल ग ा त ा <w>': 963,
 'ज व ा न <w>': 1137,
 'घ ा य ल <w>': 2649,
 'ह ै ज ब <w>': 304,
 'स त ् त र <w>': 652,
 'क ह <w>': 15124,
 'श े त <w>': 17,
 'ठ ह र ा <w>': 989,
 'ए न ो श <w>': 11,
 'ल ो ग <w>': 88281,
 'प ् र ा र ् थ न ा <w>': 4646,
 'ल ग े आ द म <w>': 1,
 'व ं श ा व ल ी <w>': 539,
 'ब न ा य ा उ स न े <w>': 3,
 'उ न ् ह े ं <w>': 96813,
 'र ख ा ज ब <w>': 8,
 'स ौ <w>': 6689,
 'त ी स <w>': 1787,
 'व र ् ष <w>': 85183,
 'द ् व ा र ा <w>': 215389,
 'आ ठ <w>': 7239,
 'ब े ट े <w>': 5605,
 'ब े ट ि य ा ं <w>': 301,
 'ह ु ई ं औ र <w>': 5,
 'क ु ल <w>': 26383,
 'अ व स ् थ ा <w>': 12442,
 'न ौ <w>': 4712,
 'त त ् प श ् च ा त <w>': 1132,
 'ग य ा ज ब <w>': 47,
 'प ा ं च <w>': 11508,
 'ब ा र ह <w>': 3447,
 'न ब ् ब े <w>': 384,
 'क े न ा न <w>': 17,
 'प न ् द ् र ह <w>': 461,
 'म ह ल ल े ल <w>': 13,
 'च ा ल ी स <w>': 1274,
 'द स <w>': 9486,
 'प ै ं स ठ <w>': 54,
 'य े र े द <w>': 11,
 'प ं च ा न व े <w>': 10,
 'ब ा स ठ <w>': 46,
 'म त ू श े ल ह <w>': 13,
 'त ी न <w>': 43933,
 'त क <w>': 186956,
 'च ल त ा <w>': 9725,
 'ल ो प <w>': 899,
 'उ ठ ा <w>': 5522,
 'ल ि य ा ज ब <w>': 13,
 'स त ् त ा स ी <w>': 8,
 'ब य ा स ी <w>': 22,
 'उ न ह त ् त र <w>': 15,
 'क ह क र <w>': 2202,
 'न ू ह <w>': 1839,
 'श ा प <w>': 811,
 'ल ड ़ क ा <w>': 1361,
 'ह म ा र े <w>': 33597,
 'क ठ ि न <w>': 7427,
 'प र ि श ् र म <w>': 1677,
 'क र त े <w>': 144696,
 'श ा न ् त ि <w>': 2075,
 'द े ग ा औ र <w>': 27,
 'स त ह त ् त र <w>': 9,
 'श े म <w>': 28,
 'ह ा म <w>': 61,
 'य े प े त <w>': 11,
 'द ि य ा फ ि र <w>': 44,
 'ब ढ ़ न े <w>': 4515,
 'ल ग े <w>': 23515,
 'उ न क े <w>': 135001,
 'ह ु ई त ब <w>': 18,
 'प ु त ् र ो ं <w>': 1769,
 'प ु त ् र ि य ो ं <w>': 280,
 'स ु न ् द र <w>': 3538,
 'च ा ह ा <w>': 1883,
 'ल ि य ा औ र <w>': 88,
 'ल ो ं <w>': 37,
 'व ि व ा द <w>': 6170,
 'श र ी र <w>': 23706,
 'आ य ु <w>': 9037,
 'ब ी स <w>': 2464,
 'ह ो ग ी उ न <w>': 2,
 'द ा न व <w>': 933,
 'र ह त े <w>': 24228,
 'ग ए <w>': 89993,
 'स न ् त ा न <w>': 2321,
 'श ू र व ी र <w>': 166,
 'ज ि न क ी <w>': 6319,
 'क ी र ् त ि <w>': 561,
 'प ् र ा च ी न <w>': 35405,
 'क ा ल <w>': 30024,
 'प ् र च ल ि त <w>': 11480,
 'ब ु र ा ई <w>': 2489,
 'ब ढ ़ <w>': 11768,
 'म न <w>': 14027,
 'व ि च ा र <w>': 24507,
 'न ि र न ् त र <w>': 1380,
 'ब ु र ा <w>': 4547,
 'ब न ा न े <w>': 29158,
 'प छ त ा य ा <w>': 24,
 'ख े द ि त <w>': 20,
 'ह ु आ त ब <w>': 43,
 'स ो च ा <w>': 2816,
 'ज ि स क ी <w>': 14672,
 'म ि ट ा <w>': 1241,
 'द ू ं ग ा <w>': 880,
 'प छ त ा त ा <w>': 16,
 'ह ू ं प र न ् त ु <w>': 14,
 'अ न ु ग ् र ह <w>': 1830,
 'ब न ी <w>': 18852,
 'र ह ी न ू ह <w>': 1,
 'ध र ् म ी <w>': 298,
 'ल ो ग ो ं <w>': 97545,
 'ख र ा <w>': 394,
 'र ह ा औ र <w>': 58,
 'ह ु ए उ स <w>': 1,
 'ब ि ग ड ़ <w>': 710,
 'उ प द ् र व <w>': 583,
 'ब ि ग ड ़ ी <w>': 68,
 'च ा ल <w>': 3000,
 'च ल न <w>': 1116,
 'ब ि ग ा ड ़ <w>': 1159,
 'थ ी त ब <w>': 48,
 'प ् र श ् न <w>': 8297,
 'स ा म ् ह न े <w>': 1202,
 'आ <w>': 33613,
 'स म े त <w>': 3281,
 'न ा श <w>': 1788,
 'ड ा ल ू ं ग ा इ स ल ि य े <w>': 1,
 'ग ो प े र <w>': 1,
 'ल क ड ़ ी <w>': 5118,
 'ज ह ा ज <w>': 4540,
 'क ो ठ र ि य ा ं <w>': 101,
 'भ ी त र <w>': 14650,
 'र ा ल <w>': 138,
 'ल ग ा न ा औ र <w>': 1,
 'ढ ं ग <w>': 8428,
 'ल म ् ब ा ई <w>': 2159,
 'च ौ ड ़ ा ई <w>': 2632,
 'प च ा स <w>': 1835,
 'ऊ ं च ा ई <w>': 5564,
 'ह ो ज ह ा ज <w>': 1,
 'ख ि ड ़ क ी <w>': 885,
 'छ त <w>': 3043,
 'अ ल ं ग <w>': 105,
 'र ख न ा <w>': 7739,
 'ख ण ् ड <w>': 1969,
 'ब न ा न ा औ र <w>': 2,
 'ज ल प ् र ल य <w>': 42,
 'ह ू ं <w>': 14260,
 'ज ा ए ं ग े प र न ् त ु <w>': 6,
 'व ा च ा <w>': 415,
 'ब ा न ् ध त ा <w>': 15,
 'ब ह ु ओ ं <w>': 28,
 'प ् र व े श <w>': 16997,
 'क र न ा औ र <w>': 65,
 'म ा द ा <w>': 3564,
 'ज ा <w>': 129865,
 'र ख न ा ए क <w>': 1,
 'आ ए ं ग े <w>': 380,
 'र ख े औ र <w>': 16,
 'भ ो ज ् य <w>': 349,
 'प द ा र ् थ <w>': 13143,
 'ज ा त ा <w>': 258233,
 'ह ो ग ा प र म े श ् व र <w>': 2,
 'घ र ा न े <w>': 1179,
 'क े व ल <w>': 52713,
 'त ु झ ी <w>': 97,
 'ह ै स ब <w>': 37,
 'श ु द ् ध <w>': 6459,
 'ल े न ा <w>': 7079,
 'म ा द ा औ र <w>': 1,
 'ब च क र <w>': 410,
 'र ह े क ् य ो ं क ि <w>': 17,
 'ब ी त न े <w>': 465,
 'ब र स ा त ा <w>': 185,
 'ज ि त न ी <w>': 3065,
 'व स ् त ु ए ं <w>': 1751,
 'द ू ं ग ा य ह ो व ा <w>': 4,
 'क ि य ा न ू ह <w>': 1,
 'छ <w>': 1705,
 'आ य ा न ू ह <w>': 1,
 'ब च न े <w>': 3199,
 'अ श ु द ् ध <w>': 885,
 'प क ् ष ि य ो ं औ र <w>': 2,
 'व ा ल ो ं <w>': 11265,
 'थ ी स ा त <w>': 1,
 'उ प र ा न ् त <w>': 1278,
 'प ् र ल य <w>': 635,
 'आ न े <w>': 21204,
 'स ौ व े ं <w>': 45,
 'द ू स र े <w>': 37554,
 'म ह ी न े <w>': 9767,
 'स त ् त र ह व ा ं <w>': 4,
 'ग ह ि र े <w>': 49,
 'स ो त े <w>': 640,
 'फ ू ट <w>': 1162,
 'न ि क ल े <w>': 2662,
 'झ र ो ख े <w>': 161,
 'ग ए औ र <w>': 179,
 'व र ् ष ा <w>': 7529,
 'ह ो त ी <w>': 111992,
 'र ह ी ठ ी क <w>': 1,
 'त ी न ो ं <w>': 5033,
 'स म े त औ र <w>': 2,
 'ग ए ज ि त न े <w>': 1,
 'ज ा त ि य ो ं <w>': 5357,
 'ब न ् द <w>': 3011,
 'प ा न ी <w>': 27712,
 'ब ढ ़ त ा <w>': 3240,
 'उ ठ न े <w>': 936,
 'ल ग ा <w>': 27923,
 'ऊ ं च ा <w>': 2140,
 'उ ठ <w>': 1849,
 'ब ढ ़ त े <w>': 3318,
 'त ै र त ा <w>': 207,
 'अ त ् य न ् त <w>': 6756,
 'य ह ा ं <w>': 39193,
 'ध र त ी <w>': 10746,
 'प ह ा ड ़ <w>': 3891,
 'ड ू ब <w>': 882,
 'ग ए ज ल <w>': 1,
 'च ल न े <w>': 6220,
 'ब ह ु त ा य त <w>': 1337,
 'ग ए ज ो <w>': 16,
 'स ् थ ल <w>': 11998,

In [25]:
from collections import defaultdict

def pair_freq(vocab):
  pairs = defaultdict(int)
  for word, freq in vocab.items():
    symbols = word.split()
    for i in range(len(symbols) - 1):
      pairs[(symbols[i], symbols[i + 1])] += freq
  return pairs

In [26]:
def merge_common(best, vocab):
  bigram = " ".join(best)
  replacement = "".join(best)
  new_vocab = {}
  for word in vocab:
    new_word = word.replace(bigram, replacement)
    new_vocab[new_word] = vocab[word]
  return new_vocab

In [29]:
num_merges = 100

for i in range(num_merges):
  pairs = pair_freq(vocab)
  # Find most frequent pair
  best = max(pairs, key=pairs.get)

  print(f"\nMerge {i+1}: {best} -> {''.join(best)}")

  # Merge pair
  vocab = merge_common(best, vocab)

  # Print updated vocab
  print(f"Iteration {i+1} completed!")

Merge 1: ('े', '<w>') -> े<w>
Iteration 1 completed!

Merge 2: ('ा', '<w>') -> ा<w>
Iteration 2 completed!

Merge 3: ('ी', '<w>') -> ी<w>
Iteration 3 completed!

Merge 4: ('ं', '<w>') -> ं<w>
Iteration 4 completed!

Merge 5: ('र', '<w>') -> र<w>
Iteration 5 completed!

Merge 6: ('क', 'े<w>') -> के<w>
Iteration 6 completed!

Merge 7: ('्', 'र') -> ्र
Iteration 7 completed!

Merge 8: ('ह', 'ै') -> है
Iteration 8 completed!

Merge 9: ('न', '<w>') -> न<w>
Iteration 9 completed!

Merge 10: ('े', 'ं<w>') -> ें<w>
Iteration 10 completed!

Merge 11: ('र', '्') -> र्
Iteration 11 completed!

Merge 12: ('क', '<w>') -> क<w>
Iteration 12 completed!

Merge 13: ('म', 'ें<w>') -> में<w>
Iteration 13 completed!

Merge 14: ('त', '<w>') -> त<w>
Iteration 14 completed!

Merge 15: ('ो', '<w>') -> ो<w>
Iteration 15 completed!

Merge 16: ('है', '<w>') -> है<w>
Iteration 16 completed!

Merge 17: ('्', 'य') -> ्य
Iteration 17 completed!

Merge 18: ('क', 'ी<w>') -> की<w>
Iteration 18 completed!

Merge 19: ('न', 'े<w>') -> ने<w>
Iteration 19 completed!

Merge 20: ('ो', 'ं<w>') -> ों<w>
Iteration 20 completed!

Merge 21: ('स', '्') -> स्
Iteration 21 completed!

Merge 22: ('ि', 'य') -> िय
Iteration 22 completed!

Merge 23: ('स', 'े<w>') -> से<w>
Iteration 23 completed!

Merge 24: ('प', '्र') -> प्र
Iteration 24 completed!

Merge 25: ('ा', 'र') -> ार
Iteration 25 completed!

Merge 26: ('क', 'ा<w>') -> का<w>
Iteration 26 completed!

Merge 27: ('ि', '<w>') -> ि<w>
Iteration 27 completed!

Merge 28: ('औ', 'र<w>') -> और<w>
Iteration 28 completed!

Merge 29: ('ल', '<w>') -> ल<w>
Iteration 29 completed!

Merge 30: ('त', 'ा<w>') -> ता<w>
Iteration 30 completed!

Merge 31: ('व', 'ि') -> वि
Iteration 31 completed!

Merge 32: ('स', '<w>') -> स<w>
Iteration 32 completed!

Merge 33: ('क', '्') -> क्
Iteration 33 completed!

Merge 34: ('म', '<w>') -> म<w>
Iteration 34 completed!

Merge 35: ('क', 'ो<w>') -> को<w>
Iteration 35 completed!

Merge 36: ('न', '्') -> न्
Iteration 36 completed!

Merge 37: ('ह', '<w>') -> ह<w>
Iteration 37 completed!

Merge 38: ('म', 'ा') -> मा
Iteration 38 completed!

Merge 39: ('र', 'ा') -> रा
Iteration 39 completed!

Merge 40: ('व', 'ा') -> वा
Iteration 40 completed!

Merge 41: ('ए', '<w>') -> ए<w>
Iteration 41 completed!

Merge 42: ('क', 'र') -> कर
Iteration 42 completed!

Merge 43: ('िय', 'ा<w>') -> िया<w>
Iteration 43 completed!

Merge 44: ('ज', 'ा') -> जा
Iteration 44 completed!

Merge 45: ('य', '<w>') -> य<w>
Iteration 45 completed!

Merge 46: ('स', 'ं') -> सं
Iteration 46 completed!

Merge 47: ('स', 'ा') -> सा
Iteration 47 completed!

Merge 48: ('न', 'ा<w>') -> ना<w>
Iteration 48 completed!

Merge 49: ('ल', 'ि') -> लि
Iteration 49 completed!

Merge 50: ('है', 'ं<w>') -> हैं<w>
Iteration 50 completed!

Merge 51: ('न', 'ि') -> नि
Iteration 51 completed!

Merge 52: ('ण', '<w>') -> ण<w>
Iteration 52 completed!

Merge 53: ('य', 'ा<w>') -> या<w>
Iteration 53 completed!

Merge 54: ('ग', '<w>') -> ग<w>
Iteration 54 completed!

Merge 55: ('ह', 'ो') -> हो
Iteration 55 completed!

Merge 56: ('त', '्') -> त्
Iteration 56 completed!

Merge 57: ('ए', 'क<w>') -> एक<w>
Iteration 57 completed!

Merge 58: ('ई', '<w>') -> ई<w>
Iteration 58 completed!

Merge 59: ('ि', 'त<w>') -> ित<w>
Iteration 59 completed!

Merge 60: ('क', 'ा') -> का
Iteration 60 completed!

Merge 61: ('त', 'े<w>') -> ते<w>
Iteration 61 completed!

Merge 62: ('न', 'ा') -> ना
Iteration 62 completed!

Merge 63: ('द', '<w>') -> द<w>
Iteration 63 completed!

Merge 64: ('प', 'र<w>') -> पर<w>
Iteration 64 completed!

Merge 65: ('क्', 'ष') -> क्ष
Iteration 65 completed!

Merge 66: ('थ', 'ा<w>') -> था<w>
Iteration 66 completed!

Merge 67: ('व', '<w>') -> व<w>
Iteration 67 completed!

Merge 68: ('ल', 'ा') -> ला
Iteration 68 completed!

Merge 69: ('द', '्') -> द्
Iteration 69 completed!

Merge 70: ('द', 'े') -> दे
Iteration 70 completed!

Merge 71: ('ड', '़') -> ड़
Iteration 71 completed!

Merge 72: ('ह', 'ा') -> हा
Iteration 72 completed!

Merge 73: ('क', 'ि<w>') -> कि<w>
Iteration 73 completed!

Merge 74: ('भ', 'ी<w>') -> भी<w>
Iteration 74 completed!

Merge 75: ('ज', 'ि') -> जि
Iteration 75 completed!

Merge 76: ('ब', 'ा') -> बा
Iteration 76 completed!

Merge 77: ('ट', '<w>') -> ट<w>
Iteration 77 completed!

Merge 78: ('ह', 'ु') -> हु
Iteration 78 completed!

Merge 79: ('त', 'ी<w>') -> ती<w>
Iteration 79 completed!

Merge 80: ('ि', 'क<w>') -> िक<w>
Iteration 80 completed!

Merge 81: ('प', 'ा') -> पा
Iteration 81 completed!

Merge 82: ('प', '<w>') -> प<w>
Iteration 82 completed!

Merge 83: ('क', 'ि') -> कि
Iteration 83 completed!

Merge 84: ('स', 'म') -> सम
Iteration 84 completed!

Merge 85: ('त', 'ि<w>') -> ति<w>
Iteration 85 completed!

Merge 86: ('ल', '्') -> ल्
Iteration 86 completed!

Merge 87: ('लि', 'ए<w>') -> लिए<w>
Iteration 87 completed!

Merge 88: ('ह', 'ी<w>') -> ही<w>
Iteration 88 completed!

Merge 89: ('त', 'ा') -> ता
Iteration 89 completed!

Merge 90: ('भ', 'ा') -> भा
Iteration 90 completed!

Merge 91: ('ी', 'ं<w>') -> ीं<w>
Iteration 91 completed!

Merge 92: ('न', 'ी<w>') -> नी<w>
Iteration 92 completed!

Merge 93: ('ष', '्') -> ष्
Iteration 93 completed!

Merge 94: ('ल', 'े<w>') -> ले<w>
Iteration 94 completed!

Merge 95: ('अ', 'प') -> अप
Iteration 95 completed!

Merge 96: ('स्', 'थ') -> स्थ
Iteration 96 completed!

Merge 97: ('ब', '<w>') -> ब<w>
Iteration 97 completed!

Merge 98: ('र', 'ू') -> रू
Iteration 98 completed!

Merge 99: ('श', '<w>') -> श<w>
Iteration 99 completed!

Merge 100: ('म', 'ि') -> मि
Iteration 100 completed!

In [30]:
vocab

{'आ द ि<w>': 61443,
 'में<w>': 2554180,
 'प र म े श ् व र<w>': 4963,
 'ने<w>': 487710,
 'आ का श<w>': 6063,
 'और<w>': 1693280,
 'प ृ थ ् व ी<w>': 17072,
 'की<w>': 1745880,
 'स ृ ष् ट ि<w>': 3166,
 'क ी और<w>': 74,
 'ब े ड ौ ल<w>': 31,
 'स ु न सा न<w>': 152,
 'प ड़ ी<w>': 4600,
 'थ ी<w>': 158145,
 'ग ह र े<w>': 3040,
 'ज ल<w>': 22395,
 'के<w>': 3460205,
 'ऊ पर<w>': 25846,
 'अ न् ध िय ारा<w>': 22,
 'था<w>': 389654,
 'त था<w>': 244962,
 'का<w>': 1291782,
 'आ त् मा<w>': 7881,
 'म ण ् ड ला ता<w>': 2,
 'थ ा त ब<w>': 126,
 'क हा<w>': 104936,
 'उ जिय ा ला<w>': 52,
 'हो<w>': 336138,
 'त ो<w>': 270637,
 'ग य ा और<w>': 290,
 'उ जिय ा ले<w>': 31,
 'को<w>': 1144583,
 'दे ख ा<w>': 24245,
 'कि<w>': 483936,
 'अ च ् छ ा<w>': 17177,
 'है<w>': 2567639,
 'अ न् ध िय ार े<w>': 45,
 'से<w>': 1407775,
 'अ ल ग<w>': 34163,
 'किय ा और<w>': 168,
 'द ि न<w>': 57802,
 'रा त<w>': 11809,
 'सा ं झ <w>': 166,
 'हु ई<w>': 83864,
 'फ ि र<w>': 82797,
 'भ ो र<w>': 414,
 'हु आ <w>': 143330,
 'इ स<w>': 395764,
 'प्र कार<w>': 102577,
 'प ह ि ला<w>': 91,
 'ग य ा फ ि र<w>': 43,
 'ब ी च <w>': 66414,
 'एक<w>': 792156,
 'ऐ सा<w>': 47496,
 'अ न् त र<w>': 4805,
 'द ो<w>': 98826,
 'भा ग<w>': 57403,
 'जा ए त ब<w>': 38,
 'कर के<w>': 32865,
 'उ स के<w>': 103089,
 'न ी च े<w>': 22953,
 'किया<w>': 472029,
 'व ै सा<w>': 2299,
 'ही<w>': 339524,
 'उ स<w>': 99004,
 'द ू स रा<w>': 15650,
 'स्थ ा न<w>': 51880,
 'इ क ट ् ठ ा<w>': 2863,
 'जा ए<w>': 25243,
 'स ू ख ी<w>': 1124,
 'भ ू मि<w>': 17175,
 'द ि ख ा ई<w>': 14837,
 'दे<w>': 37422,
 'ज ो<w>': 374975,
 'उ स को<w>': 10194,
 'उ स ने<w>': 43842,
 'सम ु द्र<w>': 11146,
 'है फ ि र<w>': 294,
 'ह र ी<w>': 1632,
 'घ ा स<w>': 2737,
 'ब ी ज <w>': 4412,
 'वा ले<w>': 100782,
 'छ ो ट े<w>': 20663,
 'प े ड़ <w>': 4534,
 'फ ल द ा ई<w>': 16,
 'व ृ क्ष <w>': 4897,
 'भी<w>': 518822,
 'जि न के<w>': 12527,
 'उ न् ही<w>': 736,
 'जा ति<w>': 13593,
 'अ न ु सार<w>': 64769,
 'हो ते<w>': 86654,
 'हैं<w>': 897087,
 'पर<w>': 681481,
 'उ ग ें<w>': 11,
 'ग य ा त ो<w>': 7,
 'जि न<w>': 16830,
 'अप नी<w>': 113919,
 'हो ता<w>': 181270,
 'उ ग े<w>': 89,
 'है त था<w>': 66,
 'त ी स रा<w>': 4433,
 'कर ने<w>': 276064,
 'लिय े<w>': 66649,
 'ज ्य ो त िय ा ं<w>': 11,
 'हों<w>': 17231,
 'व े<w>': 166212,
 'च ि न् हों<w>': 509,
 'निय त<w>': 3403,
 'सम य ों<w>': 324,
 'द ि न ों<w>': 15089,
 'व र् ष ों<w>': 26094,
 'कार ण<w>': 101399,
 'हो ं और<w>': 58,
 'प्र का श<w>': 16932,
 'दे ने<w>': 37007,
 'वा ल ी<w>': 51172,
 'ठ ह र ें<w>': 211,
 'ग य ा त ब<w>': 131,
 'ब ड़ ी<w>': 34359,
 'ब ना ई ं<w>': 247,
 'उ न<w>': 66115,
 'ज ्य ो ति<w>': 1550,
 'प्र भ ु ता<w>': 402,
 'छ ो ट ी<w>': 11605,
 'ब ना या<w>': 29978,
 'तारा ग ण<w>': 20,
 'ब ना य ा प र म े श ् व र<w>': 1,
 'इ स लिय े<w>': 4879,
 'र ख ा<w>': 29951,
 'दे ं त था<w>': 1,
 'कर ें<w>': 49902,
 'च ौ था<w>': 2092,
 'ज ी वित<w>': 7599,
 'प्रा ण िय ों<w>': 3402,
 'ब हु त<w>': 103996,
 'भ र<w>': 18317,
 'प क्ष ी<w>': 4076,
 'उ ड़ े ं इ स लिय े<w>': 1,
 'ब ड़ े<w>': 34791,
 'ज ल ज न् त ु ओ ं<w>': 2,
 'स ब<w>': 37911,
 'च ल ते<w>': 8165,
 'फ ि र ते<w>': 642,
 'ग या<w>': 331911,
 'उ ड़ ने<w>': 788,
 'प क्ष िय ों<w>': 2920,
 'है और<w>': 1402,
 'य ह<w>': 448592,
 'क ह के<w>': 36,
 'उ न को<w>': 15280,
 'आ श ी ष <w>': 347,
 'द ी<w>': 64733,
 'फ ू ल ो फ ल ो<w>': 6,
 'जा ओ <w>': 5200,
 'ब ढ ़ े ं त था<w>': 1,
 'पा ं च वा ं<w>': 473,
 'प्रा ण ी<w>': 4010,
 'अ र् थ ा त<w>': 7922,
 'घ र े ल ू <w>': 6606,
 'प श ु <w>': 4809,
 'र े ं ग ने<w>': 116,
 'ज न् त ु <w>': 406,
 'व न प श ु <w>': 11,
 'उ त् प न् न<w>': 23289,
 'ग य ा स ो<w>': 7,
 'व न<w>': 7745,
 'प श ु ओ ं<w>': 3875,
 'ज न् त ु ओ ं<w>': 423,
 'ह म<w>': 79844,
 'म न ु ष्य<w>': 15579,
 'अप ने<w>': 219981,
 'स् व रू प<w>': 10270,
 'समा न ता<w>': 4333,
 'ब ना ए ं<w>': 695,
 'म छ लिय ों<w>': 1493,
 'सार ी<w>': 7390,
 'र े ं ग ते<w>': 76,
 'अ ध ि कार<w>': 25396,
 'र ख े ं त ब<w>': 6,
 'न र<w>': 3984,
 'नार ी<w>': 1565,
 'म न ु ष्य ों<w>': 4438,
 'व श<w>': 927,
 'कर<w>': 320473,
 'ल ो<w>': 6642,
 'ज न् त ु ओ <w>': 17,
 'र ख ो फ ि र<w>': 2,
 'स ु न ो<w>': 883,
 'जि त ने<w>': 2652,
 'व ृ क्ष ों<w>': 1830,
 'फ ल<w>': 7505,
 'म ै ं<w>': 62723,
 'त ु म<w>': 79373,
 'द ि ए<w>': 18412,
 'त ु म ् हार े<w>': 29859,
 'भ ो ज न<w>': 11212,
 'है ं और<w>': 383,
 'ज ी व न<w>': 48569,
 'प्रा ण<w>': 2925,
 'ख ा ने<w>': 5680,
 'ह र े<w>': 2642,
 'क ु छ <w>': 181633,
 'क्या<w>': 61113,
 'व ह<w>': 212258,
 'छ ठ वा ं<w>': 54,
 'ग य ा य ों<w>': 4,
 'उ न की<w>': 78581,
 'स े ना<w>': 23904,
 'ब ना ना<w>': 6398,
 'समा प ् त<w>': 15498,
 'अप ना<w>': 43969,
 'का म<w>': 64827,
 'जि से<w>': 45522,
 'कर ता<w>': 107479,
 'सा त व ें<w>': 990,
 'कि ए<w>': 47326,
 'हु ए<w>': 128606,
 'सार े<w>': 15444,
 'वि श ्रा म<w>': 1364,
 'प वि त्र<w>': 8245,
 'ठ ह रा या<w>': 2096,
 'क्य ो ं कि<w>': 47415,
 'र च ना<w>': 17345,
 'लिय ा आ का श<w>': 1,
 'उ त् प त् ति<w>': 5639,
 'व ृ त् ता न् त<w>': 324,
 'ज ब<w>': 119151,
 'जि स<w>': 35301,
 'य हो वा<w>': 6414,
 'ब ना य ा त ब<w>': 3,
 'म ै द ा न<w>': 7484,
 'क ो ई<w>': 113697,
 'प ौ ध ा<w>': 1571,
 'न<w>': 129474,
 'छ ो ट ा<w>': 9636,
 'उ ग ा<w>': 158,
 'न ह ीं<w>': 357863,
 'ब र सा या<w>': 555,
 'ख े ती<w>': 6023,
 'थ ा त ौ भी<w>': 7,
 'क ो ह रा<w>': 233,
 'उ ठ ता<w>': 1438,
 'स ि ं च <w>': 10,
 'जा ती<w>': 88831,
 'थ ी और<w>': 179,
 'आ द म<w>': 1320,
 'मि ट ् ट ी<w>': 9556,
 'र च ा<w>': 837,
 'न थ न ों<w>': 24,
 'श ् वा स<w>': 977,
 'फ ू ं क<w>': 198,
 'द िया<w>': 179311,
 'ज ी व ता<w>': 15,
 'ब न<w>': 34146,
 'प ू र् व<w>': 66753,
 'ओ र<w>': 68431,
 'अ द न<w>': 217,
 'दे श<w>': 61202,
 'वा ट ि का<w>': 162,
 'ल ग ा ई<w>': 1506,
 'व हा ं<w>': 16451,
 'र ख <w>': 8206,
 'द िय ा और<w>': 223,
 'भा ं ति<w>': 2411,
 'दे ख ने<w>': 12820,
 'म न ो ह र<w>': 849,
 'अ च ् छ े<w>': 11861,
 'उ ग ा ए<w>': 330,
 'भ ले<w>': 3207,
 'या<w>': 258845,
 'ब ु र े<w>': 2302,
 'ज ् ञ ा न<w>': 21497,
 'ल ग ा य ा और<w>': 9,
 'स ी ं च ने<w>': 29,
 'म हा न द ी<w>': 527,
 'नि क ल ी<w>': 1407,
 'आ ग े<w>': 29014,
 'ब ह कर<w>': 283,
 'च ार<w>': 26179,
 'ध ारा<w>': 16567,
 'ग ई प ह ि ल ी<w>': 1,
 'ना म<w>': 110500,
 'प ी श ो न<w>': 2,
 'व ही<w>': 20990,
 'ह व ी ला<w>': 7,
 'ज हा ं<w>': 28949,
 'स ो ना<w>': 1929,
 'मि ल ता<w>': 16307,
 'घ े र े<w>': 2057,
 'है उ स<w>': 135,
 'च ो ख ा<w>': 56,
 'म ो ती<w>': 1124,
 'स ु ल ै मा नी<w>': 20,
 'प त् थ र<w>': 8124,
 'मि ल ते<w>': 8325,
 'द ू स र ी<w>': 21342,
 'न द ी<w>': 30043,
 'ग ी हो न<w>': 7,
 'क ू श<w>': 23,
 'त ी स र ी<w>': 4767,
 'ह ि द् दे क े ल<w>': 2,
 'अ श ् श ू र<w>': 163,
 'ब ह ती<w>': 3176,
 'च ौ थ ी<w>': 2438,
 'फ रा त<w>': 26,
 'है त ब<w>': 331,
 'ले<w>': 41122,
 'कर े<w>': 14152,
 'उ स की<w>': 50972,
 'र क्ष ा<w>': 11660,
 'कर े त ब<w>': 27,
 'आ ज ् ञ ा<w>': 3157,
 'त ू <w>': 10805,
 'ब ि ना<w>': 22586,
 'ख ट के<w>': 28,
 'ख ा<w>': 2377,
 'स क ता<w>': 114370,
 'है पर<w>': 81,
 'उ स का<w>': 39341,
 'क भी<w>': 31846,
 'ख ा ना<w>': 4898,
 'ख ा ए<w>': 588,
 'उ स ी<w>': 29260,
 'अ व श ्य<w>': 6524,
 'म र<w>': 4467,
 'जा ए ग ा फ ि र<w>': 22,
 'अ क े ला<w>': 1910,
 'र ह ना<w>': 6030,
 'स हा य क<w>': 12702,
 'ब ना ऊ ं ग ा<w>': 45,
 'उ स से<w>': 21489,
 'म े ल<w>': 8056,
 'ख ा ए और<w>': 4,
 'ब न ै ले<w>': 26,
 'भा ँ ति<w>': 2694,
 'र च कर<w>': 101,
 'पा स<w>': 60423,
 'आ या<w>': 18974,
 'दे ख ें<w>': 5991,
 'उ न का<w>': 47991,
 'र ख ता<w>': 9654,
 'र ख े<w>': 6345,
 'प र न् त ु <w>': 17350,
 'मि ला<w>': 17360,
 'स क े त ब<w>': 9,
 'भार ी<w>': 10772,
 'न ी न् द<w>': 10,
 'ड ा ल<w>': 6851,
 'स ो<w>': 2629,
 'त ब<w>': 44567,
 'प स ल ी<w>': 77,
 'नि का ल<w>': 5968,
 'स न् ती<w>': 84,
 'मा ं स<w>': 3419,
 'नि का ल ी<w>': 1396,
 'स् त्र ी<w>': 5413,
 'ब ना<w>': 44321,
 'आ य ा और<w>': 39,
 'अ ब<w>': 53301,
 'म े र ी<w>': 16339,
 'ह ड ् ड िय ों<w>': 1149,
 'ह ड ् ड ी<w>': 1471,
 'म े र े<w>': 23837,
 'इ स का<w>': 63251,
 'हो ग ा<w>': 45800,
 'ग ई<w>': 84863,
 'है इ स<w>': 1179,
 'प ु रू ष <w>': 1914,
 'मा ता<w>': 10275,
 'प ि ता<w>': 20224,
 'छ ो ड़ कर<w>': 7787,
 'प त् नी<w>': 9792,
 'र ह े ग ा<w>': 4489,
 'त न<w>': 573,
 'ब ने<w>': 20775,
 'र ह े ं ग े और<w>': 15,
 'द ो न ो<w>': 4559,
 'न ं ग े<w>': 328,
 'थ े<w>': 222499,
 'ल जा ते<w>': 4,
 'ब ना ए<w>': 15240,
 'स र् प<w>': 831,
 'ध ू र् त<w>': 121,
 'स च <w>': 4170,
 'बा ट ि का<w>': 11,
 'कि स ी<w>': 138092,
 'ख ा ना स् त्र ी<w>': 2,
 'स क ते<w>': 68487,
 'है ं पर<w>': 31,
 'वि ष य<w>': 24465,
 'छ ू ना<w>': 114,
 'जा ओ ग े त ब<w>': 4,
 'नि श ् च य<w>': 10905,
 'म र ो ग े व र न<w>': 1,
 'आ प<w>': 56646,
 'जा न ता<w>': 8303,
 'ख ा ओ ग े<w>': 69,
 'त ु म ् हार ी<w>': 10011,
 'आ ं ख ें<w>': 908,
 'ख ु ल<w>': 1275,
 'जा ए ं ग ी<w>': 666,
 'पा कर<w>': 1450,
 'त ु ल्य<w>': 700,
 'जा ओ ग े स ो<w>': 1,
 'म न भा ऊ <w>': 13,
 'ब ु द् ध ि<w>': 4531,
 'च ा ह ने<w>': 507,
 'य ो ग ्य<w>': 10129,
 'त ो ड़ कर<w>': 635,
 'ख ा या<w>': 1217,
 'प ति<w>': 5378,
 'ख ा य ा त ब<w>': 7,
 'द ो न ों<w>': 59925,
 'आ ं ख े<w>': 238,
 'मा ल ू म<w>': 5539,
 'उ न् हो ं ने<w>': 102084,
 'अ ं ज ी र<w>': 281,
 'प त् ते<w>': 1500,
 'ज ो ड़ <w>': 4413,
 'ल ं ग ो ट<w>': 33,
 'लिय े त ब<w>': 2,
 'ठ ं ड े<w>': 936,
 'सम य<w>': 120827,
 'फ ि र ता<w>': 232,
 'श ब ् द<w>': 34272,
 'स ु ना ई<w>': 1939,
 'छ ि प<w>': 354,
 'ग ए त ब<w>': 91,
 'प ु कार<w>': 1369,
 'प ू छ ा<w>': 3761,
 'क हा ं<w>': 1750,
 'है उ स ने<w>': 107,
 'त े रा<w>': 2143,
 'बार ी<w>': 1380,
 'स ु न<w>': 3444,
 'ड र<w>': 7288,
 'न ं ग ा<w>': 248,
 'ग य ा उ स ने<w>': 13,
 'कि स<w>': 9631,
 'त ु झ े<w>': 3085,
 'च ि ता या<w>': 17,
 'ब र् जा<w>': 2,
 'है आ द म<w>': 1,
 'सं ग<w>': 2078,
 'र ह ने<w>': 20498,
 'म ु झ े<w>': 29196,
 'ब ह का<w>': 328,
 'अ ध िक<w>': 110563,
 'श ा प ित<w>': 129,
 'प े ट<w>': 3427,
 'ब ल<w>': 12680,
 'च ला<w>': 13879,
 'कर े ग ा<w>': 13745,
 'च ा ट ता<w>': 7,
 'र ह े ग ा और<w>': 23,
 'त े र े<w>': 4829,
 'व ं श<w>': 10571,
 'इ स के<w>': 122175,
 'ब ै र<w>': 266,
 'कर ु ं ग ा<w>': 90,
 'स ि र<w>': 7176,
 'क ु च ल<w>': 507,
 'ड ा ल े ग ा<w>': 391,
 'ए ड़ ी<w>': 148,
 'ड स े ग ा फ ि र<w>': 1,
 'त े र ी<w>': 2708,
 'प ी ड़ ा<w>': 1756,
 'ग र् भ व ती<w>': 1236,
 'हो ने<w>': 102317,
 'द ु ख <w>': 2547,
 'ब ढ ़ ा ऊ ं ग ा<w>': 18,
 'प ी ड़ ित<w>': 3171,
 'बा ल क<w>': 3626,
 'कर े ग ी<w>': 3116,
 'ला ल सा<w>': 403,
 'हो ग ी<w>': 18048,
 'त ु झ <w>': 1144,
 'कर े ग ा और<w>': 39,
 'बा त<w>': 55996,
 'स ु नी<w>': 1109,
 'उ से<w>': 81357,
 'उ प ज <w>': 1931,
 'सा थ <w>': 209562,
 'का ं ट े<w>': 189,
 'ऊ ं ट क ट ार े<w>': 3,
 'उ ग ा ए ग ी<w>': 1,
 'ख े त<w>': 2204,
 'ख ा ए ग ा<w>': 100,
 'मा थ े<w>': 503,
 'प स ी ने<w>': 257,
 'र ो ट ी<w>': 1466,
 'अ न् त<w>': 4062,
 'मि ल<w>': 16688,
 'जा ए ग ा<w>': 22243,
 'नि का ला<w>': 4757,
 'जा ए ग ा और<w>': 94,
 'ह व ् वा<w>': 60,
 'आ द ि मा ता<w>': 4,
 'हु ई और<w>': 36,
 'च म ड़ े<w>': 1127,
 'अ ं ग र ख े<w>': 16,
 'प ह ि ना<w>': 14,
 'द ि ए फ ि र<w>': 10,
 'समा न<w>': 23934,
 'हा थ <w>': 19412,
 'ब ढ ़ ा<w>': 5660,
 'त ो ड़ <w>': 2681,
 'स द ा<w>': 4143,
 'र ह े त ब<w>': 28,
 'थ ा इ स लिय े<w>': 31,
 'मार् ग<w>': 22482,
 'प ह रा<w>': 186,
 'कर ु ब ों<w>': 3,
 'च ार ों<w>': 8711,
 'घ ू म ने<w>': 1343,
 'ज ् वा ला म य<w>': 5,
 'त ल वार<w>': 1916,
 'निय ु क् त<w>': 9395,
 'द िय ा ज ब<w>': 50,
 'क ै न<w>': 224,
 'ज न् म<w>': 42903,
 'स हा य ता<w>': 25459,
 'पा या<w>': 18970,
 'भा ई<w>': 13696,
 'हा ब ि ल<w>': 19,
 'ज न् म ी<w>': 447,
 'भ े ड़ ब कर िय ों<w>': 127,
 'च र वा हा<w>': 115,
 'वा ला<w>': 40660,
 'कि सा न<w>': 3694,
 'ब ना क ु छ <w>': 1,
 'प श ् च ा त<w>': 9661,
 'भ े ं ट<w>': 3071,
 'क ई<w>': 94482,
 'प ह ि ल ौ ठ े<w>': 38,
 'ब च ् च े<w>': 12038,
 'च ढ ़ ा ने<w>': 539,
 'च र् ब ी<w>': 370,
 'च ढ ़ ा ई<w>': 1833,
 'ग ्र ह ण<w>': 7907,
 'किय ा प र न् त ु <w>': 26,
 'अ ति<w>': 5463,
 'क्र ो ध ित<w>': 629,
 'म ु ं ह<w>': 3156,
 'उ द ा स ी<w>': 281,
 'छ ा<w>': 1054,
 'ग ई त ब<w>': 37,
 'क्य ों<w>': 11409,
 'है य द ि<w>': 240,
 'भ ला<w>': 2743,
 'जा ए ग ी<w>': 7968,
 'य द ि<w>': 53446,
 'पा प<w>': 2215,
 'द् वार<w>': 6074,
 'छ ि पा<w>': 1281,
 'र ह ता<w>': 24756,
 'कर े ग ा त ब<w>': 16,
 'च ढ ़ <w>': 1297,
 'घ ा त<w>': 1073,
 'किय ा त ब<w>': 84,
 'र ख वा ला<w>': 89,
 'ह ू ं उ स ने<w>': 4,
 'ल ो ह ू <w>': 312,
 'च ि ल् ला<w>': 243,
 'द ो हा ई<w>': 151,
 'र हा<w>': 90833,
 'है इ स लिय े<w>': 138,
 'जि स ने<w>': 17563,
 'प ी ने<w>': 2665,
 'ख ो ला<w>': 2220,
 'है च ा ह े<w>': 56,
 'त ौ भी<w>': 382,
 'प ू र ी<w>': 25582,
 'मि ल े ग ी<w>': 1771,
 'ब ह े त ू <w>': 38,
 'भ ग ो ड़ ा<w>': 63,
 'हो ग ा त ब<w>': 33,
 'म े रा<w>': 10737,
 'द ण ् ड <w>': 1283,
 'स ह ने<w>': 439,
 'बा ह र<w>': 26754,
 'है दे ख <w>': 29,
 'आ ज <w>': 34079,
 'द ृ ष् ट ि<w>': 19300,
 'आ ड़ <w>': 438,
 'म े<w>': 36126,
 'र ह ू ं ग ा<w>': 189,
 'पा ए ग ा<w>': 761,
 'कर े ग ा इ स<w>': 8,
 'सा त<w>': 10550,
 'ग ु ण ा<w>': 1473,
 'प ल ट ा<w>': 291,
 'लिया<w>': 67218,
 'च ि न् ह<w>': 2257,
 'मार<w>': 7478,
 'ड ा ल े त ब<w>': 10,
 'सम ् म ु ख <w>': 1239,
 'नि क ल<w>': 8137,
 'न ो द<w>': 3,
 'ल ग ा ज ब<w>': 26,
 'ह न ो क<w>': 24,
 'न ग र<w>': 37321,
 'ब सा या<w>': 1047,
 'प ु त्र<w>': 17017,
 'र ख ा और<w>': 34,
 'ई रा द<w>': 2,
 'म ह ू य ा ए ल<w>': 2,
 'म त ू श ा ए ल<w>': 2,
 'ल े म े क<w>': 20,
 'स् त्र िय ा ं<w>': 590,
 'ब ्य ा ह<w>': 434,
 'ल ी<w>': 18976,
 'आ द ा<w>': 14,
 'स ि ल् ला<w>': 23,
 'य ा बा ल<w>': 1,
 'त म ् ब ु ओ ं<w>': 39,
 'जा न व र ों<w>': 4138,
 'पा ल न<w>': 9548,
 'इ न<w>': 82776,
 'र ी त िय ों<w>': 421,
 'उ त् पा द क<w>': 2039,
 'हु आ और<w>': 111,
 'य ू बा ल<w>': 1,
 'व ी ण ा<w>': 735,
 'बा ं स ु र ी<w>': 567,
 'बा ज ों<w>': 36,
 'ब जा ने<w>': 683,
 'र ी ति<w>': 3422,
 'त ू ब ल् क ै न<w>': 2,
 'प ी त ल<w>': 888,
 'ल ो ह े<w>': 2925,
 'ध ार<w>': 945,
 'ह थ िय ार ों<w>': 1792,
 'ग ढ ़ ने<w>': 188,
 'ब ह ि न<w>': 427,
 'ना मा<w>': 144,
 'प त् निय ों<w>': 795,
 'ह े<w>': 8509,
 'का न<w>': 3237,
 'ल ग ा ओ <w>': 196,
 'म ै ं ने<w>': 11815,
 'च ो ट<w>': 2987,
 'ल ग ा ता<w>': 963,
 'ज वा न<w>': 1137,
 'घ ा य ल<w>': 2649,
 'है ज ब<w>': 304,
 'स त् त र<w>': 652,
 'क ह<w>': 15124,
 'श े त<w>': 17,
 'ठ ह रा<w>': 989,
 'ए न ो श<w>': 11,
 'ल ो ग<w>': 88281,
 'प्रार् थ ना<w>': 4646,
 'ल ग े आ द म<w>': 1,
 'व ं श ा व ल ी<w>': 539,
 'ब ना य ा उ स ने<w>': 3,
 'उ न् ह ें<w>': 96813,
 'र ख ा ज ब<w>': 8,
 'स ौ <w>': 6689,
 'त ी स<w>': 1787,
 'व र् ष <w>': 85183,
 'द् वारा<w>': 215389,
 'आ ठ <w>': 7239,
 'ब े ट े<w>': 5605,
 'ब े ट िय ा ं<w>': 301,
 'हु ई ं और<w>': 5,
 'क ु ल<w>': 26383,
 'अ व स्था<w>': 12442,
 'न ौ <w>': 4712,
 'त त् प श ् च ा त<w>': 1132,
 'ग य ा ज ब<w>': 47,
 'पा ं च <w>': 11508,
 'बार ह<w>': 3447,
 'न ब ् ब े<w>': 384,
 'क े ना न<w>': 17,
 'प न् द्र ह<w>': 461,
 'म ह ल ल े ल<w>': 13,
 'च ा ल ी स<w>': 1274,
 'द स<w>': 9486,
 'प ै ं स ठ <w>': 54,
 'य े र े द<w>': 11,
 'प ं च ा न व े<w>': 10,
 'बा स ठ <w>': 46,
 'म त ू श े ल ह<w>': 13,
 'त ी न<w>': 43933,
 'त क<w>': 186956,
 'च ल ता<w>': 9725,
 'ल ो प<w>': 899,
 'उ ठ ा<w>': 5522,
 'लिय ा ज ब<w>': 13,
 'स त् ता स ी<w>': 8,
 'ब य ा स ी<w>': 22,
 'उ न ह त् त र<w>': 15,
 'क ह कर<w>': 2202,
 'न ू ह<w>': 1839,
 'श ा प<w>': 811,
 'ल ड़ का<w>': 1361,
 'ह मार े<w>': 33597,
 'क ठ ि न<w>': 7427,
 'प र ि श ्र म<w>': 1677,
 'कर ते<w>': 144696,
 'श ा न् ति<w>': 2075,
 'दे ग ा और<w>': 27,
 'स त ह त् त र<w>': 9,
 'श े म<w>': 28,
 'हा म<w>': 61,
 'य े प े त<w>': 11,
 'द िय ा फ ि र<w>': 44,
 'ब ढ ़ ने<w>': 4515,
 'ल ग े<w>': 23515,
 'उ न के<w>': 135001,
 'हु ई त ब<w>': 18,
 'प ु त्र ों<w>': 1769,
 'प ु त्र िय ों<w>': 280,
 'स ु न् द र<w>': 3538,
 'च ा हा<w>': 1883,
 'लिय ा और<w>': 88,
 'ल ों<w>': 37,
 'वि वा द<w>': 6170,
 'श र ी र<w>': 23706,
 'आ य ु <w>': 9037,
 'ब ी स<w>': 2464,
 'हो ग ी उ न<w>': 2,
 'द ा न व<w>': 933,
 'र ह ते<w>': 24228,
 'ग ए<w>': 89993,
 'स न् ता न<w>': 2321,
 'श ू र व ी र<w>': 166,
 'जि न की<w>': 6319,
 'क ी र् ति<w>': 561,
 'प्रा च ी न<w>': 35405,
 'का ल<w>': 30024,
 'प्र च लित<w>': 11480,
 'ब ु रा ई<w>': 2489,
 'ब ढ ़ <w>': 11768,
 'म न<w>': 14027,
 'वि च ार<w>': 24507,
 'नि र न् त र<w>': 1380,
 'ब ु रा<w>': 4547,
 'ब ना ने<w>': 29158,
 'प छ ता या<w>': 24,
 'ख े द ित<w>': 20,
 'हु आ त ब<w>': 43,
 'स ो च ा<w>': 2816,
 'जि स की<w>': 14672,
 'मि ट ा<w>': 1241,
 'द ू ं ग ा<w>': 880,
 'प छ ता ता<w>': 16,
 'ह ू ं प र न् त ु <w>': 14,
 'अ न ु ग ्र ह<w>': 1830,
 'ब नी<w>': 18852,
 'र ह ी न ू ह<w>': 1,
 'ध र् म ी<w>': 298,
 'ल ो ग ों<w>': 97545,
 'ख रा<w>': 394,
 'र हा और<w>': 58,
 'हु ए उ स<w>': 1,
 'ब ि ग ड़ <w>': 710,
 'उ प द्र व<w>': 583,
 'ब ि ग ड़ ी<w>': 68,
 'च ा ल<w>': 3000,
 'च ल न<w>': 1116,
 'ब ि ग ा ड़ <w>': 1159,
 'थ ी त ब<w>': 48,
 'प्र श ् न<w>': 8297,
 'सा म ् ह ने<w>': 1202,
 'आ <w>': 33613,
 'सम े त<w>': 3281,
 'ना श<w>': 1788,
 'ड ा ल ू ं ग ा इ स लिय े<w>': 1,
 'ग ो प े र<w>': 1,
 'ल क ड़ ी<w>': 5118,
 'ज हा ज <w>': 4540,
 'क ो ठ र िय ा ं<w>': 101,
 'भ ी त र<w>': 14650,
 'रा ल<w>': 138,
 'ल ग ा ना और<w>': 1,
 'ढ ं ग<w>': 8428,
 'ल म ् बा ई<w>': 2159,
 'च ौ ड़ ा ई<w>': 2632,
 'प च ा स<w>': 1835,
 'ऊ ं च ा ई<w>': 5564,
 'हो ज हा ज <w>': 1,
 'ख ि ड़ की<w>': 885,
 'छ त<w>': 3043,
 'अ ल ं ग<w>': 105,
 'र ख ना<w>': 7739,
 'ख ण ् ड <w>': 1969,
 'ब ना ना और<w>': 2,
 'ज ल प्र ल य<w>': 42,
 'ह ू ं<w>': 14260,
 'जा ए ं ग े प र न् त ु <w>': 6,
 'वा च ा<w>': 415,
 'बा न् ध ता<w>': 15,
 'ब हु ओ ं<w>': 28,
 'प्र व े श<w>': 16997,
 'कर ना और<w>': 65,
 'मा द ा<w>': 3564,
 'जा<w>': 129865,
 'र ख ना एक<w>': 1,
 'आ ए ं ग े<w>': 380,
 'र ख े और<w>': 16,
 'भ ो ज ्य<w>': 349,
 'प द ार् थ <w>': 13143,
 'जा ता<w>': 258233,
 'हो ग ा प र म े श ् व र<w>': 2,
 'घ रा ने<w>': 1179,
 'क े व ल<w>': 52713,
 'त ु झ ी<w>': 97,
 'है स ब<w>': 37,
 'श ु द् ध <w>': 6459,
 'ल े ना<w>': 7079,
 'मा द ा और<w>': 1,
 'ब च कर<w>': 410,
 'र ह े क्य ो ं कि<w>': 17,
 'ब ी त ने<w>': 465,
 'ब र सा ता<w>': 185,
 'जि त नी<w>': 3065,
 'व स् त ु ए ं<w>': 1751,
 'द ू ं ग ा य हो वा<w>': 4,
 'किय ा न ू ह<w>': 1,
 'छ <w>': 1705,
 'आ य ा न ू ह<w>': 1,
 'ब च ने<w>': 3199,
 'अ श ु द् ध <w>': 885,
 'प क्ष िय ो ं और<w>': 2,
 'वा ल ों<w>': 11265,
 'थ ी सा त<w>': 1,
 'उ प रा न् त<w>': 1278,
 'प्र ल य<w>': 635,
 'आ ने<w>': 21204,
 'स ौ व ें<w>': 45,
 'द ू स र े<w>': 37554,
 'म ह ी ने<w>': 9767,
 'स त् त र ह वा ं<w>': 4,
 'ग ह ि र े<w>': 49,
 'स ो ते<w>': 640,
 'फ ू ट<w>': 1162,
 'नि क ले<w>': 2662,
 'झ र ो ख े<w>': 161,
 'ग ए और<w>': 179,
 'व र् ष ा<w>': 7529,
 'हो ती<w>': 111992,
 'र ह ी ठ ी क<w>': 1,
 'त ी न ों<w>': 5033,
 'सम े त और<w>': 2,
 'ग ए जि त ने<w>': 1,
 'जा त िय ों<w>': 5357,
 'ब न् द<w>': 3011,
 'पा नी<w>': 27712,
 'ब ढ ़ ता<w>': 3240,
 'उ ठ ने<w>': 936,
 'ल ग ा<w>': 27923,
 'ऊ ं च ा<w>': 2140,
 'उ ठ <w>': 1849,
 'ब ढ ़ ते<w>': 3318,
 'त ै र ता<w>': 207,
 'अ त्य न् त<w>': 6756,
 'य हा ं<w>': 39193,
 'ध र ती<w>': 10746,
 'प हा ड़ <w>': 3891,
 'ड ू ब<w>': 882,
 'ग ए ज ल<w>': 1,
 'च ल ने<w>': 6220,
 'ब हु ता य त<w>': 1337,
 'ग ए ज ो<w>': 16,
 'स्थ ल<w>': 11998,
 'जि त न ों<w>': 26,
 'मि ट े और<w>': 2,
 'मि ट<w>': 615,
 'ब च <w>': 2884,
 'प्र ब ल<w>': 2860,
 'स भ ों<w>': 241,
 'स ु ध ि<w>': 122,
 'प व न<w>': 1384,
 'ब हा ई<w>': 421,
 'घ ट ने<w>': 471,
 'ल ग ा और<w>': 48,
 'ब ं द<w>': 13158,
 'थ म<w>': 171,
 'ग ई और<w>': 67,
 'प श च ा त<w>': 6,
 'ल ग ा तार<w>': 8239,
 'ल ग ा सा त व ें<w>': 1,
 'स त् त र ह व ें<w>': 1,
 'अ रारा त<w>': 5,
 'ट िक<w>': 624,
 'द स व ें<w>': 721,
 'घ ट ता<w>': 411,
 'प ह ि ले<w>': 741,
 'प हा ड़ ों<w>': 2505,
 'च ो ट िय ा ँ <w>': 240,
 'द ि ख ला ई<w>': 576,
 'द ी ं फ ि र<w>': 5,
 'ख ो ल<w>': 3949,
 'क ौ आ <w>': 104,
 'उ ड़ ा<w>': 865,
 'द िय ा व ह<w>': 8,
 'स ू ख <w>': 639,
 'इ ध र<w>': 1494,
 'उ ध र<w>': 1610,
 'र हा फ ि र<w>': 6,
 'क ब ू त र ी<w>': 26,
 'घ ट<w>': 1310,
 'न ह ी ं उ स<w>': 15,
 'प ै र<w>': 3535,
 'त ले<w>': 833,
 'ट े क ने<w>': 93,
 'आ ध ार<w>': 41065,
 'ल ौ ट<w>': 5161,
 'आ ई<w>': 14453,
 'छ ा या<w>': 2783,
 'लिय ा त ब<w>': 35,
 'ठ ह र<w>': 503,
 'च ो ं च <w>': 442,
 'ज ल पा ई<w>': 44,
 'न या<w>': 14228,
 'प त् ता<w>': 509,
 'जा न<w>': 9753,
 'ठ ह र कर<w>': 47,
 'आ ई फ ि र<w>': 1,
 'स ता ई स व ें<w>': 2,
 'क हा त ू <w>': 8,
 'आ क्या<w>': 1,
 'श र ी र ध ार ी<w>': 34,
 'ज ी व ज न् त ु <w>': 122,
 'फ ू ल े ं फ ल ें<w>': 2,
 'फ ै ल<w>': 3234,
 'जा ए ं त ब<w>': 20,
 'ब हु ए ं<w>': 30,
 'आ ई ं और<w>': 8,
 'च ौ पा ए<w>': 207,
 'आ ए त ब<w>': 33,
 'व े द ी<w>': 876,
 'ब ना ई<w>': 9587,
 'हो म ब लि<w>': 247,
 'च ढ ़ ा य ा इ स<w>': 1,
 'स ु ख द ा य क<w>': 92,
 'स ु ग न् ध <w>': 156,
 'य द्य प ि<w>': 11696,
 'ब च प न<w>': 4400,
 'ज ै सा<w>': 16676,
 'ज ी व ों<w>': 5300,
 'मारा<w>': 2941,
 'मारू ं ग ा अ ब<w>': 1,
 'र ह े ग ी<w>': 2188,
 'ब ो ने<w>': 259,
 'का ट ने<w>': 1800,
 'ठ ण ् ड <w>': 193,
 'त प न<w>': 59,

In [31]:
bpe_set = set()

for word in vocab.keys():
  bpe_set.update(word.split())

print(bpe_set)

{'रारा', 'म', 'से<w>', 'हार', 'कार<w>', 'र्र्र्', 'न्र्रा', 'भार', 'ला<w>', 'ॅ', 'मारारा', 'ॎ', 'है', 'कि<w>', 'ष्या<w>', 'द्य<w>', 'को<w>', 'ॼ', 'कारार<w>', 'क्रा', 'सम<w>', 'क्य', 'अप्रार', 'द्रार्', 'ऒ', 'प्र', 'म<w>', 'ृ', 'वार', 'क़', 'त्र्या<w>', 'ो', 'भार्य<w>', 'प्रार्', 'ओ', 'त्रारा', 'क', 'ट<w>', 'बार्र<w>', 'लि<w>', 'समें<w>', 'कित<w>', '7', 'अप<w>', 'समित<w>', 'कारार्', 'प्रारा', 'ॠ', 'कर्र<w>', 'ीं<w>', 'ें<w>', 'करा<w>', 'ज़', 'ऍ', 'द्र', 'मारा', 'मार्रा', 'न्', 'करार<w>', 'अपारा<w>', 'हु', 'े<w>', 'हार्र', 'व', 'कर्रू', 'जिक<w>', 'सार्रा<w>', 'ए', 'ऻ', 'ड़', 'क्ष्य<w>', 'अपा<w>', 'ई<w>', 'पार्य', 'द्र्य', 'क्रार<w>', 'समार', 'उ', 'त<w>', 'तारारा', 'भारार्', 'बारारा<w>', 'त्र्', 'क्र्य', 'ता', '6', 'ल्र<w>', 'ऺ', 'कार्य', 'य', 'क्ष्रा<w>', 'न', 'ते<w>', 'नार्रा<w>', 'श', 'ऽ', 'क्र्र्र्र्', 'ष्र<w>', 'ू', 'क्रार्य', 'स्रार', 'र्य<w>', 'स्रार<w>', 'किक<w>', 'नारू', 'वि<w>', 'अपा', 'र्रार्', 'र्रारा', 'स्र्', 'मार', '्रा<w>', 'कर्य<w>', 'कारारा', 'त्', 'ि<w>', 'समि', 'मि<w>', 'ऩ', 'निया<w>', 'कार', 'सार', 'ङ', 'वारार', 'झ', 'अप्रार्', 'वार्', 'द्रारू', 'प्र्', 'क्ष्र', 'प्र्य<w>', 'ह', 'ठ', 'ट', 'हार<w>', 'ॉ', 'प<w>', 'क्र्य<w>', 'रारू', 'त्र', 'ों<w>', 'ो<w>', 'का', 'ऑ', '्र्र्र्र', 'ँ', '्रार', 'क्ष्या<w>', '3', '्र्र्र', 'र्रा', '्', 'कर्य', 'वारारा', 'पार', 'सं<w>', 'अ', 'तारा', 'द्य', 'हारा', 'मारार<w>', 'ारार्', 'स्र्र', 'भारार', 'नी<w>', '्या<w>', 'अप्रू', 'कार्र', 'र्रारा<w>', 'तारू', 'ार्य<w>', 'भार्य', 'बारा', 'न्रू', 'ल्रू', 'िक<w>', 'न्र्या<w>', 'तार्य<w>', 'द्रारा<w>', '्र्र्र्र<w>', 'लारू', 'वारा<w>', 'सार्र', 'न्रार', 'नारा<w>', 'लिक<w>', 'समारा', 'करारा', 'ए<w>', 'वार्रा', 'जा<w>', 'तार्', 'करार्य<w>', 'ार्य', 'लिया<w>', 'अप्र', 'ः', 'द्रार<w>', 'न्रा<w>', 'दें<w>', 'ष्', 'ल्रा<w>', 'मारार', 'द्रू', 'स्रार्', 'ण', 'विक<w>', 'ऊ', 'न्र्', 'ड', 'ार्र', 'त', 'न्या<w>', '्र्र', 'रार्य<w>', 'प्रा', 'कर्रा', 'क्रार्', 'नारार', 'तारार', 'लित<w>', 'क्ष्', 'क्र्र', 'द्र्र<w>', 'लारा<w>', 'द्या<w>', '्र्य<w>', 'र्रू', 'मारू', 'समार्', 'सारार्', 'अप्र<w>', 'र<w>', 'ॻ', 'रार्र', 'कारा', 'च', 'कारारा<w>', 'ॣ', 'क्ष्र<w>', 'स्', 'ता<w>', 'जिया<w>', 'क्र<w>', 'प्रार', '2', 'जा', 'जित<w>', 'त्र्य<w>', 'र्र<w>', 'मिय<w>', 'ॲ', 'कर', 'त्रा<w>', 'पारा<w>', 'लिय', 'क्या<w>', 'विय<w>', 'किय<w>', 'तार', '्य', 'द्र्र', 'त्रार<w>', 'भ', 'वार्र', 'लिय<w>', 'क्र्र<w>', 'ञ', 'लार्र', '़', 'वि', 'ल', 'वार्र्', 'य<w>', 'रा', 'ग', 'वारू', 'क्रू', 'कर्या<w>', 'थ', 'समिक<w>', 'ॡ', 'करू', '4', 'मार्य<w>', 'ऐ', 'ॆ', 'ल्र', 'पारू', 'ल्रा', 'स्या<w>', 'ब', 'द्र्', 'कर्रार<w>', '्रारा<w>', 'कार्', 'सारा<w>', 'ारा<w>', 'मि', 'कर्रा<w>', 'लि', 'लिए<w>', 'ारार<w>', 'लार', 'ार्र्', 'सारा', 'ल्', 'क्र्रू', 'जारा', 'छ', 'अपारा', 'र्या<w>', 'ार्', 'द्रारा', 'में<w>', 'र्र', 'रार्', 'वित<w>', 'नारा', 'र्र्य', 'करार', 'ध', 'ऱ', 'रार<w>', 'कार्य<w>', '्र्र्य', 'प्रार<w>', 'रा<w>', 'द्रा', '्र्रू', 'हारू', 'भा', 'ारू', 'प्र<w>', 'त्या<w>', 'जार्', 'की<w>', 'रार', 'ॊ', 'ा<w>', 'द्र्र्र', '्र<w>', 'रारा<w>', 'र्र्र', 'मिक<w>', 'या<w>', 'ि', 'ज', 'ना', 'ार<w>', 'ऴ', 'ख़', 'समार<w>', 'ारारू', 'द्', 'अप', 'ी', 'ष्य<w>', 'ी<w>', 'एक<w>', '्र', 'र', 'जारू', 'लारा', 'प्र्रा', 'दे', 'वार्य', 'पार्र', 'भारा<w>', 'बार्र', 'सा', 'हो', 'ष्र', 'स्य<w>', 'अपर<w>', 'ष्र्य', 'स्था<w>', 'रू', 'पा', 'लार्र्य<w>', 'हा', 'र्र्रा', 'ल्र्र', 'अपार्य', 'अप्रा', 'करार्', 'ष्र्या<w>', 'ल्य', 'नार', 'वा<w>', 'तार्र', 'सा<w>', 'नार्', 'ष्य', 'समि<w>', 'ऌ', '्र्य', 'द्र्य<w>', 'तार्या<w>', 'जार्र', 'तारार्', 'व<w>', 'औ', 'वार्य<w>', 'हारा<w>', 'घ', 'कारा<w>', 'ं', 'भार्', 'न्य', 'समारू', 'र्र्', 'मार्या<w>', 'स्रा', 'कर्र', 'सम', 'त्रू', 'ल्या<w>', 'द्र<w>', 'क्', 'न्य<w>', 'कर्', 'स्र्र<w>', 'है<w>', 'त्य<w>', 'का<w>', 'प्र्य', 'तारा<w>', 'ॱ', 'क्य<w>', 'हैं<w>', 'ारारा<w>', 'ख', 'ष', '्र्', 'ण<w>', 'समिय', 'ार्रा<w>', 'ारार', 'ले<w>', 'अपार्', '्रार्', 'मिया<w>', 'ॄ', 'जि<w>', 'कार्रारा<w>', 'न्रा', 'स्थ', 'कार्र<w>', 'करारा<w>', 'किय', 'त्रार', 'के<w>', 'प्रारू', 'पार्', 'कार्या<w>', 'लार्य<w>', 'द<w>', 'अप्रारू', 'सार्', 'ऎ', '्रार<w>', 'कारार', 'हारार्', 'हो<w>', 'श<w>', 'ॐ', 'ड़', 'नित<w>', 'त्रार्', 'क्ष', 'मार्य', 'भारा', 'निय', 'मिय', 'जार<w>', 'निक<w>', 'स्रू', 'लार्', 'त्र्र', 'बार', 'कि', 'ल्र्', 'हारार<w>', 'क्र्या<w>', 'ार्र<w>', 'पा<w>', 'े', 'भारारा', 'स्य', 'क्ष्य', 'बारा<w>', 'हार्या<w>', 'ौ', 'फ', 'बारार<w>', 'आ', 'समारा<w>', 'िया<w>', 'ु', 'था<w>', 'वा', 'प्र्र<w>', 'क्रा<w>', 'ष्र्', '5', 'कार्रा', 'र्र्र्र्र्', 'इ', 'क्रार', 'ार्या<w>', '8', 'क्र्र्र्र', 'भी<w>', 'मा', 'जिय', 'र्रा<w>', 'ार्रा', 'प्रा<w>', 'ने<w>', 'न्र्य', 'स्र्र्र', 'समिया<w>', 'िय', 'बार्', 'वार<w>', 'ला', 'पर<w>', '<w>', 'प्र्र', 'प्र्र्र', 'र्रार<w>', 'ळ', 'न्र्य<w>', 'द्रा<w>', 'विया<w>', 'क्रारा<w>', 'क्र', 'क<w>', 'ही<w>', 'मार्', 'प्रू', 'स्र<w>', 'ति<w>', 'वार्या<w>', 'र्', 'न्र<w>', 'ार', 'हार्', 'सारू', 'त्रारू', 'प', 'किया<w>', 'स्रा<w>', 'त्र्रा<w>', 'न्र्र', 'ब<w>', 'नि<w>', 'जार', 'न्र', 'कर्र्', 'य़', 'मारा<w>', 'सार<w>', '्य<w>', 'स', 'ार्रू', '्रारा', 'कर<w>', 'भा<w>', '0', 'करा', 'र्य', 'जार्य<w>', 'हा<w>', 'वारार<w>', 'करारार्य<w>', 'ष्रा', 'सं', 'पारा', 'ल<w>', 'न<w>', 'जि', 'क्र्', 'बारू', '्रा', 'द', 'त्य', 'मित<w>', 'सार्य', 'त्र्य', 'बार<w>', 'दे<w>', 'हार्य', 'ारा', 'नार्या<w>', 'ग<w>', 'स<w>', 'द्रार', 'ॾ', 'क्ष्र्', 'बा', 'ढ़', '9', 'समा<w>', '्रू', 'ना<w>', 'क्र्र्र', 'भार<w>', 'स्र', 'िय<w>', 'लार<w>', 'मार्र', 'ारारा', 'जिय<w>', 'भारू', 'हों<w>', 'बा<w>', 'और<w>', 'रारार्', 'र्रार', 'विय', 'कारू', 'तार्य', 'त्रा', '्र्रा', 'तार<w>', '्र्र्', 'नार<w>', 'ा', 'मा<w>', 'पार्र<w>', 'ॢ', 'मार<w>', 'अप्र्य', 'ित<w>', 'कार्र्य', 'सार्य<w>', 'ल्य<w>', 'ै', 'नार्र्', 'ढ', 'वारा', 'ॿ', 'नि', 'त्र<w>', 'निय<w>', 'फ़', 'पार्य<w>', '्र्र<w>', 'र्र्र्र', 'ती<w>', 'भार्या<w>', 'ह<w>', 'जारा<w>', 'ई', 'हार्य<w>', '1', 'नार्र', 'नार्य', 'ं<w>', 'समा', 'ऋ', 'अपार', 'पार<w>', 'नार्य<w>', 'अपार<w>'}

In [32]:
len(bpe_set)

667

In [33]:
with open('bpe_set.txt', 'w') as f:
  for word in bpe_set:
    f.write(word+"\n")

### Creating skipgram data

#### Replacing words to integers

In [ ]:
import pandas as pd
unique_words = pd.read_csv("vocabulary.csv").drop('Unnamed: 0', axis='columns')

In [ ]:
cleaned_text = open("cleaned_data.txt", "r").read()

In [ ]:
";" in cleaned_text

False

In [ ]:
unique_words

              Word    count
0               के  3460205
1               है  2567639
2              में  2554180
3               की  1745880
4               और  1693280
...            ...      ...
508200  अर्थानुरणन        2
508201      ॠथियों        2
508202        ॠणों        2
508203  अर्थानुसार        2
508204       <UNK>        0

[508205 rows x 2 columns]

In [ ]:
unique_words.reset_index(inplace=True)

In [ ]:
unique_words

         index        Word    count
0            0          के  3460205
1            1          है  2567639
2            2         में  2554180
3            3          की  1745880
4            4          और  1693280
...        ...         ...      ...
508200  508200  अर्थानुरणन        2
508201  508201      ॠथियों        2
508202  508202        ॠणों        2
508203  508203  अर्थानुसार        2
508204  508204       <UNK>        0

[508205 rows x 3 columns]

In [ ]:
unique_words.to_csv("vocabulary.csv")

In [ ]:
int_words = unique_words['Word'].to_dict()

In [ ]:
sum(unique_words['index'] == unique_words.index)

508205

In [ ]:
len(unique_words)

508205

In [ ]:
int_words.keys()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
word_int = {value: key for key, value in int_words.items()}

In [ ]:
len(word_int)

508205

In [ ]:
text_int = {}

i = 0

for word in cleaned_text.split(" "):
  if word in word_int:
    text_int[i] = word_int[word]
  else:
    text_int[i] = word_int[r'<UNK>']
  i+=1

In [ ]:
text_int

{0: 142,
 1: 2,
 2: 1694,
 3: 14,
 4: 1416,
 5: 4,
 6: 493,
 7: 3,
 8: 2507,
 9: 36027,
 10: 493,
 11: 62426,
 12: 4,
 13: 22963,
 14: 1807,
 15: 50,
 16: 4,
 17: 2601,
 18: 378,
 19: 0,
 20: 323,
 21: 77141,
 22: 21,
 23: 35,
 24: 1694,
 25: 6,
 26: 1100,
 27: 378,
 28: 0,
 29: 323,
 30: 488133,
 31: 25870,
 32: 1694,
 33: 14,
 34: 81,
 35: 44739,
 36: 25,
 37: 31,
 38: 44739,
 39: 25,
 40: 14766,
 41: 1694,
 42: 14,
 43: 62154,
 44: 7,
 45: 345,
 46: 15,
 47: 486,
 48: 1,
 49: 4,
 50: 1694,
 51: 14,
 52: 62154,
 53: 7,
 54: 48802,
 55: 5,
 56: 241,
 57: 21532,
 58: 1694,
 59: 14,
 60: 62154,
 61: 7,
 62: 152,
 63: 4,
 64: 48802,
 65: 7,
 66: 740,
 67: 81,
 68: 35,
 69: 21758,
 70: 112,
 71: 114,
 72: 11448,
 73: 56,
 74: 20,
 75: 87,
 76: 31832,
 77: 152,
 78: 25,
 79: 50290,
 80: 1694,
 81: 14,
 82: 81,
 83: 378,
 84: 0,
 85: 133,
 86: 9,
 87: 177,
 88: 1738,
 89: 25,
 90: 15,
 91: 378,
 92: 93,
 93: 153,
 94: 25,
 95: 54155,
 96: 1694,
 97: 14,
 98: 9,
 99: 1738,
 100: 253,
 101: 86,
 102: 367,
 103: 0,
 104: 378,
 105: 4,
 106: 86,
 107: 323,
 108: 0,
 109: 378,
 110: 7,
 111: 241,
 112: 241,
 113: 17,
 114: 4,
 115: 3275,
 116: 24,
 117: 25,
 118: 14766,
 119: 1694,
 120: 14,
 121: 92,
 122: 1738,
 123: 7,
 124: 1416,
 125: 81,
 126: 35,
 127: 21758,
 128: 112,
 129: 114,
 130: 11448,
 131: 56,
 132: 20,
 133: 87,
 134: 549,
 135: 152,
 136: 25,
 137: 50290,
 138: 1694,
 139: 14,
 140: 81,
 141: 1416,
 142: 0,
 143: 367,
 144: 6,
 145: 378,
 146: 9,
 147: 163,
 148: 2,
 149: 2737,
 150: 25,
 151: 332,
 152: 4,
 153: 5675,
 154: 487,
 155: 583,
 156: 222,
 157: 4,
 158: 3275,
 159: 24,
 160: 25,
 161: 14766,
 162: 1694,
 163: 14,
 164: 5675,
 165: 487,
 166: 7,
 167: 493,
 168: 81,
 169: 35,
 170: 22,
 171: 378,
 172: 2737,
 173: 56,
 174: 863,
 175: 196,
 176: 789,
 177: 81,
 178: 4,
 179: 1694,
 180: 14,
 181: 345,
 182: 15,
 183: 486,
 184: 14612,
 185: 1694,
 186: 14,
 187: 81,
 188: 493,
 189: 5,
 190: 4239,
 191: 2847,
 192: 35,
 193: 1891,
 194: 91,
 195: 408,
 196: 408,
 197: 1843,
 198: 4,
 199: 93973,
 200: 1712,
 201: 12,
 202: 702,
 203: 1891,
 204: 7674,
 205: 2,
 206: 9,
 207: 9,
 208: 3,
 209: 638,
 210: 0,
 211: 136,
 212: 109,
 213: 8,
 214: 493,
 215: 10,
 216: 126400,
 217: 4,
 218: 3275,
 219: 24,
 220: 25,
 221: 176068,
 222: 493,
 223: 5,
 224: 4239,
 225: 2847,
 226: 4,
 227: 408,
 228: 408,
 229: 1843,
 230: 503,
 231: 2,
 232: 71,
 233: 71,
 234: 638,
 235: 0,
 236: 136,
 237: 1891,
 238: 44,
 239: 1,
 240: 4,
 241: 93973,
 242: 1712,
 243: 702,
 244: 1891,
 245: 9,
 246: 9,
 247: 3,
 248: 638,
 249: 0,
 250: 136,
 251: 7674,
 252: 2,
 253: 109,
 254: 8,
 255: 32267,
 256: 4,
 257: 1694,
 258: 14,
 259: 345,
 260: 15,
 261: 486,
 262: 38563,
 263: 21758,
 264: 112,
 265: 114,
 266: 11448,
 267: 56,
 268: 20,
 269: 87,
 270: 1882,
 271: 152,
 272: 25,
 273: 50290,
 274: 1694,
 275: 14,
 276: 81,
 277: 152,
 278: 7,
 279: 740,
 280: 5,
 281: 241,
 282: 30,
 283: 0,
 284: 132,
 285: 1416,
 286: 0,
 287: 1738,
 288: 2,
 289: 125879,
 290: 485,
 291: 4,
 292: 49,
 293: 9858,
 294: 4,
 295: 2364,
 296: 13742,
 297: 4,
 298: 576,
 299: 4,
 300: 321,
 301: 0,
 302: 90,
 303: 41674,
 304: 49,
 305: 125879,
 306: 1416,
 307: 0,
 308: 1738,
 309: 2,
 310: 493,
 311: 10,
 312: 499,
 313: 225,
 314: 165,
 315: 12,
 316: 18392,
 317: 4,
 318: 3275,
 319: 24,
 320: 25,
 321: 25214,
 322: 1694,
 323: 14,
 324: 93,
 325: 239,
 326: 125879,
 327: 16428,
 328: 134,
 329: 2,
 330: 5,
 331: 239,
 332: 4399,
 333: 7,
 334: 152,
 335: 10,
 336: 11703,
 337: 30,
 338: 0,
 339: 132,
 340: 4,
 341: 757,
 342: 4399,
 343: 7,
 344: 740,
 345: 10,
 346: 11703,
 347: 30,
 348: 0,
 349: 132,
 350: 267,
 351: 4,
 352: 82054,
 353: 7,
 354: 12,
 355: 508204,
 356: 14,
 357: 134,
 358: 7,
 359: 1416,
 360: 0,
 361: 1738,
 362: 2,
 363: 1717,
 364: 269,
 365: 15,
 366: 49,
 367: 493,
 368: 10,
 369: 499,
 370: 508204,
 371: 152,
 372: 4,
 373: 740,
 374: 10,
 375: 11703,
 376: 169,
 377: 4,
 378: 62154,
 379: 7,
 380: 48802,
 381: 5,
 382: 241,
 383: 169,
 384: 4,
 385: 1694,
 386: 14,
 387: 345,
 388: 15,
 389: 486,
 390: 38563,
 391: 21758,
 392: 112,
 393: 114,
 394: 11448,
 395: 56,
 396: 20,
 397: 87,
 398: 3503,
 399: 152,
 400: 25,
 401: 50290,
 402: 1694,
 403: 14,
 404: 81,
 405: 378,
 406: 1136,
 407: 2366,
 408: 5,
 409: 84,
 410: 24,
 411: 456,
 412: 332,
 413: 4,
 414: 1995,
 415: 493,
 416: 0,
 417: 323,
 418: 1416,
 419: 0,
 420: 1738,
 421: 2,
 422: 508204,
 423: 1694,
 424: 14,
 425: 638,
 426: 638,
 427: 0,
 428: 234,
 429: 234,
 430: 448657,
 431: 3,
 432: 4,
 433: 134,
 434: 219,
 435: 1136,
 436: 2366,
 437: 3,
 438: 12,
 439: 2507,
 440: 3,
 441: 22,
 442: 1062,
 443: 8419,
 444: 8,
 445: 503,
 446: 5,
 447: 378,
 448: 84,
 449: 24,
 450: 456,
 451: 26,
 452: 4,
 453: 9,
 454: 9,
 455: 638,
 456: 0,
 457: 7322,
 458: 91,
 459: 2697,
 460: 3,
 461: 12,
 462: 2507,
 463: 3,
 464: 4,
 465: 1694,
 466: 14,
 467: 345,
 468: 15,
 469: 486,
 470: 4779,
 471: 1694,
 472: 14,
 473: 18,
 474: 55913,
 475: 564,
 476: 13086,
 477: 137,
 478: 15,
 479: 196726,
 480: 4,
 481: 789,
 482: 0,
 483: 378,
 484: 2,
 485: 456,
 486: 1632,
 487: 4,
 488: 1995,
 489: 493,
 490: 10,
 491: 508204,
 492: 21758,
 493: 112,
 494: 114,
 495: 11448,
 496: 56,
 497: 20,
 498: 87,
 499: 10364,
 500: 152,
 501: 25,
 502: 50290,
 503: 1694,
 504: 14,
 505: 81,
 506: 493,
 507: 5,
 508: 9,
 509: 9,
 510: 638,
 511: 0,
 512: 1136,
 513: 2028,
 514: 1094,
 515: 1301,
 516: 1737,
 517: 4,
 518: 27297,
 519: 91,
 520: 11600,
 521: 4,
 522: 493,
 523: 0,
 524: 124286,
 525: 638,
 526: 638,
 527: 0,
 528: 136,
 529: 359,
 530: 485,
 531: 4,
 532: 3275,
 533: 24,
 534: 25,
 535: 175943,
 536: 1694,
 537: 14,
 538: 493,
 539: 0,
 540: 638,
 541: 638,
 542: 0,
 543: 1113,
 544: 2092,
 545: 7,
 546: 4,
 547: 638,
 548: 638,
 549: 0,
 550: 1301,
 551: 2092,
 552: 7,
 553: 4,
 554: 638,
 555: 638,
 556: 0,
 557: 487,
 558: 10,
 559: 219,
 560: 27297,
 561: 91,
 562: 11254,
 563: 7,
 564: 267,
 565: 4,
 566: 1694,
 567: 14,
 568: 345,
 569: 15,
 570: 486,
 571: 14612,
 572: 1694,
 573: 14,
 574: 81,
 575: 118,
 576: 554,
 577: 7,
 578: 37,
 579: 856,
 580: 0,
 581: 136,
 582: 71,
 583: 1917,
 584: 2,
 585: 7982,
 586: 4,
 587: 49,
 588: 789,
 589: 3,
 590: 4551,
 591: 4,
 592: 1416,
 593: 0,
 594: 2697,
 595: 4,
 596: 1301,
 597: 2092,
 598: 4,
 599: 1168,
 600: 493,
 601: 10,
 602: 4,
 603: 219,
 604: 27297,
 605: 91,
 606: 11254,
 607: 10,
 608: 22,
 609: 493,
 610: 10,
 611: 35507,
 612: 8,
 613: 330,
 614: 182495,
 615: 1694,
 616: 14,
 617: 554,
 618: 7,
 619: 37,
 620: 856,
 621: 0,
 622: 136,
 623: 359,
 624: 17,
 625: 37,
 626: 24,
 627: 856,
 628: 0,
 629: 136,
 630: 1694,
 631: 14,
 632: 863,
 633: 359,
 634: 17,
 635: 2040,
 636: 4,
 637: 4366,
 638: 253,
 639: 196,
 640: 1880,
 641: 3,
 642: 2507,
 643: 36027,
 644: 1694,
 645: 14,
 646: 134,
 647: 7,
 648: 13086,
 649: 137,
 650: 4,
 651: 134,
 652: 5,
 653: 81,
 654: 196726,
 655: 4,
 656: 493,
 657: 2,
 658: 456,
 659: 1632,
 660: 4,
 661: 863,
 662: 37,
 663: 6510,
 664: 2,
 665: 27,
 666: 1299,
 667: 4,
 668: 789,
 669: 3,
 670: 4551,
 671: 35,
 672: 1416,
 673: 0,
 674: 2697,
 675: 4,
 676: 493,
 677: 10,
 678: 27297,
 679: 91,
 680: 219,
 681: 92794,
 682: 10,
 683: 330,
 684: 462058,
 685: 1694,
 686: 14,
 687: 134,
 688: 5,
 689: 81,
 690: 6732,
 691: 2928,
 692: 1891,
 693: 91,
 694: 408,
 695: 408,
 696: 1843,
 697: 1168,
 698: 493,
 699: 0,
 700: 323,
 701: 8,
 702: 4,
 703: 2928,
 704: 3870,
 705: 2,
 706: 1891,
 707: 91,
 708: 1149,
 709: 109,
 710: 8,
 711: 49,
 712: 219,
 713: 140,
 714: 14,
 715: 119,
 716: 7,
 717: 451,
 718: 8,
 719: 49,
 720: 271,
 721: 786,
 722: 0,
 723: 132,
 724: 12145,
 725: 2928,
 726: 493,
 727: 0,
 728: 1737,
 729: 4,
 730: 1416,
 731: 0,
 732: 1995,
 733: 4,
 734: 493,
 735: 10,
 736: 27297,
 737: 91,
 738: 11600,
 739: 8,
 740: 503,
 741: 2,
 742: 174,
 743: 0,
 744: 2691,
 745: 8,
 746: 134,
 747: 219,
 748: 0,
 749: 1499,
 750: 0,
 751: 132,
 752: 140,
 753: 14,
 754: 219,
 755: 2940,
 756: 2940,
 757: 408,
 758: 1843,
 759: 451,
 760: 8,
 761: 4,
 762: 3275,
 763: 24,
 764: 25,
 765: 25214,
 766: 1694,
 767: 14,
 768: 22,
 769: 43,
 770: 267,
 771: 21,
 772: 219,
 773: 7,
 774: 345,
 775: 31,
 776: 144,
 777: 345,
 778: 15,
 779: 39,
 780: 84,
 781: 24,
 782: 486,
 783: 1,
 784: 35,
 785: 21758,
 786: 112,
 787: 114,
 788: 11448,
 789: 56,
 790: 20,
 791: 87,
 792: 43398,
 793: 152,
 794: 25,
 795: 271093,
 796: 1416,
 797: 4,
 798: 493,
 799: 4,
 800: 120,
 801: 1168,
 802: 350,
 803: 6,
 804: 1342,
 805: 559,
 806: 25,
 807: 14766,
 808: 1694,
 809: 14,
 810: 194,
 811: 135,
 812: 186,
 813: 39,
 814: 79,
 815: 21,
 816: 6206,
 817: 152,
 818: 559,
 819: 17,
 820: 4,
 821: 196,
 822: 37,
 823: 179,
 824: 63,
 825: 562,
 826: 135,
 827: 5,
 828: 6206,
 829: 152,
 830: 4882,
 831: 21532,
 832: 1694,
 833: 14,
 834: 6206,
 835: 152,
 836: 7,
 837: 13086,
 838: 137,
 839: 4,
 840: 1046,
 841: 3500,
 842: 178,
 843: 92,
 844: 2,
 845: 196,
 846: 71,
 847: 2507,
 848: 3,
 849: 482,
 850: 0,
 851: 562,
 852: 135,
 853: 5,
 854: 4882,
 855: 508204,
 856: 4,
 857: 493,
 858: 3,
 859: 1517,
 860: 6,
 861: 13737,
 862: 18,
 863: 1,
 864: 15,
 865: 68,
 866: 49,
 867: 359,
 868: 63,
 869: 1094,
 870: 232,
 871: 152,
 872: 1338,
 873: 1694,
 874: 14,
 875: 493,
 876: 4,
 877: 1416,
 878: 7,
 879: 322923,
 880: 1152,
 881: 6,
 882: 72,
 883: 4355,
 884: 487,
 885: 10,
 886: 62,
 887: 21,
 888: 4,
 889: 62,
 890: 1152,
 891: 6,
 892: 72,
 893: 906,
 894: 1843,
 895: 22356,
 896: 21,
 897: 178,
 898: 1338,
 899: 1694,
 900: 14,
 901: 493,
 902: 10,
 903: 378,
 904: 23,
 905: 9336,
 906: 21,
 907: 4,
 908: 487,
 909: 10,
 910: 1425,
 911: 30,
 912: 0,
 913: 132,
 914: 554,
 915: 12,
 916: 23,
 917: 168665,
 918: 17161,
 919: 493,
 920: 5,
 921: 4684,
 922: 21,
 923: 232,
 924: 5,
 925: 1168,
 926: 487,
 927: 133659,
 928: 106,
 929: 20707,
 930: 1338,
 931: 1694,
 932: 14,
 933: 5009,
 934: 7,
 935: 487,
 936: 3,
 937: 913,
 938: 5,
 939: 7023,
 940: 4,
 941: 86,
 942: 73481,
 943: 2,
 944: 174,
 945: 6,
 946: 6259,
 947: 19182,
 948: 45,
 949: 4,
 950: 5009,
 951: 97992,
 952: 2028,
 953: 242,
 954: 14766,
 955: 1338,
 956: 1694,
 957: 14,
 958: 131,
 959: 3,
 960: 129,
 961: 18067,
 962: 143,
 963: 2,
 964: 9,
 965: 22059,
 966: 4513,
 967: 4,
 968: 518,
 969: 5009,
 970: 7,
 971: 186,
 972: 196,
 973: 7023,
 974: 21,
 975: 1052,
 976: 17731,
 977: 1338,
 978: 1694,
 979: 14,
 980: 487,
 981: 5,
 982: 219,
 983: 3158,
 984: 0,
 985: 1712,
 986: 22,
 987: 679,
 988: 2,
 989: 6939,
 990: 4,
 991: 702,
 992: 1149,
 993: 1499,
 994: 2,
 995: 736,
 996: 8,
 997: 13549,
 998: 4,
 999: 22059,
 ...}

In [ ]:
c = 0
for _, value in text_int.items():
  if value == word_int[r'<UNK>']:
    c+=1

In [ ]:
c

342599

In [ ]:
unique_words.loc[508204] = [508204, r'<UNK>', c]

In [ ]:
unique_words.sort_values(by='count', inplace=True, ascending=False)

In [ ]:
unique_words

         index               Word    count
0            0                 के  3460205
1            1                 है  2567639
2            2                में  2554180
3            3                 की  1745880
4            4                 और  1693280
...        ...                ...      ...
508195  508195             ॠषिकेष        2
508196  508196               ॠषीऔ        2
508197  508197  खसराकंठमालारूबेला        2
508198  508198           खसराखसरा        2
508199  508199               ॲसलर        2

[508205 rows x 3 columns]

In [ ]:
text_int

{0: 142,
 1: 2,
 2: 1694,
 3: 14,
 4: 1416,
 5: 4,
 6: 493,
 7: 3,
 8: 2507,
 9: 36027,
 10: 493,
 11: 62426,
 12: 4,
 13: 22963,
 14: 1807,
 15: 50,
 16: 4,
 17: 2601,
 18: 378,
 19: 0,
 20: 323,
 21: 77141,
 22: 21,
 23: 35,
 24: 1694,
 25: 6,
 26: 1100,
 27: 378,
 28: 0,
 29: 323,
 30: 488133,
 31: 25870,
 32: 1694,
 33: 14,
 34: 81,
 35: 44739,
 36: 25,
 37: 31,
 38: 44739,
 39: 25,
 40: 14766,
 41: 1694,
 42: 14,
 43: 62154,
 44: 7,
 45: 345,
 46: 15,
 47: 486,
 48: 1,
 49: 4,
 50: 1694,
 51: 14,
 52: 62154,
 53: 7,
 54: 48802,
 55: 5,
 56: 241,
 57: 21532,
 58: 1694,
 59: 14,
 60: 62154,
 61: 7,
 62: 152,
 63: 4,
 64: 48802,
 65: 7,
 66: 740,
 67: 81,
 68: 35,
 69: 21758,
 70: 112,
 71: 114,
 72: 11448,
 73: 56,
 74: 20,
 75: 87,
 76: 31832,
 77: 152,
 78: 25,
 79: 50290,
 80: 1694,
 81: 14,
 82: 81,
 83: 378,
 84: 0,
 85: 133,
 86: 9,
 87: 177,
 88: 1738,
 89: 25,
 90: 15,
 91: 378,
 92: 93,
 93: 153,
 94: 25,
 95: 54155,
 96: 1694,
 97: 14,
 98: 9,
 99: 1738,
 100: 253,
 101: 86,
 102: 367,
 103: 0,
 104: 378,
 105: 4,
 106: 86,
 107: 323,
 108: 0,
 109: 378,
 110: 7,
 111: 241,
 112: 241,
 113: 17,
 114: 4,
 115: 3275,
 116: 24,
 117: 25,
 118: 14766,
 119: 1694,
 120: 14,
 121: 92,
 122: 1738,
 123: 7,
 124: 1416,
 125: 81,
 126: 35,
 127: 21758,
 128: 112,
 129: 114,
 130: 11448,
 131: 56,
 132: 20,
 133: 87,
 134: 549,
 135: 152,
 136: 25,
 137: 50290,
 138: 1694,
 139: 14,
 140: 81,
 141: 1416,
 142: 0,
 143: 367,
 144: 6,
 145: 378,
 146: 9,
 147: 163,
 148: 2,
 149: 2737,
 150: 25,
 151: 332,
 152: 4,
 153: 5675,
 154: 487,
 155: 583,
 156: 222,
 157: 4,
 158: 3275,
 159: 24,
 160: 25,
 161: 14766,
 162: 1694,
 163: 14,
 164: 5675,
 165: 487,
 166: 7,
 167: 493,
 168: 81,
 169: 35,
 170: 22,
 171: 378,
 172: 2737,
 173: 56,
 174: 863,
 175: 196,
 176: 789,
 177: 81,
 178: 4,
 179: 1694,
 180: 14,
 181: 345,
 182: 15,
 183: 486,
 184: 14612,
 185: 1694,
 186: 14,
 187: 81,
 188: 493,
 189: 5,
 190: 4239,
 191: 2847,
 192: 35,
 193: 1891,
 194: 91,
 195: 408,
 196: 408,
 197: 1843,
 198: 4,
 199: 93973,
 200: 1712,
 201: 12,
 202: 702,
 203: 1891,
 204: 7674,
 205: 2,
 206: 9,
 207: 9,
 208: 3,
 209: 638,
 210: 0,
 211: 136,
 212: 109,
 213: 8,
 214: 493,
 215: 10,
 216: 126400,
 217: 4,
 218: 3275,
 219: 24,
 220: 25,
 221: 176068,
 222: 493,
 223: 5,
 224: 4239,
 225: 2847,
 226: 4,
 227: 408,
 228: 408,
 229: 1843,
 230: 503,
 231: 2,
 232: 71,
 233: 71,
 234: 638,
 235: 0,
 236: 136,
 237: 1891,
 238: 44,
 239: 1,
 240: 4,
 241: 93973,
 242: 1712,
 243: 702,
 244: 1891,
 245: 9,
 246: 9,
 247: 3,
 248: 638,
 249: 0,
 250: 136,
 251: 7674,
 252: 2,
 253: 109,
 254: 8,
 255: 32267,
 256: 4,
 257: 1694,
 258: 14,
 259: 345,
 260: 15,
 261: 486,
 262: 38563,
 263: 21758,
 264: 112,
 265: 114,
 266: 11448,
 267: 56,
 268: 20,
 269: 87,
 270: 1882,
 271: 152,
 272: 25,
 273: 50290,
 274: 1694,
 275: 14,
 276: 81,
 277: 152,
 278: 7,
 279: 740,
 280: 5,
 281: 241,
 282: 30,
 283: 0,
 284: 132,
 285: 1416,
 286: 0,
 287: 1738,
 288: 2,
 289: 125879,
 290: 485,
 291: 4,
 292: 49,
 293: 9858,
 294: 4,
 295: 2364,
 296: 13742,
 297: 4,
 298: 576,
 299: 4,
 300: 321,
 301: 0,
 302: 90,
 303: 41674,
 304: 49,
 305: 125879,
 306: 1416,
 307: 0,
 308: 1738,
 309: 2,
 310: 493,
 311: 10,
 312: 499,
 313: 225,
 314: 165,
 315: 12,
 316: 18392,
 317: 4,
 318: 3275,
 319: 24,
 320: 25,
 321: 25214,
 322: 1694,
 323: 14,
 324: 93,
 325: 239,
 326: 125879,
 327: 16428,
 328: 134,
 329: 2,
 330: 5,
 331: 239,
 332: 4399,
 333: 7,
 334: 152,
 335: 10,
 336: 11703,
 337: 30,
 338: 0,
 339: 132,
 340: 4,
 341: 757,
 342: 4399,
 343: 7,
 344: 740,
 345: 10,
 346: 11703,
 347: 30,
 348: 0,
 349: 132,
 350: 267,
 351: 4,
 352: 82054,
 353: 7,
 354: 12,
 355: 508204,
 356: 14,
 357: 134,
 358: 7,
 359: 1416,
 360: 0,
 361: 1738,
 362: 2,
 363: 1717,
 364: 269,
 365: 15,
 366: 49,
 367: 493,
 368: 10,
 369: 499,
 370: 508204,
 371: 152,
 372: 4,
 373: 740,
 374: 10,
 375: 11703,
 376: 169,
 377: 4,
 378: 62154,
 379: 7,
 380: 48802,
 381: 5,
 382: 241,
 383: 169,
 384: 4,
 385: 1694,
 386: 14,
 387: 345,
 388: 15,
 389: 486,
 390: 38563,
 391: 21758,
 392: 112,
 393: 114,
 394: 11448,
 395: 56,
 396: 20,
 397: 87,
 398: 3503,
 399: 152,
 400: 25,
 401: 50290,
 402: 1694,
 403: 14,
 404: 81,
 405: 378,
 406: 1136,
 407: 2366,
 408: 5,
 409: 84,
 410: 24,
 411: 456,
 412: 332,
 413: 4,
 414: 1995,
 415: 493,
 416: 0,
 417: 323,
 418: 1416,
 419: 0,
 420: 1738,
 421: 2,
 422: 508204,
 423: 1694,
 424: 14,
 425: 638,
 426: 638,
 427: 0,
 428: 234,
 429: 234,
 430: 448657,
 431: 3,
 432: 4,
 433: 134,
 434: 219,
 435: 1136,
 436: 2366,
 437: 3,
 438: 12,
 439: 2507,
 440: 3,
 441: 22,
 442: 1062,
 443: 8419,
 444: 8,
 445: 503,
 446: 5,
 447: 378,
 448: 84,
 449: 24,
 450: 456,
 451: 26,
 452: 4,
 453: 9,
 454: 9,
 455: 638,
 456: 0,
 457: 7322,
 458: 91,
 459: 2697,
 460: 3,
 461: 12,
 462: 2507,
 463: 3,
 464: 4,
 465: 1694,
 466: 14,
 467: 345,
 468: 15,
 469: 486,
 470: 4779,
 471: 1694,
 472: 14,
 473: 18,
 474: 55913,
 475: 564,
 476: 13086,
 477: 137,
 478: 15,
 479: 196726,
 480: 4,
 481: 789,
 482: 0,
 483: 378,
 484: 2,
 485: 456,
 486: 1632,
 487: 4,
 488: 1995,
 489: 493,
 490: 10,
 491: 508204,
 492: 21758,
 493: 112,
 494: 114,
 495: 11448,
 496: 56,
 497: 20,
 498: 87,
 499: 10364,
 500: 152,
 501: 25,
 502: 50290,
 503: 1694,
 504: 14,
 505: 81,
 506: 493,
 507: 5,
 508: 9,
 509: 9,
 510: 638,
 511: 0,
 512: 1136,
 513: 2028,
 514: 1094,
 515: 1301,
 516: 1737,
 517: 4,
 518: 27297,
 519: 91,
 520: 11600,
 521: 4,
 522: 493,
 523: 0,
 524: 124286,
 525: 638,
 526: 638,
 527: 0,
 528: 136,
 529: 359,
 530: 485,
 531: 4,
 532: 3275,
 533: 24,
 534: 25,
 535: 175943,
 536: 1694,
 537: 14,
 538: 493,
 539: 0,
 540: 638,
 541: 638,
 542: 0,
 543: 1113,
 544: 2092,
 545: 7,
 546: 4,
 547: 638,
 548: 638,
 549: 0,
 550: 1301,
 551: 2092,
 552: 7,
 553: 4,
 554: 638,
 555: 638,
 556: 0,
 557: 487,
 558: 10,
 559: 219,
 560: 27297,
 561: 91,
 562: 11254,
 563: 7,
 564: 267,
 565: 4,
 566: 1694,
 567: 14,
 568: 345,
 569: 15,
 570: 486,
 571: 14612,
 572: 1694,
 573: 14,
 574: 81,
 575: 118,
 576: 554,
 577: 7,
 578: 37,
 579: 856,
 580: 0,
 581: 136,
 582: 71,
 583: 1917,
 584: 2,
 585: 7982,
 586: 4,
 587: 49,
 588: 789,
 589: 3,
 590: 4551,
 591: 4,
 592: 1416,
 593: 0,
 594: 2697,
 595: 4,
 596: 1301,
 597: 2092,
 598: 4,
 599: 1168,
 600: 493,
 601: 10,
 602: 4,
 603: 219,
 604: 27297,
 605: 91,
 606: 11254,
 607: 10,
 608: 22,
 609: 493,
 610: 10,
 611: 35507,
 612: 8,
 613: 330,
 614: 182495,
 615: 1694,
 616: 14,
 617: 554,
 618: 7,
 619: 37,
 620: 856,
 621: 0,
 622: 136,
 623: 359,
 624: 17,
 625: 37,
 626: 24,
 627: 856,
 628: 0,
 629: 136,
 630: 1694,
 631: 14,
 632: 863,
 633: 359,
 634: 17,
 635: 2040,
 636: 4,
 637: 4366,
 638: 253,
 639: 196,
 640: 1880,
 641: 3,
 642: 2507,
 643: 36027,
 644: 1694,
 645: 14,
 646: 134,
 647: 7,
 648: 13086,
 649: 137,
 650: 4,
 651: 134,
 652: 5,
 653: 81,
 654: 196726,
 655: 4,
 656: 493,
 657: 2,
 658: 456,
 659: 1632,
 660: 4,
 661: 863,
 662: 37,
 663: 6510,
 664: 2,
 665: 27,
 666: 1299,
 667: 4,
 668: 789,
 669: 3,
 670: 4551,
 671: 35,
 672: 1416,
 673: 0,
 674: 2697,
 675: 4,
 676: 493,
 677: 10,
 678: 27297,
 679: 91,
 680: 219,
 681: 92794,
 682: 10,
 683: 330,
 684: 462058,
 685: 1694,
 686: 14,
 687: 134,
 688: 5,
 689: 81,
 690: 6732,
 691: 2928,
 692: 1891,
 693: 91,
 694: 408,
 695: 408,
 696: 1843,
 697: 1168,
 698: 493,
 699: 0,
 700: 323,
 701: 8,
 702: 4,
 703: 2928,
 704: 3870,
 705: 2,
 706: 1891,
 707: 91,
 708: 1149,
 709: 109,
 710: 8,
 711: 49,
 712: 219,
 713: 140,
 714: 14,
 715: 119,
 716: 7,
 717: 451,
 718: 8,
 719: 49,
 720: 271,
 721: 786,
 722: 0,
 723: 132,
 724: 12145,
 725: 2928,
 726: 493,
 727: 0,
 728: 1737,
 729: 4,
 730: 1416,
 731: 0,
 732: 1995,
 733: 4,
 734: 493,
 735: 10,
 736: 27297,
 737: 91,
 738: 11600,
 739: 8,
 740: 503,
 741: 2,
 742: 174,
 743: 0,
 744: 2691,
 745: 8,
 746: 134,
 747: 219,
 748: 0,
 749: 1499,
 750: 0,
 751: 132,
 752: 140,
 753: 14,
 754: 219,
 755: 2940,
 756: 2940,
 757: 408,
 758: 1843,
 759: 451,
 760: 8,
 761: 4,
 762: 3275,
 763: 24,
 764: 25,
 765: 25214,
 766: 1694,
 767: 14,
 768: 22,
 769: 43,
 770: 267,
 771: 21,
 772: 219,
 773: 7,
 774: 345,
 775: 31,
 776: 144,
 777: 345,
 778: 15,
 779: 39,
 780: 84,
 781: 24,
 782: 486,
 783: 1,
 784: 35,
 785: 21758,
 786: 112,
 787: 114,
 788: 11448,
 789: 56,
 790: 20,
 791: 87,
 792: 43398,
 793: 152,
 794: 25,
 795: 271093,
 796: 1416,
 797: 4,
 798: 493,
 799: 4,
 800: 120,
 801: 1168,
 802: 350,
 803: 6,
 804: 1342,
 805: 559,
 806: 25,
 807: 14766,
 808: 1694,
 809: 14,
 810: 194,
 811: 135,
 812: 186,
 813: 39,
 814: 79,
 815: 21,
 816: 6206,
 817: 152,
 818: 559,
 819: 17,
 820: 4,
 821: 196,
 822: 37,
 823: 179,
 824: 63,
 825: 562,
 826: 135,
 827: 5,
 828: 6206,
 829: 152,
 830: 4882,
 831: 21532,
 832: 1694,
 833: 14,
 834: 6206,
 835: 152,
 836: 7,
 837: 13086,
 838: 137,
 839: 4,
 840: 1046,
 841: 3500,
 842: 178,
 843: 92,
 844: 2,
 845: 196,
 846: 71,
 847: 2507,
 848: 3,
 849: 482,
 850: 0,
 851: 562,
 852: 135,
 853: 5,
 854: 4882,
 855: 508204,
 856: 4,
 857: 493,
 858: 3,
 859: 1517,
 860: 6,
 861: 13737,
 862: 18,
 863: 1,
 864: 15,
 865: 68,
 866: 49,
 867: 359,
 868: 63,
 869: 1094,
 870: 232,
 871: 152,
 872: 1338,
 873: 1694,
 874: 14,
 875: 493,
 876: 4,
 877: 1416,
 878: 7,
 879: 322923,
 880: 1152,
 881: 6,
 882: 72,
 883: 4355,
 884: 487,
 885: 10,
 886: 62,
 887: 21,
 888: 4,
 889: 62,
 890: 1152,
 891: 6,
 892: 72,
 893: 906,
 894: 1843,
 895: 22356,
 896: 21,
 897: 178,
 898: 1338,
 899: 1694,
 900: 14,
 901: 493,
 902: 10,
 903: 378,
 904: 23,
 905: 9336,
 906: 21,
 907: 4,
 908: 487,
 909: 10,
 910: 1425,
 911: 30,
 912: 0,
 913: 132,
 914: 554,
 915: 12,
 916: 23,
 917: 168665,
 918: 17161,
 919: 493,
 920: 5,
 921: 4684,
 922: 21,
 923: 232,
 924: 5,
 925: 1168,
 926: 487,
 927: 133659,
 928: 106,
 929: 20707,
 930: 1338,
 931: 1694,
 932: 14,
 933: 5009,
 934: 7,
 935: 487,
 936: 3,
 937: 913,
 938: 5,
 939: 7023,
 940: 4,
 941: 86,
 942: 73481,
 943: 2,
 944: 174,
 945: 6,
 946: 6259,
 947: 19182,
 948: 45,
 949: 4,
 950: 5009,
 951: 97992,
 952: 2028,
 953: 242,
 954: 14766,
 955: 1338,
 956: 1694,
 957: 14,
 958: 131,
 959: 3,
 960: 129,
 961: 18067,
 962: 143,
 963: 2,
 964: 9,
 965: 22059,
 966: 4513,
 967: 4,
 968: 518,
 969: 5009,
 970: 7,
 971: 186,
 972: 196,
 973: 7023,
 974: 21,
 975: 1052,
 976: 17731,
 977: 1338,
 978: 1694,
 979: 14,
 980: 487,
 981: 5,
 982: 219,
 983: 3158,
 984: 0,
 985: 1712,
 986: 22,
 987: 679,
 988: 2,
 989: 6939,
 990: 4,
 991: 702,
 992: 1149,
 993: 1499,
 994: 2,
 995: 736,
 996: 8,
 997: 13549,
 998: 4,
 999: 22059,
 ...}

In [ ]:
i = 0
window = 5

In [ ]:
data_list = list(text_int.values())

In [ ]:
int_words[27]

'कर'

In [ ]:
i = 27482

In [ ]:
[data_list[i]]*(window*2)

[39, 39, 39, 39, 39, 39, 39, 39, 39, 39]

In [ ]:
data_list[i-window:i] + data_list[i+1:i+window+1]

[4, 86, 147, 26, 4, 390, 5274, 88697, 39, 3839]

In [ ]:
len(data_list)

82035716

In [ ]:
pairs = {
    'int': [],
    'target': [],
    'pred': []
}
for i in range(window, len(data_list)-window-1):
  dic = {
      'int': [data_list[i]]*(window*2),
      'target':data_list[i-window:i] + data_list[i+1:i+window+1],
      'pred': [1]*(window*2)
  }
  pairs['int'].extend(dic['int'])
  pairs['target'].extend(dic['target'])
  pairs['pred'].extend(dic['pred'])

  if i%10000000==0:
    print('words processed: ',i)

words processed:  10000000
words processed:  20000000
words processed:  30000000
words processed:  40000000
words processed:  50000000
words processed:  60000000
words processed:  70000000
words processed:  80000000

In [ ]:
pairs

{'int': [4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2507,
  2507,
  2507,
  2507,
  2507,
  2507,
  2507,
  2507,
  2507,
  2507,
  36027,
  36027,
  36027,
  36027,
  36027,
  36027,
  36027,
  36027,
  36027,
  36027,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  493,
  62426,
  62426,
  62426,
  62426,
  62426,
  62426,
  62426,
  62426,
  62426,
  62426,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  22963,
  22963,
  22963,
  22963,
  22963,
  22963,
  22963,
  22963,
  22963,
  22963,
  1807,
  1807,
  1807,
  1807,
  1807,
  1807,
  1807,
  1807,
  1807,
  1807,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  2601,
  2601,
  2601,
  2601,
  2601,
  2601,
  2601,
  2601,
  2601,
  2601,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  77141,
  77141,
  77141,
  77141,
  77141,
  77141,
  77141,
  77141,
  77141,
  77141,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  21,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  6,
  1100,
  1100,
  1100,
  1100,
  1100,
  1100,
  1100,
  1100,
  1100,
  1100,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  323,
  488133,
  488133,
  488133,
  488133,
  488133,
  488133,
  488133,
  488133,
  488133,
  488133,
  25870,
  25870,
  25870,
  25870,
  25870,
  25870,
  25870,
  25870,
  25870,
  25870,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  31,
  31,
  31,
  31,
  31,
  31,
  31,
  31,
  31,
  31,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  44739,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  14766,
  14766,
  14766,
  14766,
  14766,
  14766,
  14766,
  14766,
  14766,
  14766,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  345,
  345,
  345,
  345,
  345,
  345,
  345,
  345,
  345,
  345,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  486,
  486,
  486,
  486,
  486,
  486,
  486,
  486,
  486,
  486,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  241,
  241,
  241,
  241,
  241,
  241,
  241,
  241,
  241,
  241,
  21532,
  21532,
  21532,
  21532,
  21532,
  21532,
  21532,
  21532,
  21532,
  21532,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  62154,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  4,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  48802,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  740,
  740,
  740,
  740,
  740,
  740,
  740,
  740,
  740,
  740,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  21758,
  21758,
  21758,
  21758,
  21758,
  21758,
  21758,
  21758,
  21758,
  21758,
  112,
  112,
  112,
  112,
  112,
  112,
  112,
  112,
  112,
  112,
  114,
  114,
  114,
  114,
  114,
  114,
  114,
  114,
  114,
  114,
  11448,
  11448,
  11448,
  11448,
  11448,
  11448,
  11448,
  11448,
  11448,
  11448,
  56,
  56,
  56,
  56,
  56,
  56,
  56,
  56,
  56,
  56,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  87,
  87,
  87,
  87,
  87,
  87,
  87,
  87,
  87,
  87,
  31832,
  31832,
  31832,
  31832,
  31832,
  31832,
  31832,
  31832,
  31832,
  31832,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  152,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  50290,
  50290,
  50290,
  50290,
  50290,
  50290,
  50290,
  50290,
  50290,
  50290,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  81,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  133,
  133,
  133,
  133,
  133,
  133,
  133,
  133,
  133,
  133,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  177,
  177,
  177,
  177,
  177,
  177,
  177,
  177,
  177,
  177,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  15,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  93,
  93,
  93,
  93,
  93,
  93,
  93,
  93,
  93,
  93,
  153,
  153,
  153,
  153,
  153,
  153,
  153,
  153,
  153,
  153,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  25,
  54155,
  54155,
  54155,
  54155,
  54155,
  54155,
  54155,
  54155,
  54155,
  54155,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  1694,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  9,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  1738,
  253,
  253,
  253,
  253,
  253,
  253,
  253,
  253,
  253,
  253,
  86,
  86,
  86,
  86,
  86,
  86,
  86,
  86,
  86,
  86,
  367,
  367,
  367,
  367,
  367,
  367,
  367,
  367,
  367,
  367,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  378,
  ...],
 'target': [142,
  2,
  1694,
  14,
  1416,
  493,
  3,
  2507,
  36027,
  493,
  2,
  1694,
  14,
  1416,
  4,
  3,
  2507,
  36027,
  493,
  62426,
  1694,
  14,
  1416,
  4,
  493,
  2507,
  36027,
  493,
  62426,
  4,
  14,
  1416,
  4,
  493,
  3,
  36027,
  493,
  62426,
  4,
  22963,
  1416,
  4,
  493,
  3,
  2507,
  493,
  62426,
  4,
  22963,
  1807,
  4,
  493,
  3,
  2507,
  36027,
  62426,
  4,
  22963,
  1807,
  50,
  493,
  3,
  2507,
  36027,
  493,
  4,
  22963,
  1807,
  50,
  4,
  3,
  2507,
  36027,
  493,
  62426,
  22963,
  1807,
  50,
  4,
  2601,
  2507,
  36027,
  493,
  62426,
  4,
  1807,
  50,
  4,
  2601,
  378,
  36027,
  493,
  62426,
  4,
  22963,
  50,
  4,
  2601,
  378,
  0,
  493,
  62426,
  4,
  22963,
  1807,
  4,
  2601,
  378,
  0,
  323,
  62426,
  4,
  22963,
  1807,
  50,
  2601,
  378,
  0,
  323,
  77141,
  4,
  22963,
  1807,
  50,
  4,
  378,
  0,
  323,
  77141,
  21,
  22963,
  1807,
  50,
  4,
  2601,
  0,
  323,
  77141,
  21,
  35,
  1807,
  50,
  4,
  2601,
  378,
  323,
  77141,
  21,
  35,
  1694,
  50,
  4,
  2601,
  378,
  0,
  77141,
  21,
  35,
  1694,
  6,
  4,
  2601,
  378,
  0,
  323,
  21,
  35,
  1694,
  6,
  1100,
  2601,
  378,
  0,
  323,
  77141,
  35,
  1694,
  6,
  1100,
  378,
  378,
  0,
  323,
  77141,
  21,
  1694,
  6,
  1100,
  378,
  0,
  0,
  323,
  77141,
  21,
  35,
  6,
  1100,
  378,
  0,
  323,
  323,
  77141,
  21,
  35,
  1694,
  1100,
  378,
  0,
  323,
  488133,
  77141,
  21,
  35,
  1694,
  6,
  378,
  0,
  323,
  488133,
  25870,
  21,
  35,
  1694,
  6,
  1100,
  0,
  323,
  488133,
  25870,
  1694,
  35,
  1694,
  6,
  1100,
  378,
  323,
  488133,
  25870,
  1694,
  14,
  1694,
  6,
  1100,
  378,
  0,
  488133,
  25870,
  1694,
  14,
  81,
  6,
  1100,
  378,
  0,
  323,
  25870,
  1694,
  14,
  81,
  44739,
  1100,
  378,
  0,
  323,
  488133,
  1694,
  14,
  81,
  44739,
  25,
  378,
  0,
  323,
  488133,
  25870,
  14,
  81,
  44739,
  25,
  31,
  0,
  323,
  488133,
  25870,
  1694,
  81,
  44739,
  25,
  31,
  44739,
  323,
  488133,
  25870,
  1694,
  14,
  44739,
  25,
  31,
  44739,
  25,
  488133,
  25870,
  1694,
  14,
  81,
  25,
  31,
  44739,
  25,
  14766,
  25870,
  1694,
  14,
  81,
  44739,
  31,
  44739,
  25,
  14766,
  1694,
  1694,
  14,
  81,
  44739,
  25,
  44739,
  25,
  14766,
  1694,
  14,
  14,
  81,
  44739,
  25,
  31,
  25,
  14766,
  1694,
  14,
  62154,
  81,
  44739,
  25,
  31,
  44739,
  14766,
  1694,
  14,
  62154,
  7,
  44739,
  25,
  31,
  44739,
  25,
  1694,
  14,
  62154,
  7,
  345,
  25,
  31,
  44739,
  25,
  14766,
  14,
  62154,
  7,
  345,
  15,
  31,
  44739,
  25,
  14766,
  1694,
  62154,
  7,
  345,
  15,
  486,
  44739,
  25,
  14766,
  1694,
  14,
  7,
  345,
  15,
  486,
  1,
  25,
  14766,
  1694,
  14,
  62154,
  345,
  15,
  486,
  1,
  4,
  14766,
  1694,
  14,
  62154,
  7,
  15,
  486,
  1,
  4,
  1694,
  1694,
  14,
  62154,
  7,
  345,
  486,
  1,
  4,
  1694,
  14,
  14,
  62154,
  7,
  345,
  15,
  1,
  4,
  1694,
  14,
  62154,
  62154,
  7,
  345,
  15,
  486,
  4,
  1694,
  14,
  62154,
  7,
  7,
  345,
  15,
  486,
  1,
  1694,
  14,
  62154,
  7,
  48802,
  345,
  15,
  486,
  1,
  4,
  14,
  62154,
  7,
  48802,
  5,
  15,
  486,
  1,
  4,
  1694,
  62154,
  7,
  48802,
  5,
  241,
  486,
  1,
  4,
  1694,
  14,
  7,
  48802,
  5,
  241,
  21532,
  1,
  4,
  1694,
  14,
  62154,
  48802,
  5,
  241,
  21532,
  1694,
  4,
  1694,
  14,
  62154,
  7,
  5,
  241,
  21532,
  1694,
  14,
  1694,
  14,
  62154,
  7,
  48802,
  241,
  21532,
  1694,
  14,
  62154,
  14,
  62154,
  7,
  48802,
  5,
  21532,
  1694,
  14,
  62154,
  7,
  62154,
  7,
  48802,
  5,
  241,
  1694,
  14,
  62154,
  7,
  152,
  7,
  48802,
  5,
  241,
  21532,
  14,
  62154,
  7,
  152,
  4,
  48802,
  5,
  241,
  21532,
  1694,
  62154,
  7,
  152,
  4,
  48802,
  5,
  241,
  21532,
  1694,
  14,
  7,
  152,
  4,
  48802,
  7,
  241,
  21532,
  1694,
  14,
  62154,
  152,
  4,
  48802,
  7,
  740,
  21532,
  1694,
  14,
  62154,
  7,
  4,
  48802,
  7,
  740,
  81,
  1694,
  14,
  62154,
  7,
  152,
  48802,
  7,
  740,
  81,
  35,
  14,
  62154,
  7,
  152,
  4,
  7,
  740,
  81,
  35,
  21758,
  62154,
  7,
  152,
  4,
  48802,
  740,
  81,
  35,
  21758,
  112,
  7,
  152,
  4,
  48802,
  7,
  81,
  35,
  21758,
  112,
  114,
  152,
  4,
  48802,
  7,
  740,
  35,
  21758,
  112,
  114,
  11448,
  4,
  48802,
  7,
  740,
  81,
  21758,
  112,
  114,
  11448,
  56,
  48802,
  7,
  740,
  81,
  35,
  112,
  114,
  11448,
  56,
  20,
  7,
  740,
  81,
  35,
  21758,
  114,
  11448,
  56,
  20,
  87,
  740,
  81,
  35,
  21758,
  112,
  11448,
  56,
  20,
  87,
  31832,
  81,
  35,
  21758,
  112,
  114,
  56,
  20,
  87,
  31832,
  152,
  35,
  21758,
  112,
  114,
  11448,
  20,
  87,
  31832,
  152,
  25,
  21758,
  112,
  114,
  11448,
  56,
  87,
  31832,
  152,
  25,
  50290,
  112,
  114,
  11448,
  56,
  20,
  31832,
  152,
  25,
  50290,
  1694,
  114,
  11448,
  56,
  20,
  87,
  152,
  25,
  50290,
  1694,
  14,
  11448,
  56,
  20,
  87,
  31832,
  25,
  50290,
  1694,
  14,
  81,
  56,
  20,
  87,
  31832,
  152,
  50290,
  1694,
  14,
  81,
  378,
  20,
  87,
  31832,
  152,
  25,
  1694,
  14,
  81,
  378,
  0,
  87,
  31832,
  152,
  25,
  50290,
  14,
  81,
  378,
  0,
  133,
  31832,
  152,
  25,
  50290,
  1694,
  81,
  378,
  0,
  133,
  9,
  152,
  25,
  50290,
  1694,
  14,
  378,
  0,
  133,
  9,
  177,
  25,
  50290,
  1694,
  14,
  81,
  0,
  133,
  9,
  177,
  1738,
  50290,
  1694,
  14,
  81,
  378,
  133,
  9,
  177,
  1738,
  25,
  1694,
  14,
  81,
  378,
  0,
  9,
  177,
  1738,
  25,
  15,
  14,
  81,
  378,
  0,
  133,
  177,
  1738,
  25,
  15,
  378,
  81,
  378,
  0,
  133,
  9,
  1738,
  25,
  15,
  378,
  93,
  378,
  0,
  133,
  9,
  177,
  25,
  15,
  378,
  93,
  153,
  0,
  133,
  9,
  177,
  1738,
  15,
  378,
  93,
  153,
  25,
  133,
  9,
  177,
  1738,
  25,
  378,
  93,
  153,
  25,
  54155,
  9,
  177,
  1738,
  25,
  15,
  93,
  153,
  25,
  54155,
  1694,
  177,
  1738,
  25,
  15,
  378,
  153,
  25,
  54155,
  1694,
  14,
  1738,
  25,
  15,
  378,
  93,
  25,
  54155,
  1694,
  14,
  9,
  25,
  15,
  378,
  93,
  153,
  54155,
  1694,
  14,
  9,
  1738,
  15,
  378,
  93,
  153,
  25,
  1694,
  14,
  9,
  1738,
  253,
  378,
  93,
  153,
  25,
  54155,
  14,
  9,
  1738,
  253,
  86,
  93,
  153,
  25,
  54155,
  1694,
  9,
  1738,
  253,
  86,
  367,
  153,
  25,
  54155,
  1694,
  14,
  1738,
  253,
  86,
  367,
  0,
  25,
  54155,
  1694,
  14,
  9,
  253,
  86,
  367,
  0,
  378,
  54155,
  1694,
  14,
  9,
  1738,
  86,
  367,
  0,
  378,
  4,
  1694,
  14,
  9,
  1738,
  253,
  367,
  0,
  378,
  4,
  86,
  14,
  9,
  1738,
  253,
  86,
  0,
  378,
  4,
  86,
  323,
  9,
  1738,
  253,
  86,
  367,
  378,
  4,
  86,
  323,
  0,
  1738,
  253,
  86,
  367,
  0,
  4,
  86,
  323,
  0,
  378,
  ...],
 'pred': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  ...]}

In [ ]:
sg_data = pd.DataFrame(columns=('int', 'target', 'pred'))

In [ ]:
sg_data

Empty DataFrame
Columns: [int, target, pred]
Index: []

In [ ]:
sg_data = pd.concat([sg_data, pd.DataFrame(pairs)], axis='rows')

In [ ]:
sg_data=sg_data.reset_index()

In [ ]:
sg_data = sg_data.drop('index', axis='columns')

In [ ]:
sg_data

           int target pred
0            4    142    1
1            4      2    1
2            4   1694    1
3            4     14    1
4            4   1416    1
...        ...    ...  ...
820357045  486    725    1
820357046  486      4    1
820357047  486    437    1
820357048  486   4638    1
820357049  486     12    1

[820357050 rows x 3 columns]

In [ ]:
sg_data.to_csv("sg_data.csv")

#### Negative Sampling

Finding the current positive predictions for each context word

In [ ]:
import pandas as pd
sg_data = pd.read_csv("sg_data.csv").drop('Unnamed: 0', axis='columns')

In [ ]:
unique_words = pd.read_csv("vocabulary.csv").drop('Unnamed: 0', axis='columns')

In [ ]:
sg_data

           int  target  pred
0            4     142     1
1            4       2     1
2            4    1694     1
3            4      14     1
4            4    1416     1
...        ...     ...   ...
820357045  486     725     1
820357046  486       4     1
820357047  486     437     1
820357048  486    4638     1
820357049  486      12     1

[820357050 rows x 3 columns]

In [ ]:
sg_data['int'].unique()

array([     4,    493,      3, ..., 326832, 487196, 497553])

In [ ]:
sg_data[sg_data['int'] == 20]['target'].values

array([21758,   112,   114, ..., 14538,     6,  2140])

In [ ]:
tar_position = sg_data.groupby('int')['target'].apply(lambda x: [x.unique(), len(x)]).to_dict()

In [ ]:
tar_position[0]

[array([  1807,     50,      4, ..., 487196, 173397, 497553]), 34602050]

In [ ]:
len(tar_position)

508205

In [ ]:
tar_position[9]

[array([    14,     81,    378, ..., 326832, 497553, 487491]), 7921560]

In [ ]:
sg_data['int'].value_counts().mean()

np.float64(1614.224673114196)

In [ ]:
len(np.unique(neg_sg_pairs["int"]))

159

In [ ]:
import numpy as np
import pandas as pd
import time
import os # Import os for file operations

vocab_size = len(unique_words)
oversample_factor = 2

# Define the output file name for negative samples chunks
neg_samples_chunk_file = 'neg_sg_pairs_chunk_temp.csv'

# Remove the file if it already exists to start fresh, and write header
if os.path.exists(neg_samples_chunk_file):
    os.remove(neg_samples_chunk_file)
# Write header initially (this ensures the CSV is properly structured for appending)
pd.DataFrame(columns=['int', 'target', 'pred']).to_csv(neg_samples_chunk_file, mode='w', header=True, index=False)

processed_context_words_count = 0
start_time = time.time()

for context_word_id, (positive_targets, num_positive_samples) in tar_position.items():
    forbidden_words_set = set(positive_targets)
    forbidden_words_set.add(context_word_id)

    collected_negative_samples_for_current_word = []

    while len(collected_negative_samples_for_current_word) < num_positive_samples:
        needed_count = num_positive_samples - len(collected_negative_samples_for_current_word)
        batch_size = needed_count * oversample_factor

        candidates = np.random.randint(0, vocab_size, size=batch_size)
        valid_candidates = candidates[~np.isin(candidates, list(forbidden_words_set))]
        collected_negative_samples_for_current_word.extend(valid_candidates)

    final_negative_samples = collected_negative_samples_for_current_word[:num_positive_samples]

    # Create a small DataFrame for the current context word's negative samples
    temp_df_chunk = pd.DataFrame({
        'int': [context_word_id] * len(final_negative_samples),
        'target': final_negative_samples,
        'pred': 0
    })

    # Append the chunk to the temporary CSV file without writing header again
    temp_df_chunk.to_csv(neg_samples_chunk_file, mode='a', header=False, index=False)

    processed_context_words_count += 1
    if processed_context_words_count % 1000 == 0:
        elapsed_time = time.time() - start_time
        print(f"Processed {processed_context_words_count}/{len(tar_position)} context words. Elapsed: {elapsed_time:.2f}s")

end_time = time.time()
print(f"Total time taken for negative sampling and writing to chunk file: {end_time - start_time:.2f}s")

Processed 1000/508205 context words. Elapsed: 330.09s
Processed 2000/508205 context words. Elapsed: 369.51s
Processed 3000/508205 context words. Elapsed: 390.13s
Processed 4000/508205 context words. Elapsed: 405.83s
Processed 5000/508205 context words. Elapsed: 416.19s
Processed 6000/508205 context words. Elapsed: 424.41s
Processed 7000/508205 context words. Elapsed: 432.80s
Processed 8000/508205 context words. Elapsed: 438.50s
Processed 9000/508205 context words. Elapsed: 443.49s
Processed 10000/508205 context words. Elapsed: 447.85s
Processed 11000/508205 context words. Elapsed: 451.71s
Processed 12000/508205 context words. Elapsed: 455.22s
Processed 13000/508205 context words. Elapsed: 459.97s
Processed 14000/508205 context words. Elapsed: 462.99s
Processed 15000/508205 context words. Elapsed: 465.79s
Processed 16000/508205 context words. Elapsed: 468.41s
Processed 17000/508205 context words. Elapsed: 470.86s
Processed 18000/508205 context words. Elapsed: 473.20s
Processed 19000/508205 context words. Elapsed: 475.50s
Processed 20000/508205 context words. Elapsed: 477.83s
Processed 21000/508205 context words. Elapsed: 479.95s
Processed 22000/508205 context words. Elapsed: 481.96s
Processed 23000/508205 context words. Elapsed: 483.88s
Processed 24000/508205 context words. Elapsed: 485.77s
Processed 25000/508205 context words. Elapsed: 487.48s
Processed 26000/508205 context words. Elapsed: 489.11s
Processed 27000/508205 context words. Elapsed: 491.83s
Processed 28000/508205 context words. Elapsed: 493.36s
Processed 29000/508205 context words. Elapsed: 494.96s
Processed 30000/508205 context words. Elapsed: 496.51s
Processed 31000/508205 context words. Elapsed: 498.05s
Processed 32000/508205 context words. Elapsed: 499.56s
Processed 33000/508205 context words. Elapsed: 501.09s
Processed 34000/508205 context words. Elapsed: 502.58s
Processed 35000/508205 context words. Elapsed: 504.05s
Processed 36000/508205 context words. Elapsed: 505.51s
Processed 37000/508205 context words. Elapsed: 506.98s
Processed 38000/508205 context words. Elapsed: 508.44s
Processed 39000/508205 context words. Elapsed: 509.86s
Processed 40000/508205 context words. Elapsed: 511.34s
Processed 41000/508205 context words. Elapsed: 512.81s
Processed 42000/508205 context words. Elapsed: 514.23s
Processed 43000/508205 context words. Elapsed: 515.65s
Processed 44000/508205 context words. Elapsed: 517.04s
Processed 45000/508205 context words. Elapsed: 518.43s
Processed 46000/508205 context words. Elapsed: 519.83s
Processed 47000/508205 context words. Elapsed: 521.85s
Processed 48000/508205 context words. Elapsed: 523.34s
Processed 49000/508205 context words. Elapsed: 524.73s
Processed 50000/508205 context words. Elapsed: 526.13s
Processed 51000/508205 context words. Elapsed: 527.53s
Processed 52000/508205 context words. Elapsed: 528.90s
Processed 53000/508205 context words. Elapsed: 530.29s
Processed 54000/508205 context words. Elapsed: 531.68s
Processed 55000/508205 context words. Elapsed: 533.13s
Processed 56000/508205 context words. Elapsed: 534.54s
Processed 57000/508205 context words. Elapsed: 536.05s
Processed 58000/508205 context words. Elapsed: 537.54s
Processed 59000/508205 context words. Elapsed: 539.01s
Processed 60000/508205 context words. Elapsed: 540.50s
Processed 61000/508205 context words. Elapsed: 541.99s
Processed 62000/508205 context words. Elapsed: 543.49s
Processed 63000/508205 context words. Elapsed: 544.96s
Processed 64000/508205 context words. Elapsed: 546.43s
Processed 65000/508205 context words. Elapsed: 547.91s
Processed 66000/508205 context words. Elapsed: 549.40s
Processed 67000/508205 context words. Elapsed: 550.87s
Processed 68000/508205 context words. Elapsed: 552.33s
Processed 69000/508205 context words. Elapsed: 554.09s
Processed 70000/508205 context words. Elapsed: 555.65s
Processed 71000/508205 context words. Elapsed: 557.12s
Processed 72000/508205 context words. Elapsed: 558.58s
Processed 73000/508205 context words. Elapsed: 560.02s
Processed 74000/508205 context words. Elapsed: 561.46s
Processed 75000/508205 context words. Elapsed: 562.90s
Processed 76000/508205 context words. Elapsed: 564.31s
Processed 77000/508205 context words. Elapsed: 565.80s
Processed 78000/508205 context words. Elapsed: 567.26s
Processed 79000/508205 context words. Elapsed: 568.70s
Processed 80000/508205 context words. Elapsed: 570.13s
Processed 81000/508205 context words. Elapsed: 571.55s
Processed 82000/508205 context words. Elapsed: 572.96s
Processed 83000/508205 context words. Elapsed: 574.38s
Processed 84000/508205 context words. Elapsed: 575.80s
Processed 85000/508205 context words. Elapsed: 577.25s
Processed 86000/508205 context words. Elapsed: 578.68s
Processed 87000/508205 context words. Elapsed: 580.12s
Processed 88000/508205 context words. Elapsed: 581.55s
Processed 89000/508205 context words. Elapsed: 582.99s
Processed 90000/508205 context words. Elapsed: 584.60s
Processed 91000/508205 context words. Elapsed: 586.11s
Processed 92000/508205 context words. Elapsed: 587.60s
Processed 93000/508205 context words. Elapsed: 589.02s
Processed 94000/508205 context words. Elapsed: 590.46s
Processed 95000/508205 context words. Elapsed: 591.89s
Processed 96000/508205 context words. Elapsed: 593.32s
Processed 97000/508205 context words. Elapsed: 594.73s
Processed 98000/508205 context words. Elapsed: 596.13s
Processed 99000/508205 context words. Elapsed: 597.56s
Processed 100000/508205 context words. Elapsed: 598.99s
Processed 101000/508205 context words. Elapsed: 600.39s
Processed 102000/508205 context words. Elapsed: 601.82s
Processed 103000/508205 context words. Elapsed: 603.25s
Processed 104000/508205 context words. Elapsed: 604.67s
Processed 105000/508205 context words. Elapsed: 606.08s
Processed 106000/508205 context words. Elapsed: 607.50s
Processed 107000/508205 context words. Elapsed: 608.95s
Processed 108000/508205 context words. Elapsed: 610.37s
Processed 109000/508205 context words. Elapsed: 611.79s
Processed 110000/508205 context words. Elapsed: 613.18s
Processed 111000/508205 context words. Elapsed: 614.68s
Processed 112000/508205 context words. Elapsed: 616.08s
Processed 113000/508205 context words. Elapsed: 617.47s
Processed 114000/508205 context words. Elapsed: 618.86s
Processed 115000/508205 context words. Elapsed: 620.31s
Processed 116000/508205 context words. Elapsed: 621.72s
Processed 117000/508205 context words. Elapsed: 623.27s
Processed 118000/508205 context words. Elapsed: 624.67s
Processed 119000/508205 context words. Elapsed: 626.09s
Processed 120000/508205 context words. Elapsed: 627.38s
Processed 121000/508205 context words. Elapsed: 628.41s
Processed 122000/508205 context words. Elapsed: 629.43s
Processed 123000/508205 context words. Elapsed: 630.48s
Processed 124000/508205 context words. Elapsed: 631.50s
Processed 125000/508205 context words. Elapsed: 632.53s
Processed 126000/508205 context words. Elapsed: 633.62s
Processed 127000/508205 context words. Elapsed: 634.67s
Processed 128000/508205 context words. Elapsed: 635.73s
Processed 129000/508205 context words. Elapsed: 636.80s
Processed 130000/508205 context words. Elapsed: 637.88s
Processed 131000/508205 context words. Elapsed: 638.94s
Processed 132000/508205 context words. Elapsed: 640.01s
Processed 133000/508205 context words. Elapsed: 641.09s
Processed 134000/508205 context words. Elapsed: 642.26s
Processed 135000/508205 context words. Elapsed: 643.65s
Processed 136000/508205 context words. Elapsed: 644.89s
Processed 137000/508205 context words. Elapsed: 646.05s
Processed 138000/508205 context words. Elapsed: 647.14s
Processed 139000/508205 context words. Elapsed: 648.23s
Processed 140000/508205 context words. Elapsed: 649.29s
Processed 141000/508205 context words. Elapsed: 650.36s
Processed 142000/508205 context words. Elapsed: 651.44s
Processed 143000/508205 context words. Elapsed: 652.53s
Processed 144000/508205 context words. Elapsed: 653.63s
Processed 145000/508205 context words. Elapsed: 654.70s
Processed 146000/508205 context words. Elapsed: 655.77s
Processed 147000/508205 context words. Elapsed: 656.86s
Processed 148000/508205 context words. Elapsed: 658.08s
Processed 149000/508205 context words. Elapsed: 659.49s
Processed 150000/508205 context words. Elapsed: 660.91s
Processed 151000/508205 context words. Elapsed: 662.32s
Processed 152000/508205 context words. Elapsed: 663.73s
Processed 153000/508205 context words. Elapsed: 665.12s
Processed 154000/508205 context words. Elapsed: 666.52s
Processed 155000/508205 context words. Elapsed: 667.92s
Processed 156000/508205 context words. Elapsed: 669.33s
Processed 157000/508205 context words. Elapsed: 670.80s
Processed 158000/508205 context words. Elapsed: 672.23s
Processed 159000/508205 context words. Elapsed: 673.67s
Processed 160000/508205 context words. Elapsed: 675.14s
Processed 161000/508205 context words. Elapsed: 676.68s
Processed 162000/508205 context words. Elapsed: 678.13s
Processed 163000/508205 context words. Elapsed: 679.56s
Processed 164000/508205 context words. Elapsed: 681.03s
Processed 165000/508205 context words. Elapsed: 682.45s
Processed 166000/508205 context words. Elapsed: 683.92s
Processed 167000/508205 context words. Elapsed: 685.37s
Processed 168000/508205 context words. Elapsed: 686.83s
Processed 169000/508205 context words. Elapsed: 688.28s
Processed 170000/508205 context words. Elapsed: 689.71s
Processed 171000/508205 context words. Elapsed: 691.14s
Processed 172000/508205 context words. Elapsed: 692.58s
Processed 173000/508205 context words. Elapsed: 694.04s
Processed 174000/508205 context words. Elapsed: 695.61s
Processed 175000/508205 context words. Elapsed: 697.07s
Processed 176000/508205 context words. Elapsed: 698.51s
Processed 177000/508205 context words. Elapsed: 699.96s
Processed 178000/508205 context words. Elapsed: 701.37s
Processed 179000/508205 context words. Elapsed: 702.79s
Processed 180000/508205 context words. Elapsed: 704.24s
Processed 181000/508205 context words. Elapsed: 705.77s
Processed 182000/508205 context words. Elapsed: 707.22s
Processed 183000/508205 context words. Elapsed: 708.64s
Processed 184000/508205 context words. Elapsed: 710.03s
Processed 185000/508205 context words. Elapsed: 711.43s
Processed 186000/508205 context words. Elapsed: 712.83s
Processed 187000/508205 context words. Elapsed: 714.23s
Processed 188000/508205 context words. Elapsed: 715.63s
Processed 189000/508205 context words. Elapsed: 717.05s
Processed 190000/508205 context words. Elapsed: 718.51s
Processed 191000/508205 context words. Elapsed: 719.94s
Processed 192000/508205 context words. Elapsed: 721.36s
Processed 193000/508205 context words. Elapsed: 722.79s
Processed 194000/508205 context words. Elapsed: 724.19s
Processed 195000/508205 context words. Elapsed: 725.60s
Processed 196000/508205 context words. Elapsed: 727.03s
Processed 197000/508205 context words. Elapsed: 728.43s
Processed 198000/508205 context words. Elapsed: 729.85s
Processed 199000/508205 context words. Elapsed: 731.31s
Processed 200000/508205 context words. Elapsed: 732.80s
Processed 201000/508205 context words. Elapsed: 734.19s
Processed 202000/508205 context words. Elapsed: 735.58s
Processed 203000/508205 context words. Elapsed: 737.10s
Processed 204000/508205 context words. Elapsed: 738.57s
Processed 205000/508205 context words. Elapsed: 740.06s
Processed 206000/508205 context words. Elapsed: 741.47s
Processed 207000/508205 context words. Elapsed: 742.87s
Processed 208000/508205 context words. Elapsed: 744.25s
Processed 209000/508205 context words. Elapsed: 745.71s
Processed 210000/508205 context words. Elapsed: 747.15s
Processed 211000/508205 context words. Elapsed: 748.58s
Processed 212000/508205 context words. Elapsed: 750.02s
Processed 213000/508205 context words. Elapsed: 751.50s
Processed 214000/508205 context words. Elapsed: 752.99s
Processed 215000/508205 context words. Elapsed: 754.47s
Processed 216000/508205 context words. Elapsed: 755.92s
Processed 217000/508205 context words. Elapsed: 757.35s
Processed 218000/508205 context words. Elapsed: 758.76s
Processed 219000/508205 context words. Elapsed: 760.16s
Processed 220000/508205 context words. Elapsed: 761.56s
Processed 221000/508205 context words. Elapsed: 762.97s
Processed 222000/508205 context words. Elapsed: 764.36s
Processed 223000/508205 context words. Elapsed: 765.75s
Processed 224000/508205 context words. Elapsed: 767.21s
Processed 225000/508205 context words. Elapsed: 768.68s
Processed 226000/508205 context words. Elapsed: 770.10s
Processed 227000/508205 context words. Elapsed: 771.51s
Processed 228000/508205 context words. Elapsed: 772.93s
Processed 229000/508205 context words. Elapsed: 774.33s
Processed 230000/508205 context words. Elapsed: 775.72s
Processed 231000/508205 context words. Elapsed: 777.11s
Processed 232000/508205 context words. Elapsed: 778.51s
Processed 233000/508205 context words. Elapsed: 779.93s
Processed 234000/508205 context words. Elapsed: 781.33s
Processed 235000/508205 context words. Elapsed: 782.74s
Processed 236000/508205 context words. Elapsed: 784.05s
Processed 237000/508205 context words. Elapsed: 785.06s
Processed 238000/508205 context words. Elapsed: 786.07s
Processed 239000/508205 context words. Elapsed: 787.10s
Processed 240000/508205 context words. Elapsed: 788.40s
Processed 241000/508205 context words. Elapsed: 789.44s
Processed 242000/508205 context words. Elapsed: 790.48s
Processed 243000/508205 context words. Elapsed: 791.48s
Processed 244000/508205 context words. Elapsed: 792.79s
Processed 245000/508205 context words. Elapsed: 794.21s
Processed 246000/508205 context words. Elapsed: 795.62s
Processed 247000/508205 context words. Elapsed: 797.05s
Processed 248000/508205 context words. Elapsed: 798.47s
Processed 249000/508205 context words. Elapsed: 799.90s
Processed 250000/508205 context words. Elapsed: 801.32s
Processed 251000/508205 context words. Elapsed: 802.73s
Processed 252000/508205 context words. Elapsed: 804.16s
Processed 253000/508205 context words. Elapsed: 805.60s
Processed 254000/508205 context words. Elapsed: 807.02s
Processed 255000/508205 context words. Elapsed: 808.45s
Processed 256000/508205 context words. Elapsed: 809.87s
Processed 257000/508205 context words. Elapsed: 811.26s
Processed 258000/508205 context words. Elapsed: 812.66s
Processed 259000/508205 context words. Elapsed: 814.16s
Processed 260000/508205 context words. Elapsed: 815.64s
Processed 261000/508205 context words. Elapsed: 817.06s
Processed 262000/508205 context words. Elapsed: 818.47s
Processed 263000/508205 context words. Elapsed: 819.88s
Processed 264000/508205 context words. Elapsed: 821.35s
Processed 265000/508205 context words. Elapsed: 822.79s
Processed 266000/508205 context words. Elapsed: 824.22s
Processed 267000/508205 context words. Elapsed: 825.67s
Processed 268000/508205 context words. Elapsed: 827.09s
Processed 269000/508205 context words. Elapsed: 828.58s
Processed 270000/508205 context words. Elapsed: 830.01s
Processed 271000/508205 context words. Elapsed: 831.43s
Processed 272000/508205 context words. Elapsed: 832.83s
Processed 273000/508205 context words. Elapsed: 834.24s
Processed 274000/508205 context words. Elapsed: 835.64s
Processed 275000/508205 context words. Elapsed: 837.02s
Processed 276000/508205 context words. Elapsed: 838.43s
Processed 277000/508205 context words. Elapsed: 839.85s
Processed 278000/508205 context words. Elapsed: 841.26s
Processed 279000/508205 context words. Elapsed: 842.68s
Processed 280000/508205 context words. Elapsed: 844.09s
Processed 281000/508205 context words. Elapsed: 845.53s
Processed 282000/508205 context words. Elapsed: 846.97s
Processed 283000/508205 context words. Elapsed: 848.45s
Processed 284000/508205 context words. Elapsed: 849.58s
Processed 285000/508205 context words. Elapsed: 850.97s
Processed 286000/508205 context words. Elapsed: 852.39s
Processed 287000/508205 context words. Elapsed: 853.90s
Processed 288000/508205 context words. Elapsed: 855.36s
Processed 289000/508205 context words. Elapsed: 856.79s
Processed 290000/508205 context words. Elapsed: 858.23s
Processed 291000/508205 context words. Elapsed: 859.64s
Processed 292000/508205 context words. Elapsed: 861.07s
Processed 293000/508205 context words. Elapsed: 862.48s
Processed 294000/508205 context words. Elapsed: 863.88s
Processed 295000/508205 context words. Elapsed: 865.29s
Processed 296000/508205 context words. Elapsed: 866.70s
Processed 297000/508205 context words. Elapsed: 868.10s
Processed 298000/508205 context words. Elapsed: 869.53s
Processed 299000/508205 context words. Elapsed: 870.94s
Processed 300000/508205 context words. Elapsed: 872.35s
Processed 301000/508205 context words. Elapsed: 873.76s
Processed 302000/508205 context words. Elapsed: 875.18s
Processed 303000/508205 context words. Elapsed: 876.58s
Processed 304000/508205 context words. Elapsed: 877.97s
Processed 305000/508205 context words. Elapsed: 879.37s
Processed 306000/508205 context words. Elapsed: 880.77s
Processed 307000/508205 context words. Elapsed: 882.14s
Processed 308000/508205 context words. Elapsed: 883.13s
Processed 309000/508205 context words. Elapsed: 884.13s
Processed 310000/508205 context words. Elapsed: 885.13s
Processed 311000/508205 context words. Elapsed: 886.13s
Processed 312000/508205 context words. Elapsed: 887.14s
Processed 313000/508205 context words. Elapsed: 888.13s
Processed 314000/508205 context words. Elapsed: 889.19s
Processed 315000/508205 context words. Elapsed: 890.62s
Processed 316000/508205 context words. Elapsed: 892.04s
Processed 317000/508205 context words. Elapsed: 893.48s
Processed 318000/508205 context words. Elapsed: 894.90s
Processed 319000/508205 context words. Elapsed: 896.31s
Processed 320000/508205 context words. Elapsed: 897.72s
Processed 321000/508205 context words. Elapsed: 899.15s
Processed 322000/508205 context words. Elapsed: 900.56s
Processed 323000/508205 context words. Elapsed: 901.99s
Processed 324000/508205 context words. Elapsed: 903.41s
Processed 325000/508205 context words. Elapsed: 904.84s
Processed 326000/508205 context words. Elapsed: 906.26s
Processed 327000/508205 context words. Elapsed: 907.67s
Processed 328000/508205 context words. Elapsed: 909.11s
Processed 329000/508205 context words. Elapsed: 910.54s
Processed 330000/508205 context words. Elapsed: 911.94s
Processed 331000/508205 context words. Elapsed: 913.35s
Processed 332000/508205 context words. Elapsed: 914.78s
Processed 333000/508205 context words. Elapsed: 916.19s
Processed 334000/508205 context words. Elapsed: 917.61s
Processed 335000/508205 context words. Elapsed: 919.03s
Processed 336000/508205 context words. Elapsed: 920.44s
Processed 337000/508205 context words. Elapsed: 921.85s
Processed 338000/508205 context words. Elapsed: 923.27s
Processed 339000/508205 context words. Elapsed: 924.72s
Processed 340000/508205 context words. Elapsed: 926.15s
Processed 341000/508205 context words. Elapsed: 927.54s
Processed 342000/508205 context words. Elapsed: 928.94s
Processed 343000/508205 context words. Elapsed: 930.36s
Processed 344000/508205 context words. Elapsed: 931.77s
Processed 345000/508205 context words. Elapsed: 933.18s
Processed 346000/508205 context words. Elapsed: 934.67s
Processed 347000/508205 context words. Elapsed: 936.08s
Processed 348000/508205 context words. Elapsed: 937.50s
Processed 349000/508205 context words. Elapsed: 938.91s
Processed 350000/508205 context words. Elapsed: 940.35s
Processed 351000/508205 context words. Elapsed: 941.78s
Processed 352000/508205 context words. Elapsed: 943.19s
Processed 353000/508205 context words. Elapsed: 944.59s
Processed 354000/508205 context words. Elapsed: 946.01s
Processed 355000/508205 context words. Elapsed: 947.42s
Processed 356000/508205 context words. Elapsed: 948.86s
Processed 357000/508205 context words. Elapsed: 950.30s
Processed 358000/508205 context words. Elapsed: 951.70s
Processed 359000/508205 context words. Elapsed: 953.12s

In [ ]:
unique_words

         index        Word    count
0            0          के  3460205
1            1          है  2567639
2            2         में  2554180
3            3          की  1745880
4            4          और  1693280
...        ...         ...      ...
508200  508200  अर्थानुरणन        2
508201  508201      ॠथियों        2
508202  508202        ॠणों        2
508203  508203  अर्थानुसार        2
508204  508204       <UNK>        0

[508205 rows x 3 columns]

In [ ]:
neg_sg_pairs = pd.read_csv('neg_sg_pairs_chunk_temp.csv')

In [ ]:
neg_sg_pairs

              int  target  pred
0               0  480347     0
1               0  411514     0
2               0  439285     0
3               0  446425     0
4               0  213592     0
...           ...     ...   ...
820357045  508204  159419     0
820357046  508204  383464     0
820357047  508204  458442     0
820357048  508204  126681     0
820357049  508204  271433     0

[820357050 rows x 3 columns]

In [ ]:
neg_sg_pairs.to_csv('neg_sg_pairs.csv')

In [ ]:
!pwd

/content/drive/MyDrive/DL

In [ ]:
sg_data = pd.concat([sg_data, neg_sg_pairs], axis='rows')

In [ ]:
sg_data

                index     int  target  pred
0                   0       4     142     1
1                   1       4       2     1
2                   2       4    1694     1
3                   3       4      14     1
4                   4       4    1416     1
...               ...     ...     ...   ...
1640714095  820357045  508204  159419     0
1640714096  820357046  508204  383464     0
1640714097  820357047  508204  458442     0
1640714098  820357048  508204  126681     0
1640714099  820357049  508204  271433     0

[1640714100 rows x 4 columns]

In [ ]:
sg_data.reset_index(inplace=True)

In [ ]:
sg_data = sg_data.drop('index', axis='columns')

In [ ]:
sg_data

               int  target  pred
0                4     142     1
1                4       2     1
2                4    1694     1
3                4      14     1
4                4    1416     1
...            ...     ...   ...
1640714095  508204  159419     0
1640714096  508204  383464     0
1640714097  508204  458442     0
1640714098  508204  126681     0
1640714099  508204  271433     0

[1640714100 rows x 3 columns]

In [ ]:
sg_data.to_csv("sg_data_total.csv")

In [ ]:
sg_data = sg_data.sample(frac=1).reset_index(drop=True)

In [ ]:
sg_data.to_csv("sg_data_total.csv")

In [ ]:
import pandas as pd
sg_data = pd.read_csv("sg_data_total.csv").drop('Unnamed: 0', axis='columns')

In [ ]:
sg_data

               int  target  pred
0                4     142     1
1                4       2     1
2                4    1694     1
3                4      14     1
4                4    1416     1
...            ...     ...   ...
1640714095  508204  159419     0
1640714096  508204  383464     0
1640714097  508204  458442     0
1640714098  508204  126681     0
1640714099  508204  271433     0

[1640714100 rows x 3 columns]

#### Splitting train, valid and test data

In [ ]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(sg_data, test_size=0.05, random_state=10)
test, val = train_test_split(test, test_size=0.5)

In [ ]:
train.to_csv('train.csv')

In [ ]:
test.to_csv('test.csv')

In [ ]:
val.to_csv('val.csv')

In [ ]:
train

              int  target  pred
1580728521  20448  110552     0
522802738    6314     133     1
368221966      34     523     1
1843805      1191      25     1
1170089517     87   47845     0
...           ...     ...   ...
1068604539     25  283054     0
574014784       0    4365     1
89128932      114      79     1
1283169405    318  306287     0
1165313289     82  230365     0

[1558678395 rows x 3 columns]

In [ ]:
!pwd

/content/drive/MyDrive/DL

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

# Load only the 'pred' column from train.csv
# Specify dtype for 'pred' to maintain memory efficiency
pred_column_only = pd.read_csv("train.csv", usecols=['pred'], dtype={'pred': 'int8'})

In [ ]:
pred_column_only['pred'].value_counts()

pred
1    779340819
0    779337576
Name: count, dtype: int64

### Vocabulary text for huggingface

In [ ]:
import pandas as pd

In [ ]:
vocab = pd.read_csv('vocabulary.csv').drop('Unnamed: 0', axis='columns')

In [ ]:
vocab

         index        Word    count
0            0          के  3460205
1            1          है  2567639
2            2         में  2554180
3            3          की  1745880
4            4          और  1693280
...        ...         ...      ...
508200  508200  अर्थानुरणन        2
508201  508201      ॠथियों        2
508202  508202        ॠणों        2
508203  508203  अर्थानुसार        2
508204  508204       <UNK>        0

[508205 rows x 3 columns]

In [ ]:
!ls Word2Vec_hindi/model

config.json  Word2Vec_hindi.bin

In [ ]:
with open('Word2Vec_hindi/model/vocab.txt', 'w') as f:
  for word in vocab['Word']:
    f.write(word+'\n')

In [ ]:
!ls Word2Vec_hindi/model

config.json  vocab.txt	Word2Vec_hindi.bin